import { PgLikeQuerierIt } from '../querier/pgLikeQuerier-test.js';
import { createSpec } from '../test/index.js';
import { BunSqlQuerierPool } from './bunSqlQuerierPool.js';

class BunCockroachIt extends PgLikeQuerierIt {
  constructor() {
    super(
      new BunSqlQuerierPool({
        url: 'cockroachdb://root@0.0.0.0:26257/defaultdb',
      }),
      'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
    );
  }
}

createSpec(new BunCockroachIt());
