import { AbstractSqlQuerierIt } from '../querier/abstractSqlQuerier-test.js';
import { createSpec } from '../test/index.js';
import { BunSqlQuerierPool } from './bunSqlQuerierPool.js';

class BunPostgresIt extends AbstractSqlQuerierIt {
  constructor() {
    super(
      new BunSqlQuerierPool({
        url: 'postgres://test:test@0.0.0.0:5442/test_bun_pg',
      }),
      'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
    );
  }

  override async beforeAll() {
    const querier = await this.pool.getQuerier();
    try {
      // pgvector extension must exist before any vector column can be created
      await querier.run('CREATE EXTENSION IF NOT EXISTS vector');
    } finally {
      await querier.release();
    }
    await super.beforeAll();
  }
}

createSpec(new BunPostgresIt());
