import { describe, expect, it } from 'vitest';
import { Item, User, VectorItem } from '../test/index.js';
import { CockroachDialect } from './cockroachDialect.js';

describe('CockroachDialect', () => {
  const dialect = new CockroachDialect({});

  it('should use cockroachdb identifier', () => {
    expect(dialect.dialectName).toBe('cockroachdb');
  });

  /**
   * Not Postgres' `reltuples`, which CockroachDB answers `NULL` for even straight after an `ANALYZE`
   * (verified live on v26.2) - deleting this override would silently start estimating every table at 0.
   */
  it('refuses a window function under a row lock, as Postgres does', () => {
    expect(dialect.supportsWindowWithRowLock).toBe(false);
  });

  it('estimatedCount should read its own statistics, not pg_class.reltuples', () => {
    const ctx = dialect.createContext();
    dialect.estimatedCount(ctx, User);
    expect(ctx.sql).toBe(
      'SELECT row_count "_uql_count" FROM [SHOW STATISTICS FOR TABLE "User"] ORDER BY created DESC LIMIT 1',
    );
    expect(ctx.values).toEqual([]);
  });

  it('upsert should not rely on xmax (unsupported by CockroachDB)', () => {
    const ctx = dialect.createContext();
    dialect.upsert(
      ctx,
      User,
      { email: true, companyId: true },
      {
        id: 1,
        name: 'Test',
        email: 'test@example.com',
        companyId: 1,
      },
    );
    expect(ctx.sql).toBe(
      'INSERT INTO "User" ("id", "name", "email", "companyId", "createdAt") VALUES ($2, $3, $4, $5, $6) ON CONFLICT ("email", "companyId") DO UPDATE SET "id" = EXCLUDED."id", "name" = EXCLUDED."name", "updatedAt" = $1 RETURNING "id" "id"',
    );
  });

  it('should use a real sequential IDENTITY column, not SERIAL (unique_rowid() overflows JS numbers)', () => {
    expect(dialect.serialPrimaryKey).toBe('BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
  });

  it('should sort by vector similarity using pgvector-style operators (native on CockroachDB)', () => {
    const ctx = dialect.createContext();
    dialect.find(ctx, VectorItem, {
      $select: { id: true },
      $sort: { vec: { $vector: [1, 2, 3] } },
      $limit: 10,
    });
    expect(ctx.sql).toBe('SELECT "id" FROM "VectorItem" ORDER BY "vec" <=> $1::vector LIMIT 10');
    expect(ctx.values).toEqual(['[1,2,3]']);
  });

  it('should sort by vector similarity with an explicit distance metric', () => {
    const ctx = dialect.createContext();
    dialect.find(ctx, VectorItem, {
      $select: { id: true },
      $sort: { vec: { $vector: [1, 2, 3], $distance: 'l2' } },
      $limit: 5,
    });
    expect(ctx.sql).toBe('SELECT "id" FROM "VectorItem" ORDER BY "vec" <-> $1::vector LIMIT 5');
  });

  it('should have pgvector-compatible index operator classes but no extension requirement (native type)', () => {
    expect(dialect.vectorMetrics).toEqual(
      new Map([
        ['cosine', { op: '<=>', opsSuffix: 'cosine' }],
        ['l2', { op: '<->', opsSuffix: 'l2' }],
        ['inner', { op: '<#>', opsSuffix: 'ip' }],
      ]),
    );
    expect(dialect.vectorExtension).toBeUndefined();
  });

  it('should not support l1 distance (CockroachDB has no vector_l1_ops)', () => {
    expect(dialect.vectorMetrics.has('l1')).toBe(false);

    const ctx = dialect.createContext();
    expect(() => dialect.find(ctx, VectorItem, { $sort: { vec: { $vector: [1, 2, 3], $distance: 'l1' } } })).toThrow(
      'cockroachdb does not support vector distance metric: l1',
    );
  });

  it('should not resolve a distance operator via the prototype chain for an unvalidated value', () => {
    const ctx = dialect.createContext();
    // 'toString' is not an own property of `vectorMetrics`, but `Object.prototype.toString` exists -
    // a naive `in`/bracket-access check would resolve it as if it were a supported metric.
    expect(() =>
      dialect.find(ctx, VectorItem, { $sort: { vec: { $vector: [1, 2, 3], $distance: 'toString' as any } } }),
    ).toThrow('cockroachdb does not support vector distance metric: toString');
  });

  it('should support $text full-text search via to_tsvector/to_tsquery (verified to work on CockroachDB)', () => {
    const ctx = dialect.createContext();
    dialect.find(ctx, Item, {
      $select: { id: true },
      $where: { $text: { $fields: ['name', 'description'], $value: 'some text' } },
    });
    expect(ctx.sql).toBe(
      'SELECT "id" FROM "Item" WHERE to_tsvector("name" || \' \' || "description") @@ websearch_to_tsquery($1)',
    );
    expect(ctx.values).toEqual(['some text']);
  });
});
