import { expect } from 'vitest';
import { PgFamilySpec } from '../dialect/pgFamilyDialect-spec.js';
import { createSpec, Item, User, VectorItem } from '../test/index.js';
import { CockroachDialect } from './cockroachDialect.js';

/**
 * CockroachDB over the Postgres-wire suite, plus what is its own: statistics it keeps itself, an
 * `IDENTITY` key, a native vector type with pgvector's operators but only three of its metrics.
 */
class CockroachDialectSpec extends PgFamilySpec {
  /** Typed as its own dialect for the members only CockroachDB has (`vectorMetrics`). */
  readonly crdb = new CockroachDialect({});

  constructor() {
    super(new CockroachDialect({}));
  }

  /** CockroachDB has no `xmax`, so its upsert returns the id and nothing else. */
  protected override readonly upsertCreatedFlag = '';

  shouldUseItsOwnDialectName() {
    expect(this.dialect.dialectName).toBe('cockroachdb');
  }

  /**
   * Not Postgres' `reltuples`, which CockroachDB answers `NULL` for even straight after an `ANALYZE`
   * (verified live on v26.2) - deleting this override would silently start estimating every table at 0.
   */
  override shouldEstimatedCount() {
    const ctx = this.dialect.createContext();
    this.dialect.estimatedCount(ctx, User);
    expect(ctx.sql).toBe(
      'SELECT row_count "_uql_count" FROM [SHOW STATISTICS FOR TABLE "User"] ORDER BY created DESC LIMIT 1',
    );
    expect(ctx.values).toEqual([]);
  }

  shouldUseAnIdentityPrimaryKey() {
    expect(this.dialect.serialPrimaryKey).toBe('BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
  }

  shouldSortByVectorSimilarity() {
    const ctx = this.dialect.createContext();
    this.dialect.find(ctx, VectorItem, {
      $select: { id: true },
      $sort: { vec: { $vector: [1, 2, 3] } },
      $limit: 10,
    });
    expect(ctx.sql).toBe('SELECT "id" FROM "VectorItem" ORDER BY "vec" <=> $1::vector LIMIT 10');
    expect(ctx.values).toEqual(['[1,2,3]']);
  }

  shouldSortByVectorSimilarityWithAMetric() {
    const ctx = this.dialect.createContext();
    this.dialect.find(ctx, VectorItem, {
      $select: { id: true },
      $sort: { vec: { $vector: [1, 2, 3], $distance: 'l2' } },
      $limit: 5,
    });
    expect(ctx.sql).toBe('SELECT "id" FROM "VectorItem" ORDER BY "vec" <-> $1::vector LIMIT 5');
  }

  shouldHaveVectorOperatorClassesAndNoExtension() {
    expect(this.crdb.vectorMetrics).toEqual(
      new Map([
        ['cosine', { op: '<=>', opsSuffix: 'cosine' }],
        ['l2', { op: '<->', opsSuffix: 'l2' }],
        ['inner', { op: '<#>', opsSuffix: 'ip' }],
      ]),
    );
    expect(this.crdb.vectorExtension).toBeUndefined();
  }

  shouldRefuseL1Distance() {
    expect(this.crdb.vectorMetrics.has('l1')).toBe(false);

    const ctx = this.dialect.createContext();
    expect(() =>
      this.dialect.find(ctx, VectorItem, { $sort: { vec: { $vector: [1, 2, 3], $distance: 'l1' } } }),
    ).toThrow('cockroachdb does not support vector distance metric: l1');
  }

  shouldNotResolveAMetricViaThePrototypeChain() {
    const ctx = this.dialect.createContext();
    // 'toString' is not an own property of `vectorMetrics`, but `Object.prototype.toString` exists -
    // a naive `in`/bracket-access check would resolve it as if it were a supported metric.
    expect(() =>
      this.dialect.find(ctx, VectorItem, { $sort: { vec: { $vector: [1, 2, 3], $distance: 'toString' as any } } }),
    ).toThrow('cockroachdb does not support vector distance metric: toString');
  }

  shouldSupportTextFullTextSearchViaToTsvectorToTsqueryVerifiedToWorkOnCockroachDB() {
    const ctx = this.dialect.createContext();
    this.dialect.find(ctx, Item, {
      $select: { id: true },
      $where: { $text: { $fields: ['name', 'description'], $value: 'some text' } },
    });
    expect(ctx.sql).toBe(
      'SELECT "id" FROM "Item" WHERE to_tsvector("name" || \' \' || "description") @@ websearch_to_tsquery($1)',
    );
    expect(ctx.values).toEqual(['some text']);
  }
}

createSpec(new CockroachDialectSpec());
