import { describe, expect, it } from 'vitest';
import { Item, User, VectorItem } from '../test/index.js';
import { CockroachDialect } from './cockroachDialect.js';

describe('CockroachDialect', () => {
  const dialect = new CockroachDialect({});

  it('should use cockroachdb identifier', () => {
    expect(dialect.dialectName).toBe('cockroachdb');
  });

  it('upsert should not rely on xmax (unsupported by CockroachDB)', () => {
    const ctx = dialect.createContext();
    dialect.upsert(
      ctx,
      User,
      { email: true, companyId: true },
      {
        id: 1,
        name: 'Test',
        email: 'test@example.com',
        companyId: 1,
      },
    );
    expect(ctx.sql).toBe(
      'INSERT INTO "User" ("id", "name", "email", "companyId", "createdAt") VALUES ($2, $3, $4, $5, $6) ON CONFLICT ("email", "companyId") DO UPDATE SET "id" = EXCLUDED."id", "name" = EXCLUDED."name", "updatedAt" = $1 RETURNING "id" "id"',
    );
  });

  it('should use a real sequential IDENTITY column, not SERIAL (unique_rowid() overflows JS numbers)', () => {
    expect(dialect.serialPrimaryKey).toBe('BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
  });

  it('should sort by vector similarity using pgvector-style operators (native on CockroachDB)', () => {
    const ctx = dialect.createContext();
    dialect.find(ctx, VectorItem, {
      $select: { id: true },
      $sort: { vec: { $vector: [1, 2, 3] } },
      $limit: 10,
    });
    expect(ctx.sql).toBe('SELECT "id" FROM "VectorItem" ORDER BY "vec" <=> $1::vector LIMIT 10');
    expect(ctx.values).toEqual(['[1,2,3]']);
  });

  it('should sort by vector similarity with an explicit distance metric', () => {
    const ctx = dialect.createContext();
    dialect.find(ctx, VectorItem, {
      $select: { id: true },
      $sort: { vec: { $vector: [1, 2, 3], $distance: 'l2' } },
      $limit: 5,
    });
    expect(ctx.sql).toBe('SELECT "id" FROM "VectorItem" ORDER BY "vec" <-> $1::vector LIMIT 5');
  });

  it('should have pgvector-compatible index operator classes but no extension requirement (native type)', () => {
    expect(dialect.vectorOpsClass).toMatchObject({ cosine: 'vector_cosine_ops', l2: 'vector_l2_ops' });
    expect(dialect.vectorExtension).toBeUndefined();
  });

  it('should support $text full-text search via to_tsvector/to_tsquery (verified to work on CockroachDB)', () => {
    const ctx = dialect.createContext();
    dialect.find(ctx, Item, {
      $select: { id: true },
      $where: { $text: { $fields: ['name', 'description'], $value: 'some text' } },
    });
    expect(ctx.sql).toBe(
      'SELECT "id" FROM "Item" WHERE to_tsvector("name" || \' \' || "description") @@ to_tsquery($1)',
    );
    expect(ctx.values).toEqual(['some text']);
  });
});
