import { PgLikeQuerierIt } from '../querier/pgLikeQuerier-test.js';
import { createSpec } from '../test/index.js';
import { configurePgNumericTypeParsers } from '../test/pgTypeParsers.util.js';
import { CrdbQuerierPool } from './crdbQuerierPool.js';

configurePgNumericTypeParsers();

/**
 * CockroachDB has no `xmax`/`ctid` system columns, so `created` cannot be derived the way
 * Postgres does (see `CockroachDialect.upsert`); `shouldUpsertOne`'s default `created: undefined`
 * expectation (in `AbstractSqlQuerierIt`) already covers this, so no override is needed here.
 */
export class CockroachQuerierIt extends PgLikeQuerierIt {
  constructor() {
    super(
      new CrdbQuerierPool({
        host: '0.0.0.0',
        port: 26257,
        user: 'root',
        database: 'defaultdb',
      }),
      'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
    );
  }
}

createSpec(new CockroachQuerierIt());
