import type { UpdatePayload } from './entity.js';
import type { Query, QueryConflictPaths, QueryFilter, QueryOptions, QuerySearch } from './query.js';
import type { QueryAggMap, QueryAggregate, QueryGroupMap } from './queryAggregate.js';
import type { Type } from './utility.js';

/**
 * comparison options.
 */
export type QueryComparisonOptions = QueryOptions & {
  /**
   * Whether this fragment is rendered as an operand of an enclosing `AND`/`OR`/`NOT`. An operand
   * parenthesizes itself when it emits more than one term, so no fragment ever depends on the
   * engine's operator precedence. Only the `WHERE` clause as a whole is not an operand.
   */
  operand?: boolean;
};

/**
 * query filter options.
 */
export type QueryWhereOptions = QueryComparisonOptions & {
  /**
   * clause to be used in the filter.
   */
  clause?: 'WHERE' | 'AND' | false;
};

/**
 * Emits a statement, or a fragment of one, into the context it is handed. What a caller passes when
 * it knows *what* to build but not *where*: the statement is assembled into whichever context the
 * receiver opens, so the two ends cannot disagree about which one it went into.
 */
export type QueryBuildFn = (ctx: QueryContext) => void;

export interface QueryContext {
  append(sql: string): this;
  addValue(value: unknown): this;
  pushValue(...values: unknown[]): this;
  /**
   * A fresh derived-table/subquery alias, unique within this query: `nextAlias('_uql_elem')` returns
   * `'_uql_elem_1'`, then `'_uql_elem_2'`, etc. Needed wherever a hook (e.g. exploding a JSON array)
   * might recurse into itself at a deeper nesting level within the same query - a fixed, reused
   * alias would let the inner occurrence shadow the outer one it needs to correlate against.
   */
  nextAlias(prefix: string): string;
  /**
   * A context for a fragment of this same statement: it renders its own SQL in isolation while
   * sharing the bound values and the generated aliases, so both stay unique and correctly numbered
   * across the statement. See {@link AbstractSqlDialect.buildFragment}.
   */
  createFragment(): QueryContext;
  readonly sql: string;
  readonly values: unknown[];
}

/**
 * Capabilities of the database driver (transport layer).
 */
export interface DriverCapabilities {
  /**
   * Whether JSON bind parameters are cast via text first (`($n::text)::jsonb`).
   * Bun SQL PostgreSQL uses this for reliable jsonb merge/push; `pg` does not.
   */
  readonly explicitJsonCast: boolean;
  /**
   * Whether the driver natively supports JS arrays for the underlying database type.
   * `PgDialect` keeps this `true` for node-postgres; Bun SQL PostgreSQL uses `false` and
   * `toPgArray` string literals instead.
   */
  readonly nativeArrays: boolean;
  /** Whether the dialect natively supports the JSONB binary JSON type (Postgres/CockroachDB). */
  readonly supportsJsonb: boolean;
}

/**
 * How a dialect surfaces the IDs generated by an INSERT statement:
 * - `'returning'`: the statement itself returns one row per inserted record (`RETURNING`,
 *   or MongoDB's `insertedIds`), so IDs are exact for every row.
 * - `'firstId'`: the driver header only exposes the first generated ID (MySQL `insertId`);
 *   the remaining IDs are inferred by incrementing it.
 * - `'lastId'`: the driver header only exposes the last generated ID (SQLite `lastInsertRowid`);
 *   the remaining IDs are inferred backwards from it.
 */
export type InsertIdSource = 'returning' | 'firstId' | 'lastId';

/**
 * Features of the database engine (SQL syntax layer).
 */
export interface EngineFeatures {
  readonly ifNotExists: boolean;
  readonly indexIfNotExists: boolean;
  /**
   * Whether the engine has namespaces a table can sit behind. `false` leaves every table
   * unqualified, whatever `schema` an entity or pool named: SQLite attaches database files and
   * MongoDB takes its database from the connection, so neither has one to name.
   */
  readonly schemas: boolean;
  readonly dropTableCascade: boolean;
  readonly renameColumn: boolean;
  readonly foreignKeyAlter: boolean;
  /** Whether the dialect supports inline COMMENT on columns (MySQL/MariaDB). */
  readonly columnComment: boolean;
  /**
   * Whether every column of a vector index has to be `NOT NULL`, which MariaDB 12.3 enforces ("All
   * parts of a VECTOR index must be NOT NULL") and CockroachDB 26.3 does not - so being indexed, not
   * the entity, decides the column's nullability there.
   */
  readonly vectorIndexRequiresNotNull: boolean;
  /** Whether the dialect requires/allows (n) length constraints on vector types. */
  readonly vectorSupportsLength: boolean;
  /** Whether the dialect natively supports the TIMESTAMPTZ alias/type. */
  readonly supportsTimestamptz: boolean;
  /** Whether the dialect defaults to TEXT for strings when no length is specified (e.g. Postgres). */
  readonly defaultStringAsText: boolean;
}

export interface DialectFeatures extends EngineFeatures, DriverCapabilities {}

export interface QueryDialect {
  /**
   * The dialect features.
   */
  readonly features: DialectFeatures;

  /**
   * obtains the records matching the given search parameters.
   * @param ctx the query context
   * @param entity the target entity
   * @param q the criteria options
   * @param opts the query options
   * @param totalAlias when given, carry the unpaged match count on every row under this alias
   */
  find<E>(ctx: QueryContext, entity: Type<E>, q: Query<E>, opts?: QueryOptions, totalAlias?: string): void;

  /**
   * counts the number of records matching the given search parameters.
   * @param ctx the query context
   * @param entity the target entity
   * @param q the criteria options
   * @param opts the query options
   */
  count<E>(ctx: QueryContext, entity: Type<E>, q: QueryFilter<E>, opts?: QueryOptions): void;

  /**
   * insert records.
   * @param ctx the query context
   * @param entity the target entity
   * @param payload the payload
   * @param opts the query options
   */
  insert<E>(ctx: QueryContext, entity: Type<E>, payload: E | E[], opts?: QueryOptions): void;

  /**
   * update records.
   * @param ctx the query context
   * @param entity the target entity
   * @param q the criteria options
   * @param payload
   * @param opts the query options
   */
  update<E>(
    ctx: QueryContext,
    entity: Type<E>,
    q: QuerySearch<E>,
    payload: UpdatePayload<E>,
    opts?: QueryOptions,
  ): void;

  /**
   * upsert records.
   * @param ctx the query context
   * @param entity the target entity
   * @param conflictPaths the conflict paths
   * @param payload
   */
  upsert<E>(ctx: QueryContext, entity: Type<E>, conflictPaths: QueryConflictPaths<E>, payload: E | E[]): void;

  /**
   * delete records.
   * @param ctx the query context
   * @param entity the target entity
   * @param q the criteria options
   * @param opts the query options
   */
  delete<E>(ctx: QueryContext, entity: Type<E>, q: QuerySearch<E>, opts?: QueryOptions): void;

  /**
   * escape an identifier.
   * @param val the value to be escaped
   * @param forbidQualified don't escape dots
   * @param addDot use a dot as suffix
   */
  escapeId(val: string | undefined, forbidQualified?: boolean, addDot?: boolean): string;

  /**
   * escape a value.
   * @param val the value to escape
   */
  escape(val: unknown): string;

  /**
   * add a value to the query.
   * @param values the values array
   * @param value the value to add
   */
  addValue(values: unknown[], value: unknown): string;

  /**
   * normalizes a value according to the dialect.
   * @param value the value to normalize
   */
  normalizeValue(value: unknown): unknown;

  /**
   * create a new query context.
   */
  createContext(): QueryContext;
}

/**
 * Supported SQL dialect identifiers.
 */
export type SqlDialectName = 'postgres' | 'cockroachdb' | 'mysql' | 'mariadb' | 'sqlite';

/**
 * Minimal dialect interface exposing escapeIdChar for SQL operations
 */
export interface SqlQueryDialect extends QueryDialect {
  /**
   * The SQL dialect name (postgres, mysql, mariadb, sqlite).
   */
  readonly dialectName: SqlDialectName;

  /**
   * the escape character for identifiers.
   */
  readonly escapeIdChar: '"' | '`';

  /**
   * Build an aggregate query.
   */
  aggregate<E, G extends QueryGroupMap<E>, A extends QueryAggMap<E>>(
    ctx: QueryContext,
    entity: Type<E>,
    q: QueryAggregate<E, G, A>,
    opts?: QueryOptions,
  ): void;

  /**
   * Get the placeholder for a parameter at the given index (1-based).
   * Default: '?' for MySQL/MariaDB/SQLite, '$n' for PostgreSQL.
   */
  placeholder(index: number): string;
}

/**
 * An index capability that some engines have and others reject outright. Verified live: expression
 * indexes exist everywhere but MariaDB 12.3 (which needs a generated column); prefix lengths are
 * MySQL-family only and *required* there to index `TEXT`; `NULLS FIRST/LAST` and operator classes are
 * Postgres-only (CockroachDB 26.2 answers "unimplemented"); `INCLUDE` is Postgres-wire only; the
 * MySQL family is alone in having no partial indexes. The two JSON ones split the other way: the
 * engines that index a path inside a document are the ones whose planner matches the query's own
 * extraction back to it (Postgres, CockroachDB, SQLite - MySQL matches neither
 * `CAST(col->>'$.x' AS CHAR(n))` nor `JSON_VALUE(... RETURNING ...)`, verified on 26.7, and needs a
 * generated column instead), while MySQL alone has the multi-valued index a JSON array needs.
 *
 * Introspectors reuse the vocabulary for what they can read *back*, which is what diffing may
 * compare. The two sets are deliberately not the same object and must not be unified: Postgres can
 * emit an expression index and read one back, but MySQL emits one it cannot describe afterwards.
 */
export const INDEX_FEATURE_LABELS = {
  expression: 'expression indexes',
  partial: 'partial indexes',
  prefixLength: 'index prefix lengths',
  nullsOrder: 'NULLS FIRST/LAST in an index',
  opsClass: 'index operator classes',
  include: 'covering indexes (INCLUDE)',
  jsonPath: 'indexes over a path inside a JSON column',
  jsonArray: 'multi-valued indexes over a JSON array',
} as const;

/** Derived from the labels, so a feature cannot be added without the words an error reports it in. */
export type IndexFeature = keyof typeof INDEX_FEATURE_LABELS;
