import { PgQuerierPool } from '../postgres/pgQuerierPool.js';
import { PostgresDialect } from '../postgres/postgresDialect.js';
import { postgresConnection } from '../test/index.js';
import { describeMigratorSync } from './migrator-sync-test.js';

describeMigratorSync({
  name: 'PostgreSQL',
  createPool: () => new PgQuerierPool(postgresConnection()),
  dialect: new PostgresDialect(),
  serialIdColumn: '"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
  textType: 'TEXT',
  doubleType: 'DOUBLE PRECISION',
  keyColumnType: 'BIGINT',
});
