import { afterAll, afterEach, beforeAll, describe, expect, it, vi } from 'vitest';
import { Entity, Field, Id } from '../entity/index.js';
import { MariadbQuerierPool } from '../maria/mariadbQuerierPool.js';
import { MySql2QuerierPool } from '../mysql/mysql2QuerierPool.js';
import { PgQuerierPool } from '../postgres/pgQuerierPool.js';
import { Sqlite3QuerierPool } from '../sqlite/sqliteQuerierPool.js';
import type { SchemaIntrospector, SqlQuerierPool } from '../type/index.js';
import { MariadbSchemaIntrospector, MysqlSchemaIntrospector } from './introspection/mysqlIntrospector.js';
import { PostgresSchemaIntrospector } from './introspection/postgresIntrospector.js';
import { SqliteSchemaIntrospector } from './introspection/sqliteIntrospector.js';
import { Migrator } from './migrator.js';

interface DatabaseConfig {
  name: string;
  /** A factory, not a pool: nothing is opened for a backend whose suite never runs. */
  createPool: () => SqlQuerierPool;
  createIntrospector: (pool: SqlQuerierPool) => SchemaIntrospector;
  /** A hand-written key column, for seeding the table a sync is then asked to reconcile. */
  serialIdColumn: string;
  /** The plain integer a caller-supplied key column takes, which is not the auto-increment type. */
  keyColumnType: string;
  /** Set where the engine cannot alter a key, naming the refusal its DDL raises. */
  unsafeKeyError?: string;
  /** Set where the engine cannot `ALTER` a foreign key in, so a sync reports no difference at all. */
  noForeignKeyAlter?: boolean;
  /** How this engine spelled a key before it was derived from the declared type. MySQL family only. */
  legacyUnsignedIdColumn?: string;
  textType: string;
  doubleType: string;
  unsafeAlterError?: string;
}

const databases: DatabaseConfig[] = [
  {
    name: 'PostgreSQL',
    createPool: () =>
      new PgQuerierPool({ host: '0.0.0.0', port: 5442, user: 'test', password: 'test', database: 'test' }),
    createIntrospector: (pool) => new PostgresSchemaIntrospector(pool),
    serialIdColumn: '"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
    textType: 'TEXT',
    doubleType: 'DOUBLE PRECISION',
    keyColumnType: 'BIGINT',
  },
  {
    name: 'MySQL',
    legacyUnsignedIdColumn: '`id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY',
    createPool: () =>
      new MySql2QuerierPool({ host: '0.0.0.0', port: 3316, user: 'test', password: 'test', database: 'test' }),
    createIntrospector: (pool) => new MysqlSchemaIntrospector(pool),
    serialIdColumn: '`id` BIGINT AUTO_INCREMENT PRIMARY KEY',
    textType: 'VARCHAR(255)',
    doubleType: 'DOUBLE',
    keyColumnType: 'BIGINT',
  },
  {
    name: 'MariaDB',
    legacyUnsignedIdColumn: '`id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY',
    createPool: () =>
      new MariadbQuerierPool({
        host: '0.0.0.0',
        port: 3326,
        user: 'test',
        password: 'test',
        database: 'test',
        connectionLimit: 5,
      }),
    createIntrospector: (pool) => new MariadbSchemaIntrospector(pool),
    serialIdColumn: '`id` BIGINT AUTO_INCREMENT PRIMARY KEY',
    textType: 'VARCHAR(255)',
    doubleType: 'DOUBLE',
    keyColumnType: 'BIGINT',
  },
  {
    name: 'SQLite',
    createPool: () => new Sqlite3QuerierPool(':memory:'),
    createIntrospector: (pool) => new SqliteSchemaIntrospector(pool),
    serialIdColumn: '`id` INTEGER PRIMARY KEY AUTOINCREMENT',
    textType: 'TEXT',
    doubleType: 'DOUBLE',
    keyColumnType: 'INTEGER',
    unsafeAlterError: 'Cannot alter column',
    unsafeKeyError: 'Cannot change the primary key',
    noForeignKeyAlter: true,
  },
];

for (const db of databases) {
  describe(`Migrator sync Integration (${db.name})`, () => {
    let pool: SqlQuerierPool;
    let introspector: SchemaIntrospector;
    const claimed = new Set<string>();

    /**
     * Every statement goes through the pool, which acquires and releases per call. Pinning one querier
     * for the whole suite instead made a single dropped connection fail all of it.
     */
    const escapeId = (id: string) => pool.dialect.escapeId(id);
    const dropTable = (tableName: string) => pool.run(`DROP TABLE IF EXISTS ${escapeId(tableName)}`);

    /** Names the table this test owns, guarantees it does not exist yet, and registers its teardown. */
    const givenNoTable = async (tableName: string) => {
      claimed.add(tableName);
      await dropTable(tableName);
    };

    /** {@link givenNoTable} plus the pre-existing table a sync is expected to reconcile. */
    const givenTable = async (tableName: string, columns: string) => {
      await givenNoTable(tableName);
      await pool.run(`CREATE TABLE ${escapeId(tableName)} (${columns})`);
    };

    beforeAll(() => {
      pool = db.createPool();
      introspector = db.createIntrospector(pool);
    });

    afterAll(() => pool.end());

    // Teardown here rather than trailing each test: a failed expectation used to leak its table into
    // the shared database, where the next run's introspection would find it.
    afterEach(async () => {
      for (const tableName of claimed) {
        await dropTable(tableName);
      }
      claimed.clear();
    });

    it('should detect and sync a new property added to an existing entity', async () => {
      @Entity()
      class AutoSyncUserTest1 {
        @Id({ type: Number }) id?: number;
        @Field({ type: String }) name?: string;
        @Field({ type: String }) email?: string;
      }

      const tableName = 'AutoSyncUserTest1';
      await givenTable(tableName, `${db.serialIdColumn}, ${escapeId('name')} ${db.textType}`);

      const before = await introspector.introspect();
      expect(before.getTable(tableName)).toBeDefined();
      expect(Array.from(before.getTable(tableName)!.columns.keys()).sort()).toEqual(['id', 'name']);

      await new Migrator(pool, { entities: [AutoSyncUserTest1] }).sync({ logging: true });

      const after = await introspector.introspect();
      expect(after.getTable(tableName)).toBeDefined();
      expect(Array.from(after.getTable(tableName)!.columns.keys()).sort()).toEqual(['email', 'id', 'name']);
    });

    /**
     * The regression test the differ merge most needs: a schema created from its own entities has
     * nothing left to reconcile. Anything reported here is a phantom - a column the generator spells
     * differently from how the engine stores it, or an index it fails to recognise as already there -
     * and it would re-run on every single sync.
     */
    it('should have nothing to do when the schema was created from the same entities', async () => {
      @Entity()
      class AutoSyncSettledTest {
        @Id({ type: Number }) id?: number;
        @Field({ type: String }) name?: string;
        @Field({ type: String, index: true }) email?: string;
        @Field({ type: Number }) cost?: number;
        @Field({ type: Boolean }) active?: boolean;
      }

      await givenNoTable('AutoSyncSettledTest');
      const migrator = new Migrator(pool, { entities: [AutoSyncSettledTest] });
      await migrator.sync();

      expect(await migrator.planSync({ safe: false, drop: true })).toEqual([]);
    });

    /**
     * The upgrade the composite-key work exists for: a table keyed by one column, an entity that now
     * declares two. The key itself has to change, not just the column - and it has to come back in
     * the order declared, since `(a, b)` is a different key from `(b, a)`.
     */
    it.skipIf(!!db.unsafeKeyError)('should widen a single-column key to a composite one', async () => {
      @Entity()
      class AutoSyncKeyTest {
        @Id({ type: Number }) userId?: number;
        @Id({ type: Number }) groupId?: number;
        @Field({ type: String }) note?: string;
      }

      const tableName = 'AutoSyncKeyTest';
      await givenTable(
        tableName,
        `${escapeId('userId')} ${db.keyColumnType} NOT NULL, ${escapeId('note')} ${db.textType}, PRIMARY KEY (${escapeId('userId')})`,
      );

      const before = await introspector.getTableSchema(tableName);
      expect(before?.primaryKey).toEqual(['userId']);

      await new Migrator(pool, { entities: [AutoSyncKeyTest] }).sync({ safe: false });

      const after = await introspector.getTableSchema(tableName);
      expect(after?.primaryKey).toEqual(['userId', 'groupId']);
    });

    /** SQLite can only rebuild the table, so it refuses by name rather than emitting DDL. */
    it.skipIf(!db.unsafeKeyError)('should refuse to change a key it cannot alter', async () => {
      @Entity()
      class AutoSyncKeyRefusedTest {
        @Id({ type: Number }) userId?: number;
        @Id({ type: Number }) groupId?: number;
      }

      const tableName = 'AutoSyncKeyRefusedTest';
      await givenTable(
        tableName,
        `${escapeId('userId')} ${db.keyColumnType} NOT NULL, PRIMARY KEY (${escapeId('userId')})`,
      );

      await expect(new Migrator(pool, { entities: [AutoSyncKeyRefusedTest] }).sync({ safe: false })).rejects.toThrow(
        db.unsafeKeyError,
      );
    });

    it('should create an index the entity declares on a table that already exists', async () => {
      @Entity()
      class AutoSyncIndexTest {
        @Id({ type: Number }) id?: number;
        @Field({ type: String, index: true }) email?: string;
      }

      const tableName = 'AutoSyncIndexTest';
      await givenTable(tableName, `${db.serialIdColumn}, ${escapeId('email')} ${db.textType}`);

      const before = await introspector.introspect();
      expect(before.getTable(tableName)!.indexes).toEqual([]);

      await new Migrator(pool, { entities: [AutoSyncIndexTest] }).sync({ logging: true });

      const after = await introspector.introspect();
      expect(after.getTable(tableName)!.indexes.map((index) => index.name)).toEqual(['AutoSyncIndexTest__email_idx']);
    });

    it('should add multiple new properties to an existing entity', async () => {
      @Entity()
      class AutoSyncProductTest1 {
        @Id({ type: Number }) id?: number;
        @Field({ type: String }) name?: string;
        @Field({ type: Number }) price?: number;
        @Field({ type: String }) description?: string;
        @Field({ type: Boolean }) active?: boolean;
      }

      const tableName = 'AutoSyncProductTest1';
      await givenTable(tableName, `${db.serialIdColumn}, ${escapeId('name')} ${db.textType}`);

      await new Migrator(pool, { entities: [AutoSyncProductTest1] }).sync({ logging: true });

      const ast = await introspector.introspect();
      const table = ast.getTable(tableName);
      expect(table).toBeDefined();
      expect(Array.from(table!.columns.keys()).sort()).toEqual(['active', 'description', 'id', 'name', 'price']);
    });

    it('should not modify table when schema is already in sync', async () => {
      @Entity()
      class AutoSyncCategoryTest1 {
        @Id({ type: Number }) id?: number;
        @Field({ type: String }) name?: string;
      }

      const tableName = 'AutoSyncCategoryTest1';
      await givenTable(tableName, `${db.serialIdColumn}, ${escapeId('name')} ${db.textType}`);

      const before = await introspector.introspect();
      expect(before.getTable(tableName)).toBeDefined();

      await new Migrator(pool, { entities: [AutoSyncCategoryTest1] }).sync({ logging: true });

      const after = await introspector.introspect();
      expect(after.getTable(tableName)).toBeDefined();
      expect(after.getTable(tableName)!.columns.size).toBe(before.getTable(tableName)!.columns.size);
    });

    it('should create a new table if it does not exist', async () => {
      @Entity()
      class AutoSyncNewTableTest1 {
        @Id({ type: Number }) id?: number;
        @Field({ type: String }) title?: string;
        @Field({ type: String }) content?: string;
      }

      const tableName = 'AutoSyncNewTableTest1';
      await givenNoTable(tableName);

      expect(await introspector.tableExists(tableName)).toBe(false);

      await new Migrator(pool, { entities: [AutoSyncNewTableTest1] }).sync({ logging: true });

      expect(await introspector.tableExists(tableName)).toBe(true);

      const ast = await introspector.introspect();
      const table = ast.getTable(tableName);
      expect(table).toBeDefined();
      expect(table!.columns.size).toBe(3);
    });

    it('should handle entity with custom table name', async () => {
      @Entity({ name: 'custom_user_table' })
      class AutoSyncCustomNameTest1 {
        @Id({ type: Number }) id?: number;
        @Field({ type: String }) username?: string;
        @Field({ type: String }) email?: string;
      }

      const tableName = 'custom_user_table';
      await givenTable(tableName, `${db.serialIdColumn}, ${escapeId('username')} ${db.textType}`);

      await new Migrator(pool, { entities: [AutoSyncCustomNameTest1] }).sync({ logging: true });

      const ast = await introspector.introspect();
      const table = ast.getTable(tableName);
      expect(table).toBeDefined();
      expect(Array.from(table!.columns.keys()).sort()).toEqual(['email', 'id', 'username']);
    });

    it('should handle field with custom column name', async () => {
      @Entity()
      class AutoSyncCustomColumnTest1 {
        @Id({ type: Number }) id?: number;
        @Field({ type: String, name: 'user_email' }) email?: string;
      }

      const tableName = 'AutoSyncCustomColumnTest1';
      await givenTable(tableName, db.serialIdColumn);

      await new Migrator(pool, { entities: [AutoSyncCustomColumnTest1] }).sync({ logging: true });

      const ast = await introspector.introspect();
      const table = ast.getTable(tableName);
      expect(table).toBeDefined();
      expect(Array.from(table!.columns.keys()).sort()).toEqual(['id', 'user_email']);
    });

    it('should handle field rename safely (add new, keep old)', async () => {
      @Entity()
      class AutoSyncRenameTest {
        @Id({ type: Number }) id?: number;
        @Field({ type: String }) newName?: string;
      }

      const tableName = 'AutoSyncRenameTest';
      await givenTable(tableName, `${db.serialIdColumn}, ${escapeId('oldName')} ${db.textType}`);

      await new Migrator(pool, { entities: [AutoSyncRenameTest] }).sync({ logging: true });

      const ast = await introspector.introspect();
      const table = ast.getTable(tableName);
      expect(table).toBeDefined();
      expect(Array.from(table!.columns.keys()).sort()).toEqual(['id', 'newName', 'oldName']);
    });

    it('should drop old column and add new one when renaming with safe: false', async () => {
      @Entity()
      class AutoSyncUnsafeRenameTest {
        @Id({ type: Number }) id?: number;
        @Field({ type: String }) newName?: string;
      }

      const tableName = 'AutoSyncUnsafeRenameTest';
      await givenTable(tableName, `${db.serialIdColumn}, ${escapeId('oldName')} ${db.textType}`);

      await new Migrator(pool, { entities: [AutoSyncUnsafeRenameTest] }).sync({
        logging: true,
        safe: false,
        drop: true,
      });

      const ast = await introspector.introspect();
      const table = ast.getTable(tableName);
      expect(table).toBeDefined();
      expect(Array.from(table!.columns.keys()).sort()).toEqual(['id', 'newName']);
    });

    it('should NOT alter existing DOUBLE column to BIGINT for number field (Safe Mode)', async () => {
      @Entity()
      class AutoSyncFloatTest {
        @Id({ type: Number }) id?: number;
        @Field({ type: Number }) cost?: number;
      }

      const tableName = 'AutoSyncFloatTest';
      await givenTable(tableName, `${db.serialIdColumn}, ${escapeId('cost')} ${db.doubleType}`);

      await new Migrator(pool, { entities: [AutoSyncFloatTest] }).sync({ logging: true });

      const ast = await introspector.introspect();
      const table = ast.getTable(tableName);
      expect(table).toBeDefined();

      const costCol = table!.columns.get('cost');
      expect(costCol).toBeDefined();

      const type = costCol!.type.category.toLowerCase();
      const isFloatCompatible =
        type.includes('double') || type.includes('float') || type.includes('real') || type.includes('decimal');

      expect(isFloatCompatible).toBe(true);
      expect(type).not.toContain('bigint');
      expect(type).not.toContain('int8'); // postgres bigint alias
    });

    it('should block drops even if safe: false (when drop: false)', async () => {
      @Entity()
      class AutoSyncNoDropTest {
        @Id({ type: Number }) id?: number;
        @Field({ type: String }) name?: string;
      }

      const tableName = 'AutoSyncNoDropTest';
      await givenTable(
        tableName,
        `${db.serialIdColumn}, ${escapeId('name')} ${db.textType}, ${escapeId('extraColumn')} ${db.textType}`,
      );

      await new Migrator(pool, { entities: [AutoSyncNoDropTest] }).sync({ logging: true, safe: false });

      const ast = await introspector.introspect();
      const table = ast.getTable(tableName);
      expect(table).toBeDefined();
      expect(Array.from(table!.columns.keys()).sort()).toEqual(['extraColumn', 'id', 'name']);
    });

    /**
     * A key a foreign key can point at, spelled the same as the column that will reference it. Not
     * {@link DatabaseConfig.serialIdColumn}, which is `BIGINT UNSIGNED` on the MySQL family: an
     * engine refuses a constraint whose two sides differ in signedness.
     *
     * The child table is claimed first so the shared teardown drops it first - a parent cannot go
     * while a constraint still points at it, and a failed drop leaks the table into the next test.
     */
    const givenRelatedTables = async (parent: string, child: string) => {
      const idColumn = `${escapeId('id')} ${db.keyColumnType} PRIMARY KEY`;
      await givenNoTable(child);
      await givenTable(parent, idColumn);
      await pool.run(`CREATE TABLE ${escapeId(child)} (${idColumn}, ${escapeId('companyId')} ${db.keyColumnType})`);
    };

    /**
     * The whole point of the foreign-key diff: the constraint has to reach the database and the engine
     * has to accept the DDL, which no string assertion can prove.
     */
    it.skipIf(db.noForeignKeyAlter)('should add a foreign key the table has not got', async () => {
      @Entity()
      class FkSyncCompany {
        @Id({ type: Number }) id?: number;
      }
      @Entity()
      class FkSyncEmployee {
        @Id({ type: Number }) id?: number;
        @Field({ references: () => FkSyncCompany, onDelete: 'CASCADE' }) companyId?: number;
      }

      await givenRelatedTables('FkSyncCompany', 'FkSyncEmployee');
      const before = await introspector.introspect();
      expect(before.getTable('FkSyncEmployee')!.outgoingRelations).toHaveLength(0);

      await new Migrator(pool, { entities: [FkSyncCompany, FkSyncEmployee] }).sync({ logging: true });

      const relations = (await introspector.introspect()).getTable('FkSyncEmployee')!.outgoingRelations;
      expect(relations).toHaveLength(1);
      expect(relations[0].to.table.name).toBe('FkSyncCompany');
      expect(relations[0].onDelete).toBe('CASCADE');
    });

    /**
     * The case the feature exists for, and the one no unit test can prove: changing `onDelete` on a
     * relation whose constraint is already there. It is a drop and an add, so it needs `safe: false`.
     */
    it.skipIf(db.noForeignKeyAlter)('should alter a foreign key whose referential action changed', async () => {
      @Entity()
      class FkAlterCompany {
        @Id({ type: Number }) id?: number;
      }
      @Entity()
      class FkAlterEmployee {
        @Id({ type: Number }) id?: number;
        @Field({ references: () => FkAlterCompany, onDelete: 'SET NULL' }) companyId?: number;
      }

      await givenRelatedTables('FkAlterCompany', 'FkAlterEmployee');
      await pool.run(
        `ALTER TABLE ${escapeId('FkAlterEmployee')} ADD CONSTRAINT ${escapeId('fk_employee_company')} ` +
          `FOREIGN KEY (${escapeId('companyId')}) REFERENCES ${escapeId('FkAlterCompany')} (${escapeId('id')}) ` +
          `ON DELETE CASCADE`,
      );
      const before = await introspector.introspect();
      expect(before.getTable('FkAlterEmployee')!.outgoingRelations[0].onDelete).toBe('CASCADE');

      await new Migrator(pool, { entities: [FkAlterCompany, FkAlterEmployee] }).sync({ logging: true, safe: false });

      const relations = (await introspector.introspect()).getTable('FkAlterEmployee')!.outgoingRelations;
      expect(relations).toHaveLength(1);
      expect(relations[0].onDelete).toBe('SET NULL');
    });

    /**
     * A schema built from its own entities has no foreign key left to reconcile. A phantom here would
     * drop and re-add every constraint on every sync, forever.
     */
    it('should report no foreign key change on a schema it just created', async () => {
      @Entity()
      class FkStableCompany {
        @Id({ type: Number }) id?: number;
      }
      @Entity()
      class FkStableEmployee {
        @Id({ type: Number }) id?: number;
        @Field({ references: () => FkStableCompany, onDelete: 'CASCADE' }) companyId?: number;
      }

      await givenNoTable('FkStableEmployee');
      await givenNoTable('FkStableCompany');
      const migrator = new Migrator(pool, { entities: [FkStableCompany, FkStableEmployee] });
      await migrator.sync({ logging: true });

      expect(await migrator.planSync()).toEqual([]);
    });

    /**
     * The upgrade path for a database created while the serial was a fixed `BIGINT UNSIGNED`: the key
     * has to come back to the type it declares, or every foreign key pointing at it stays refused.
     * Signedness is the one part of a generated key's type the diff compares, for exactly this.
     */
    it.runIf(db.legacyUnsignedIdColumn)('should bring a legacy unsigned key back to its declared type', async () => {
      @Entity()
      class FkLegacyCompany {
        @Id({ type: Number }) id?: number;
      }
      @Entity()
      class FkLegacyEmployee {
        @Id({ type: Number }) id?: number;
        @Field({ references: () => FkLegacyCompany, onDelete: 'CASCADE' }) companyId?: number;
      }

      await givenNoTable('FkLegacyEmployee');
      await givenTable('FkLegacyCompany', db.legacyUnsignedIdColumn!);
      await pool.run(
        `CREATE TABLE ${escapeId('FkLegacyEmployee')} (${db.legacyUnsignedIdColumn}, ${escapeId('companyId')} ${db.keyColumnType})`,
      );

      const migrator = new Migrator(pool, { entities: [FkLegacyCompany, FkLegacyEmployee] });
      await migrator.sync({ logging: true, safe: false });

      const after = await introspector.introspect();
      expect(after.getTable('FkLegacyCompany')!.columns.get('id')!.type.unsigned).toBeFalsy();
      // The point of the alter: the constraint can finally be created.
      expect(after.getTable('FkLegacyEmployee')!.outgoingRelations).toHaveLength(1);
      expect(await migrator.planSync({ safe: false })).toEqual([]);
    });

    it('should log skipped migrations when safe mode blocks changes', async () => {
      @Entity()
      class AutoSyncLogTest {
        @Id({ type: Number }) id?: number;
        @Field({ type: String }) name?: string;
      }

      const tableName = 'AutoSyncLogTest';
      await givenTable(
        tableName,
        `${db.serialIdColumn}, ${escapeId('name')} ${db.textType}, ${escapeId('extraColumn')} ${db.textType}`,
      );

      const consoleSpy = vi.spyOn(console, 'info').mockImplementation(() => {});
      try {
        await new Migrator(pool, { entities: [AutoSyncLogTest], logger: true }).sync({ logging: true });

        expect(consoleSpy).toHaveBeenCalledWith(expect.stringContaining('skipped migration:'));
        expect(consoleSpy).toHaveBeenCalledWith(expect.stringContaining('Skipped dropping 1 columns'));
      } finally {
        consoleSpy.mockRestore();
      }
    });

    it.skipIf(!!db.unsafeAlterError)('should alter column type when safe: false', async () => {
      @Entity()
      class AutoSyncUnsafeAlterTest {
        @Id({ type: Number }) id?: number;
        @Field({ type: Number }) cost?: number; // Defaults to bigint
      }

      const tableName = 'AutoSyncUnsafeAlterTest';
      await givenTable(tableName, `${db.serialIdColumn}, ${escapeId('cost')} ${db.doubleType}`);

      await new Migrator(pool, { entities: [AutoSyncUnsafeAlterTest] }).sync({ logging: true, safe: false });

      const ast = await introspector.introspect();
      const table = ast.getTable(tableName);
      expect(table).toBeDefined();

      const costCol = table!.columns.get('cost');
      expect(costCol).toBeDefined();

      const type = costCol!.type.category.toLowerCase();
      expect(type).toContain('int');
      expect(type).not.toContain('double');
    });

    it.runIf(!!db.unsafeAlterError)('should throw error when altering column type (system limitation)', async () => {
      @Entity()
      class AutoSyncUnsafeAlterErrorTest {
        @Id({ type: Number }) id?: number;
        @Field({ type: Number }) cost?: number;
      }

      const tableName = 'AutoSyncUnsafeAlterErrorTest';
      await givenTable(tableName, `${db.serialIdColumn}, ${escapeId('cost')} ${db.doubleType}`);

      const migrator = new Migrator(pool, { entities: [AutoSyncUnsafeAlterErrorTest] });

      await expect(migrator.sync({ logging: true, safe: false })).rejects.toThrow(db.unsafeAlterError);
    });
  });
}
