import { afterAll, afterEach, beforeAll, describe, expect, it, vi } from 'vitest';
import { Entity, Field, Id } from '../entity/index.js';
import { MariadbQuerierPool } from '../maria/mariadbQuerierPool.js';
import { MySql2QuerierPool } from '../mysql/mysql2QuerierPool.js';
import { PgQuerierPool } from '../postgres/pgQuerierPool.js';
import { Sqlite3QuerierPool } from '../sqlite/sqliteQuerierPool.js';
import type { SchemaIntrospector, SqlQuerierPool } from '../type/index.js';
import { MariadbSchemaIntrospector, MysqlSchemaIntrospector } from './introspection/mysqlIntrospector.js';
import { PostgresSchemaIntrospector } from './introspection/postgresIntrospector.js';
import { SqliteSchemaIntrospector } from './introspection/sqliteIntrospector.js';
import { Migrator } from './migrator.js';

interface DatabaseConfig {
  name: string;
  /** A factory, not a pool: nothing is opened for a backend whose suite never runs. */
  createPool: () => SqlQuerierPool;
  createIntrospector: (pool: SqlQuerierPool) => SchemaIntrospector;
  /** A hand-written key column, for seeding the table `autoSync` is then asked to reconcile. */
  serialIdColumn: string;
  /** The plain integer a caller-supplied key column takes, which is not the auto-increment type. */
  keyColumnType: string;
  /** Set where the engine cannot alter a key, naming the refusal its DDL raises. */
  unsafeKeyError?: string;
  textType: string;
  doubleType: string;
  unsafeAlterError?: string;
}

const databases: DatabaseConfig[] = [
  {
    name: 'PostgreSQL',
    createPool: () =>
      new PgQuerierPool({ host: '0.0.0.0', port: 5442, user: 'test', password: 'test', database: 'test' }),
    createIntrospector: (pool) => new PostgresSchemaIntrospector(pool),
    serialIdColumn: '"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
    textType: 'TEXT',
    doubleType: 'DOUBLE PRECISION',
    keyColumnType: 'BIGINT',
  },
  {
    name: 'MySQL',
    createPool: () =>
      new MySql2QuerierPool({ host: '0.0.0.0', port: 3316, user: 'test', password: 'test', database: 'test' }),
    createIntrospector: (pool) => new MysqlSchemaIntrospector(pool),
    serialIdColumn: '`id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY',
    textType: 'VARCHAR(255)',
    doubleType: 'DOUBLE',
    keyColumnType: 'BIGINT',
  },
  {
    name: 'MariaDB',
    createPool: () =>
      new MariadbQuerierPool({
        host: '0.0.0.0',
        port: 3326,
        user: 'test',
        password: 'test',
        database: 'test',
        connectionLimit: 5,
      }),
    createIntrospector: (pool) => new MariadbSchemaIntrospector(pool),
    serialIdColumn: '`id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY',
    textType: 'VARCHAR(255)',
    doubleType: 'DOUBLE',
    keyColumnType: 'BIGINT',
  },
  {
    name: 'SQLite',
    createPool: () => new Sqlite3QuerierPool(':memory:'),
    createIntrospector: (pool) => new SqliteSchemaIntrospector(pool),
    serialIdColumn: '`id` INTEGER PRIMARY KEY AUTOINCREMENT',
    textType: 'TEXT',
    doubleType: 'DOUBLE',
    keyColumnType: 'INTEGER',
    unsafeAlterError: 'Cannot alter column',
    unsafeKeyError: 'Cannot change the primary key',
  },
];

for (const db of databases) {
  describe(`Migrator autoSync Integration (${db.name})`, () => {
    let pool: SqlQuerierPool;
    let introspector: SchemaIntrospector;
    const claimed = new Set<string>();

    /**
     * Every statement goes through the pool, which acquires and releases per call. Pinning one querier
     * for the whole suite instead made a single dropped connection fail all of it.
     */
    const escapeId = (id: string) => pool.dialect.escapeId(id);
    const dropTable = (tableName: string) => pool.run(`DROP TABLE IF EXISTS ${escapeId(tableName)}`);

    /** Names the table this test owns, guarantees it does not exist yet, and registers its teardown. */
    const givenNoTable = async (tableName: string) => {
      claimed.add(tableName);
      await dropTable(tableName);
    };

    /** {@link givenNoTable} plus the pre-existing table `autoSync` is expected to reconcile. */
    const givenTable = async (tableName: string, columns: string) => {
      await givenNoTable(tableName);
      await pool.run(`CREATE TABLE ${escapeId(tableName)} (${columns})`);
    };

    beforeAll(() => {
      pool = db.createPool();
      introspector = db.createIntrospector(pool);
    });

    afterAll(() => pool.end());

    // Teardown here rather than trailing each test: a failed expectation used to leak its table into
    // the shared database, where the next run's introspection would find it.
    afterEach(async () => {
      for (const tableName of claimed) {
        await dropTable(tableName);
      }
      claimed.clear();
    });

    it('should detect and sync a new property added to an existing entity', async () => {
      @Entity()
      class AutoSyncUserTest1 {
        @Id({ type: Number }) id?: number;
        @Field({ type: String }) name?: string;
        @Field({ type: String }) email?: string;
      }

      const tableName = 'AutoSyncUserTest1';
      await givenTable(tableName, `${db.serialIdColumn}, ${escapeId('name')} ${db.textType}`);

      const before = await introspector.introspect();
      expect(before.getTable(tableName)).toBeDefined();
      expect(Array.from(before.getTable(tableName)!.columns.keys()).sort()).toEqual(['id', 'name']);

      await new Migrator(pool, { entities: [AutoSyncUserTest1] }).autoSync({ logging: true });

      const after = await introspector.introspect();
      expect(after.getTable(tableName)).toBeDefined();
      expect(Array.from(after.getTable(tableName)!.columns.keys()).sort()).toEqual(['email', 'id', 'name']);
    });

    /**
     * The regression test the differ merge most needs: a schema created from its own entities has
     * nothing left to reconcile. Anything reported here is a phantom - a column the generator spells
     * differently from how the engine stores it, or an index it fails to recognise as already there -
     * and it would re-run on every single sync.
     */
    it('should have nothing to do when the schema was created from the same entities', async () => {
      @Entity()
      class AutoSyncSettledTest {
        @Id({ type: Number }) id?: number;
        @Field({ type: String }) name?: string;
        @Field({ type: String, index: true }) email?: string;
        @Field({ type: Number }) cost?: number;
        @Field({ type: Boolean }) active?: boolean;
      }

      await givenNoTable('AutoSyncSettledTest');
      const migrator = new Migrator(pool, { entities: [AutoSyncSettledTest] });
      await migrator.autoSync();

      expect(await migrator.planSync({ safe: false, drop: true })).toEqual([]);
    });

    /**
     * The upgrade the composite-key work exists for: a table keyed by one column, an entity that now
     * declares two. The key itself has to change, not just the column - and it has to come back in
     * the order declared, since `(a, b)` is a different key from `(b, a)`.
     */
    it.skipIf(!!db.unsafeKeyError)('should widen a single-column key to a composite one', async () => {
      @Entity()
      class AutoSyncKeyTest {
        @Id({ type: Number }) userId?: number;
        @Id({ type: Number }) groupId?: number;
        @Field({ type: String }) note?: string;
      }

      const tableName = 'AutoSyncKeyTest';
      await givenTable(
        tableName,
        `${escapeId('userId')} ${db.keyColumnType} NOT NULL, ${escapeId('note')} ${db.textType}, PRIMARY KEY (${escapeId('userId')})`,
      );

      const before = await introspector.getTableSchema(tableName);
      expect(before?.primaryKey).toEqual(['userId']);

      await new Migrator(pool, { entities: [AutoSyncKeyTest] }).autoSync({ safe: false });

      const after = await introspector.getTableSchema(tableName);
      expect(after?.primaryKey).toEqual(['userId', 'groupId']);
    });

    /** SQLite can only rebuild the table, so it refuses by name rather than emitting DDL. */
    it.skipIf(!db.unsafeKeyError)('should refuse to change a key it cannot alter', async () => {
      @Entity()
      class AutoSyncKeyRefusedTest {
        @Id({ type: Number }) userId?: number;
        @Id({ type: Number }) groupId?: number;
      }

      const tableName = 'AutoSyncKeyRefusedTest';
      await givenTable(
        tableName,
        `${escapeId('userId')} ${db.keyColumnType} NOT NULL, PRIMARY KEY (${escapeId('userId')})`,
      );

      await expect(
        new Migrator(pool, { entities: [AutoSyncKeyRefusedTest] }).autoSync({ safe: false }),
      ).rejects.toThrow(db.unsafeKeyError);
    });

    it('should create an index the entity declares on a table that already exists', async () => {
      @Entity()
      class AutoSyncIndexTest {
        @Id({ type: Number }) id?: number;
        @Field({ type: String, index: true }) email?: string;
      }

      const tableName = 'AutoSyncIndexTest';
      await givenTable(tableName, `${db.serialIdColumn}, ${escapeId('email')} ${db.textType}`);

      const before = await introspector.introspect();
      expect(before.getTable(tableName)!.indexes).toEqual([]);

      await new Migrator(pool, { entities: [AutoSyncIndexTest] }).autoSync({ logging: true });

      const after = await introspector.introspect();
      expect(after.getTable(tableName)!.indexes.map((index) => index.name)).toEqual(['AutoSyncIndexTest__email_idx']);
    });

    it('should add multiple new properties to an existing entity', async () => {
      @Entity()
      class AutoSyncProductTest1 {
        @Id({ type: Number }) id?: number;
        @Field({ type: String }) name?: string;
        @Field({ type: Number }) price?: number;
        @Field({ type: String }) description?: string;
        @Field({ type: Boolean }) active?: boolean;
      }

      const tableName = 'AutoSyncProductTest1';
      await givenTable(tableName, `${db.serialIdColumn}, ${escapeId('name')} ${db.textType}`);

      await new Migrator(pool, { entities: [AutoSyncProductTest1] }).autoSync({ logging: true });

      const ast = await introspector.introspect();
      const table = ast.getTable(tableName);
      expect(table).toBeDefined();
      expect(Array.from(table!.columns.keys()).sort()).toEqual(['active', 'description', 'id', 'name', 'price']);
    });

    it('should not modify table when schema is already in sync', async () => {
      @Entity()
      class AutoSyncCategoryTest1 {
        @Id({ type: Number }) id?: number;
        @Field({ type: String }) name?: string;
      }

      const tableName = 'AutoSyncCategoryTest1';
      await givenTable(tableName, `${db.serialIdColumn}, ${escapeId('name')} ${db.textType}`);

      const before = await introspector.introspect();
      expect(before.getTable(tableName)).toBeDefined();

      await new Migrator(pool, { entities: [AutoSyncCategoryTest1] }).autoSync({ logging: true });

      const after = await introspector.introspect();
      expect(after.getTable(tableName)).toBeDefined();
      expect(after.getTable(tableName)!.columns.size).toBe(before.getTable(tableName)!.columns.size);
    });

    it('should create a new table if it does not exist', async () => {
      @Entity()
      class AutoSyncNewTableTest1 {
        @Id({ type: Number }) id?: number;
        @Field({ type: String }) title?: string;
        @Field({ type: String }) content?: string;
      }

      const tableName = 'AutoSyncNewTableTest1';
      await givenNoTable(tableName);

      expect(await introspector.tableExists(tableName)).toBe(false);

      await new Migrator(pool, { entities: [AutoSyncNewTableTest1] }).autoSync({ logging: true });

      expect(await introspector.tableExists(tableName)).toBe(true);

      const ast = await introspector.introspect();
      const table = ast.getTable(tableName);
      expect(table).toBeDefined();
      expect(table!.columns.size).toBe(3);
    });

    it('should handle entity with custom table name', async () => {
      @Entity({ name: 'custom_user_table' })
      class AutoSyncCustomNameTest1 {
        @Id({ type: Number }) id?: number;
        @Field({ type: String }) username?: string;
        @Field({ type: String }) email?: string;
      }

      const tableName = 'custom_user_table';
      await givenTable(tableName, `${db.serialIdColumn}, ${escapeId('username')} ${db.textType}`);

      await new Migrator(pool, { entities: [AutoSyncCustomNameTest1] }).autoSync({ logging: true });

      const ast = await introspector.introspect();
      const table = ast.getTable(tableName);
      expect(table).toBeDefined();
      expect(Array.from(table!.columns.keys()).sort()).toEqual(['email', 'id', 'username']);
    });

    it('should handle field with custom column name', async () => {
      @Entity()
      class AutoSyncCustomColumnTest1 {
        @Id({ type: Number }) id?: number;
        @Field({ type: String, name: 'user_email' }) email?: string;
      }

      const tableName = 'AutoSyncCustomColumnTest1';
      await givenTable(tableName, db.serialIdColumn);

      await new Migrator(pool, { entities: [AutoSyncCustomColumnTest1] }).autoSync({ logging: true });

      const ast = await introspector.introspect();
      const table = ast.getTable(tableName);
      expect(table).toBeDefined();
      expect(Array.from(table!.columns.keys()).sort()).toEqual(['id', 'user_email']);
    });

    it('should handle field rename safely (add new, keep old)', async () => {
      @Entity()
      class AutoSyncRenameTest {
        @Id({ type: Number }) id?: number;
        @Field({ type: String }) newName?: string;
      }

      const tableName = 'AutoSyncRenameTest';
      await givenTable(tableName, `${db.serialIdColumn}, ${escapeId('oldName')} ${db.textType}`);

      await new Migrator(pool, { entities: [AutoSyncRenameTest] }).autoSync({ logging: true });

      const ast = await introspector.introspect();
      const table = ast.getTable(tableName);
      expect(table).toBeDefined();
      expect(Array.from(table!.columns.keys()).sort()).toEqual(['id', 'newName', 'oldName']);
    });

    it('should drop old column and add new one when renaming with safe: false', async () => {
      @Entity()
      class AutoSyncUnsafeRenameTest {
        @Id({ type: Number }) id?: number;
        @Field({ type: String }) newName?: string;
      }

      const tableName = 'AutoSyncUnsafeRenameTest';
      await givenTable(tableName, `${db.serialIdColumn}, ${escapeId('oldName')} ${db.textType}`);

      await new Migrator(pool, { entities: [AutoSyncUnsafeRenameTest] }).autoSync({
        logging: true,
        safe: false,
        drop: true,
      });

      const ast = await introspector.introspect();
      const table = ast.getTable(tableName);
      expect(table).toBeDefined();
      expect(Array.from(table!.columns.keys()).sort()).toEqual(['id', 'newName']);
    });

    it('should NOT alter existing DOUBLE column to BIGINT for number field (Safe Mode)', async () => {
      @Entity()
      class AutoSyncFloatTest {
        @Id({ type: Number }) id?: number;
        @Field({ type: Number }) cost?: number;
      }

      const tableName = 'AutoSyncFloatTest';
      await givenTable(tableName, `${db.serialIdColumn}, ${escapeId('cost')} ${db.doubleType}`);

      await new Migrator(pool, { entities: [AutoSyncFloatTest] }).autoSync({ logging: true });

      const ast = await introspector.introspect();
      const table = ast.getTable(tableName);
      expect(table).toBeDefined();

      const costCol = table!.columns.get('cost');
      expect(costCol).toBeDefined();

      const type = costCol!.type.category.toLowerCase();
      const isFloatCompatible =
        type.includes('double') || type.includes('float') || type.includes('real') || type.includes('decimal');

      expect(isFloatCompatible).toBe(true);
      expect(type).not.toContain('bigint');
      expect(type).not.toContain('int8'); // postgres bigint alias
    });

    it('should block drops even if safe: false (when drop: false)', async () => {
      @Entity()
      class AutoSyncNoDropTest {
        @Id({ type: Number }) id?: number;
        @Field({ type: String }) name?: string;
      }

      const tableName = 'AutoSyncNoDropTest';
      await givenTable(
        tableName,
        `${db.serialIdColumn}, ${escapeId('name')} ${db.textType}, ${escapeId('extraColumn')} ${db.textType}`,
      );

      await new Migrator(pool, { entities: [AutoSyncNoDropTest] }).autoSync({ logging: true, safe: false });

      const ast = await introspector.introspect();
      const table = ast.getTable(tableName);
      expect(table).toBeDefined();
      expect(Array.from(table!.columns.keys()).sort()).toEqual(['extraColumn', 'id', 'name']);
    });

    it('should log skipped migrations when safe mode blocks changes', async () => {
      @Entity()
      class AutoSyncLogTest {
        @Id({ type: Number }) id?: number;
        @Field({ type: String }) name?: string;
      }

      const tableName = 'AutoSyncLogTest';
      await givenTable(
        tableName,
        `${db.serialIdColumn}, ${escapeId('name')} ${db.textType}, ${escapeId('extraColumn')} ${db.textType}`,
      );

      const consoleSpy = vi.spyOn(console, 'info').mockImplementation(() => {});
      try {
        await new Migrator(pool, { entities: [AutoSyncLogTest], logger: true }).autoSync({ logging: true });

        expect(consoleSpy).toHaveBeenCalledWith(expect.stringContaining('skipped migration:'));
        expect(consoleSpy).toHaveBeenCalledWith(expect.stringContaining('Skipped dropping 1 columns'));
      } finally {
        consoleSpy.mockRestore();
      }
    });

    it.skipIf(!!db.unsafeAlterError)('should alter column type when safe: false', async () => {
      @Entity()
      class AutoSyncUnsafeAlterTest {
        @Id({ type: Number }) id?: number;
        @Field({ type: Number }) cost?: number; // Defaults to bigint
      }

      const tableName = 'AutoSyncUnsafeAlterTest';
      await givenTable(tableName, `${db.serialIdColumn}, ${escapeId('cost')} ${db.doubleType}`);

      await new Migrator(pool, { entities: [AutoSyncUnsafeAlterTest] }).autoSync({ logging: true, safe: false });

      const ast = await introspector.introspect();
      const table = ast.getTable(tableName);
      expect(table).toBeDefined();

      const costCol = table!.columns.get('cost');
      expect(costCol).toBeDefined();

      const type = costCol!.type.category.toLowerCase();
      expect(type).toContain('int');
      expect(type).not.toContain('double');
    });

    it.runIf(!!db.unsafeAlterError)('should throw error when altering column type (system limitation)', async () => {
      @Entity()
      class AutoSyncUnsafeAlterErrorTest {
        @Id({ type: Number }) id?: number;
        @Field({ type: Number }) cost?: number;
      }

      const tableName = 'AutoSyncUnsafeAlterErrorTest';
      await givenTable(tableName, `${db.serialIdColumn}, ${escapeId('cost')} ${db.doubleType}`);

      const migrator = new Migrator(pool, { entities: [AutoSyncUnsafeAlterErrorTest] });

      await expect(migrator.autoSync({ logging: true, safe: false })).rejects.toThrow(db.unsafeAlterError);
    });
  });
}
