import { describe, expect, it } from 'vitest';
import { Entity, Field, Id, ManyToOne } from '../entity/index.js';
import { MariaDialect } from '../maria/mariaDialect.js';
import { MySqlDialect } from '../mysql/mysqlDialect.js';
import { PostgresDialect } from '../postgres/postgresDialect.js';
import type { ColumnNode, IndexNode, TableNode } from '../schema/types.js';
import { SqliteDialect } from '../sqlite/sqliteDialect.js';
import { mockTableNode } from '../test/index.js';
import type { ColumnSchema } from '../type/index.js';
import type { FullColumnDefinition, TableDefinition } from './builder/types.js';
import { SqlSchemaGenerator } from './schemaGenerator.js';

// Test entities
@Entity()
class TestUser {
  @Id({ type: Number })
  id?: number;

  @Field({ type: String, length: 100 })
  name?: string;

  @Field({ type: String, unique: true })
  email?: string;

  @Field({ type: String, nullable: false })
  password?: string;

  @Field({ type: Number, onInsert: Date.now })
  createdAt?: number;
}

@Entity({ name: 'blog_posts' })
class TestPost {
  @Id({ type: String, onInsert: () => crypto.randomUUID(), length: 36 })
  id?: string;

  @Field({ type: String })
  title?: string;

  @Field({ type: String, columnType: 'text' })
  content?: string;

  @Field({ type: 'jsonb' })
  metadata?: Record<string, unknown>;

  @Field({ references: () => TestUser })
  authorId?: number;

  @ManyToOne({ entity: () => TestUser })
  author?: TestUser;
}

@Entity()
class SqliteIndexedEntity {
  @Id({ type: Number }) id?: number;
  @Field({ type: String, index: true })
  slug?: string;
}

describe('SqlSchemaGenerator (Postgres)', () => {
  const generator = new SqlSchemaGenerator(new PostgresDialect());

  it('should generate CREATE TABLE for simple entity', () => {
    const sql = generator.generateCreateSchema([TestUser]).join('\n');

    expect(sql).toContain('CREATE TABLE "TestUser"');
    expect(sql).toContain('"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
    expect(sql).toContain('"name" VARCHAR(100)');
    expect(sql).toContain('"email" TEXT UNIQUE');
    expect(sql).toContain('"password" TEXT NOT NULL');
    expect(sql).toContain('"createdAt"');
  });

  it('should generate CREATE TABLE with UUID primary key', () => {
    const sql = generator.generateCreateSchema([TestPost]).join('\n');

    expect(sql).toContain('CREATE TABLE "blog_posts"');
    expect(sql).toContain('"id" VARCHAR(36) PRIMARY KEY');
    expect(sql).toContain('"title" TEXT');
    expect(sql).toContain('"content" TEXT');
    expect(sql).toContain('"metadata" JSONB');
    expect(sql).toContain('"authorId" BIGINT');
  });

  it('should generate DROP TABLE statement', () => {
    const sql = generator.generateDropTable('TestUser', { ifExists: true });

    expect(sql).toBe('DROP TABLE IF EXISTS "TestUser";');
  });
  /** Build a minimal TableNode mock with an id + embedding column and the given vector indexes. */
  function buildVectorTableNode(indexes: Partial<IndexNode>[]): TableNode {
    const table = {
      name: 'embeddings',
      primaryKey: [],
      indexes: [],
      outgoingRelations: [],
      incomingRelations: [],
    } as unknown as TableNode;
    (table as { columns: Map<string, ColumnNode> }).columns = new Map<string, ColumnNode>([
      [
        'id',
        {
          name: 'id',
          type: { category: 'integer' },
          nullable: false,
          isPrimaryKey: true,
          isAutoIncrement: true,
          isUnique: false,
          table,
        } as ColumnNode,
      ],
      [
        'embedding',
        {
          name: 'embedding',
          type: { category: 'vector', length: 1536 },
          nullable: false,
          isPrimaryKey: false,
          isAutoIncrement: false,
          isUnique: false,
          table,
        } as ColumnNode,
      ],
    ]);
    (table as { indexes: IndexNode[] }).indexes = indexes.map(
      (idx) =>
        ({
          name: 'idx_vec',
          table,
          columns: [{ name: 'embedding' }],
          entries: [{ column: 'embedding' }],
          unique: false,
          type: 'vector',
          ...idx,
        }) as IndexNode,
    );
    return table;
  }

  it('should emit CREATE VECTOR INDEX for MariaDB', () => {
    const mariaGenerator = new SqlSchemaGenerator(new MariaDialect());
    const statements = mariaGenerator.generateCreateTableFromNode(buildVectorTableNode([{}]));
    expect(statements.at(-1)).toBe('CREATE VECTOR INDEX `idx_vec` ON `embeddings` (`embedding`);');
    expect(statements[0]).not.toContain('VECTOR INDEX');
    expect(statements.join('\n')).not.toContain('CREATE EXTENSION');
  });

  // Verified against MariaDB 12.3: a nullable column makes the whole statement fail with
  // "All parts of a VECTOR index must be NOT NULL", whatever the entity declared.
  it('should force NOT NULL on a MariaDB indexed vector column', () => {
    const mariaGenerator = new SqlSchemaGenerator(new MariaDialect());
    const table = buildVectorTableNode([{ distance: 'cosine' }]);
    (table.columns.get('embedding') as { nullable: boolean }).nullable = true;

    const sql = mariaGenerator.generateCreateTableFromNode(table).join('\n');

    expect(sql).toContain('`embedding` VECTOR(1536) NOT NULL');
  });

  it('should emit CREATE VECTOR INDEX with M and DISTANCE for MariaDB', () => {
    const mariaGenerator = new SqlSchemaGenerator(new MariaDialect());
    const sql = mariaGenerator
      .generateCreateTableFromNode(buildVectorTableNode([{ distance: 'cosine', m: 8 }]))
      .join('\n');
    expect(sql).toContain('ON `embeddings` (`embedding`) M=8 DISTANCE=cosine;');
  });

  it('should emit CREATE VECTOR INDEX with l2 as euclidean for MariaDB', () => {
    const mariaGenerator = new SqlSchemaGenerator(new MariaDialect());
    const sql = mariaGenerator.generateCreateTableFromNode(buildVectorTableNode([{ distance: 'l2' }])).join('\n');
    expect(sql).toContain('ON `embeddings` (`embedding`) DISTANCE=euclidean;');
  });

  // pgvector's index types are not access methods MariaDB has, so they are named rather than
  // compiled into a ` USING hnsw` the server can only answer with a syntax error.
  it.each(['hnsw', 'ivfflat'] as const)('should reject a %s index on MariaDB', (type) => {
    const mariaGenerator = new SqlSchemaGenerator(new MariaDialect());
    expect(() => mariaGenerator.generateCreateTableFromNode(buildVectorTableNode([{ type }]))).toThrow(
      `mariadb has no ${type} index (index "idx_vec"); declare type: 'vector' instead`,
    );
  });

  it('should throw for a MariaDB vector index with an unsupported distance metric, not silently default to euclidean', () => {
    const mariaGenerator = new SqlSchemaGenerator(new MariaDialect());
    expect(() => mariaGenerator.generateCreateTableFromNode(buildVectorTableNode([{ distance: 'inner' }]))).toThrow(
      'mariadb does not support vector distance metric: inner',
    );
  });

  it('should not resolve a vector distance keyword via the prototype chain for an unvalidated distance value', () => {
    const mariaGenerator = new SqlSchemaGenerator(new MariaDialect());
    expect(() =>
      mariaGenerator.generateCreateTableFromNode(buildVectorTableNode([{ distance: 'toString' as any }])),
    ).toThrow('mariadb does not support vector distance metric: toString');
  });

  it('should prepend CREATE EXTENSION for Postgres tables with vector columns', () => {
    const sql = generator.generateCreateTableFromNode(buildVectorTableNode([])).join('\n');
    expect(sql).toMatch(/^CREATE EXTENSION IF NOT EXISTS vector;/);
    expect(sql).toContain('CREATE TABLE');
  });

  it('should generate CREATE TABLE with IF NOT EXISTS', () => {
    const sql = generator.generateCreateSchema([TestUser], { ifNotExists: true }).join('\n');
    expect(sql).toContain('CREATE TABLE IF NOT EXISTS "TestUser"');
  });

  it('should handle already-typed column schemas', () => {
    const sql = generator.generateAlterTable({
      tableName: 'users',
      type: 'alter',
      columnsToAdd: [
        {
          name: 'profile_data',
          type: 'JSONB',
          nullable: true,
          isPrimaryKey: false,
          isAutoIncrement: false,
          isUnique: false,
        },
      ],
    });
    // Should NOT be JSONB(JSONB)
    expect(sql[0]).toContain('ADD COLUMN "profile_data" JSONB');
    expect(sql[0]).not.toContain('JSONB(');
  });

  it('should generate ALTER TABLE DOWN statements for column additions', () => {
    const sql = generator.generateAlterTableDown({
      tableName: 'users',
      type: 'alter',
      columnsToAdd: [
        {
          name: 'profile_data',
          type: 'JSONB',
          nullable: true,
          isPrimaryKey: false,
          isAutoIncrement: false,
          isUnique: false,
        },
      ],
    });
    expect(sql[0]).toBe('ALTER TABLE "users" DROP COLUMN "profile_data";');
  });

  it('should generate ALTER TABLE DOWN statements for column alterations', () => {
    const sql = generator.generateAlterTableDown({
      tableName: 'users',
      type: 'alter',
      columnsToAlter: [
        {
          from: {
            name: 'age',
            type: 'INTEGER',
            nullable: true,
            isPrimaryKey: false,
            isAutoIncrement: false,
            isUnique: false,
          },
          to: {
            name: 'age',
            type: 'BIGINT',
            nullable: false,
            isPrimaryKey: false,
            isAutoIncrement: false,
            isUnique: false,
          },
        },
      ],
    });
    expect(sql.length).toBeGreaterThan(0);
    expect(sql[0]).toContain('ALTER TABLE');
    expect(sql[0]).toContain('"age"');
    expect(sql[0]).toContain('INTEGER');
  });

  it('should generate ALTER TABLE DOWN statements for index additions', () => {
    const sql = generator.generateAlterTableDown({
      tableName: 'users',
      type: 'alter',
      indexesToAdd: [{ name: 'idx_users_email', entries: [{ column: 'email' }], unique: true }],
    });
    expect(sql[0]).toBe('DROP INDEX IF EXISTS "idx_users_email";');
  });

  it('should add TODO comment for dropped columns/indexes', () => {
    const sql1 = generator.generateAlterTableDown({
      tableName: 'users',
      type: 'alter',
      columnsToDrop: ['old_column'],
    });
    expect(sql1[0]).toContain('TODO');

    const sql2 = generator.generateAlterTableDown({
      tableName: 'users',
      type: 'alter',
      indexesToDrop: ['idx_old'],
    });
    expect(sql2[0]).toContain('TODO');
  });

  it('should generate ALTER TABLE statements for dropping columns and indexes', () => {
    const sql = generator.generateAlterTable({
      tableName: 'users',
      type: 'alter',
      columnsToDrop: ['old_col'],
      indexesToDrop: ['idx_old'],
      indexesToAdd: [{ name: 'idx_new', entries: [{ column: 'name' }], unique: false }],
    });
    expect(sql).toContain('ALTER TABLE "users" DROP COLUMN "old_col";');
    expect(sql).toContain('DROP INDEX IF EXISTS "idx_old";');
    expect(sql).toContain('CREATE INDEX IF NOT EXISTS "idx_new" ON "users" ("name");');
  });
});

describe('SqlSchemaGenerator (MySQL)', () => {
  const generator = new SqlSchemaGenerator(new MySqlDialect());

  it('should generate CREATE TABLE for simple entity', () => {
    const sql = generator.generateCreateSchema([TestUser]).join('\n');

    expect(sql).toContain('CREATE TABLE `TestUser`');
    expect(sql).toContain('`id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY');
    expect(sql).toContain('`name` VARCHAR(100)');
    expect(sql).toContain('`email` VARCHAR(255) UNIQUE');
    expect(sql).toContain('ENGINE=InnoDB');
  });

  it('should generate boolean as TINYINT(1)', () => {
    const boolType = generator.getSqlType({ type: Boolean }, Boolean);
    expect(boolType).toBe('TINYINT(1)');
  });

  it('should generate DROP INDEX with ON table', () => {
    const sql = generator.generateDropIndex('users', 'idx_email');
    expect(sql).toBe('DROP INDEX `idx_email` ON `users`;');
  });
});

describe('SqlSchemaGenerator (SQLite)', () => {
  const generator = new SqlSchemaGenerator(new SqliteDialect());

  it('should generate CREATE TABLE for simple entity', () => {
    const sql = generator.generateCreateSchema([TestUser]).join('\n');

    expect(sql).toContain('CREATE TABLE `TestUser`');
    expect(sql).toContain('`id` INTEGER PRIMARY KEY AUTOINCREMENT');
    expect(sql).toContain('`name` TEXT');
    expect(sql).toContain('`email` TEXT UNIQUE');
  });

  it('should use TEXT for most types (SQLite dynamic typing)', () => {
    expect(generator.getSqlType({ columnType: 'varchar' }, String)).toBe('TEXT');
    expect(generator.getSqlType({ columnType: 'json' }, undefined)).toBe('TEXT');
    expect(generator.getSqlType({ columnType: 'uuid' }, undefined)).toBe('TEXT');
  });

  it('should use INTEGER for numeric types', () => {
    expect(generator.getSqlType({ columnType: 'int' }, undefined)).toBe('INTEGER');
    expect(generator.getSqlType({ columnType: 'bigint' }, undefined)).toBe('INTEGER');
    expect(generator.getSqlType({ type: Boolean }, Boolean)).toBe('INTEGER');
  });

  it('generateCreateSchema splits non-inline indexes for separate querier.run', () => {
    const stmts = generator.generateCreateSchema([SqliteIndexedEntity]);
    expect(stmts).toHaveLength(2);
    expect(stmts[0]).toMatch(/^CREATE TABLE `SqliteIndexedEntity`/);
    expect(stmts[1]).toMatch(/^CREATE INDEX `idx_SqliteIndexedEntity_slug`/);
  });
});

describe('SqlSchemaGenerator Integration', () => {
  const generator = new SqlSchemaGenerator(new PostgresDialect());

  it('should generate CREATE TABLE from TableNode', () => {
    const table = {
      name: 'users',
      columns: new Map<string, ColumnNode>(),
      primaryKey: [],
      indexes: [],
      incomingRelations: [],
      outgoingRelations: [],
    } as unknown as TableNode;
    (table as { columns: Map<string, ColumnNode> }).columns = new Map<string, ColumnNode>([
      [
        'id',
        {
          name: 'id',
          type: { category: 'integer', size: 'big' },
          isPrimaryKey: true,
          isAutoIncrement: true,
          nullable: false,
          table,
        } as ColumnNode,
      ],
      ['name', { name: 'name', type: { category: 'string', length: 100 }, nullable: true, table } as ColumnNode],
    ]);
    (table as { primaryKey: ColumnNode[] }).primaryKey = [table.columns.get('id')!];

    const sql = generator.generateCreateTableFromNode(table).join('\n');
    expect(sql).toContain('CREATE TABLE "users"');
    expect(sql).toContain('"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
    expect(sql).toContain('"name" VARCHAR(100)');
  });

  it('should generate CREATE INDEX from IndexNode', () => {
    const table = mockTableNode('users', [{ name: 'name' }]);
    const index: IndexNode = {
      name: 'idx_name',
      table,
      entries: [{ column: 'name' }],
      unique: true,
    };
    const sql = generator.generateCreateIndexFromNode(index);
    expect(sql).toBe('CREATE UNIQUE INDEX "idx_name" ON "users" ("name");');
  });

  // The predicate used to be dropped between IndexNode and IndexSchema, turning the soft-delete
  // pattern (unique among live rows) into a unique index over every row.
  it('should carry a partial index predicate from IndexNode', () => {
    const table = mockTableNode('users', [{ name: 'email' }]);
    const index: IndexNode = {
      name: 'idx_live_email',
      table,
      entries: [{ column: 'email' }],
      unique: true,
      where: '"deletedAt" IS NULL',
    };
    const sql = generator.generateCreateIndexFromNode(index);
    expect(sql).toBe('CREATE UNIQUE INDEX "idx_live_email" ON "users" ("email") WHERE "deletedAt" IS NULL;');
  });

  it('should generate DROP TABLE from TableNode', () => {
    const table = { name: 'users' } as TableNode;
    const sql = generator.generateDropTable(table.name, { ifExists: true });
    expect(sql).toBe('DROP TABLE IF EXISTS "users";');
  });

  it('should generate DROP TABLE without IF EXISTS by default', () => {
    const table = { name: 'users' } as TableNode;
    expect(generator.generateDropTable(table.name)).toBe('DROP TABLE "users";');
  });
});

/**
 * `ColumnSchema` is the shape a diff carries, so these are the columns an `ALTER TABLE ... ADD
 * COLUMN` emits - the qualifiers have to survive the round trip from the diff to the DDL.
 */
describe('SqlSchemaGenerator column definitions from ColumnSchema', () => {
  const generator = new SqlSchemaGenerator(new PostgresDialect());

  /** ADD COLUMN for a single `ColumnSchema`, with only the qualifiers under test overridden. */
  function addColumn(column: Partial<ColumnSchema>, gen = generator): string {
    return gen.generateAlterTable({
      tableName: 'users',
      type: 'alter',
      columnsToAdd: [
        {
          name: 'col',
          type: 'INTEGER',
          nullable: true,
          isPrimaryKey: false,
          isAutoIncrement: false,
          isUnique: false,
          ...column,
        },
      ],
    })[0];
  }

  it('should append precision and scale to a bare type', () => {
    expect(addColumn({ name: 'amount', type: 'NUMERIC', precision: 12, scale: 4 })).toBe(
      'ALTER TABLE "users" ADD COLUMN "amount" NUMERIC(12, 4);',
    );
  });

  it('should append precision alone when there is no scale', () => {
    expect(addColumn({ name: 'amount', type: 'NUMERIC', precision: 12 })).toBe(
      'ALTER TABLE "users" ADD COLUMN "amount" NUMERIC(12);',
    );
  });

  it('should append length when there is no precision', () => {
    expect(addColumn({ name: 'name', type: 'VARCHAR', length: 100 })).toBe(
      'ALTER TABLE "users" ADD COLUMN "name" VARCHAR(100);',
    );
  });

  it('should keep a type that already carries its own parameters', () => {
    expect(addColumn({ name: 'name', type: 'VARCHAR(50)', length: 100, precision: 12, scale: 4 })).toBe(
      'ALTER TABLE "users" ADD COLUMN "name" VARCHAR(50);',
    );
  });

  it('should emit NOT NULL for a non-nullable column', () => {
    expect(addColumn({ nullable: false })).toBe('ALTER TABLE "users" ADD COLUMN "col" INTEGER NOT NULL;');
  });

  it('should emit UNIQUE for a unique column', () => {
    expect(addColumn({ isUnique: true })).toBe('ALTER TABLE "users" ADD COLUMN "col" INTEGER UNIQUE;');
  });

  /** A primary key is already NOT NULL and UNIQUE; repeating either is redundant DDL. */
  it('should emit PRIMARY KEY alone for a non-nullable unique primary key', () => {
    expect(addColumn({ nullable: false, isUnique: true, isPrimaryKey: true })).toBe(
      'ALTER TABLE "users" ADD COLUMN "col" INTEGER PRIMARY KEY;',
    );
  });

  it('should not duplicate a PRIMARY KEY already present in the type', () => {
    expect(addColumn({ type: 'SERIAL PRIMARY KEY', isPrimaryKey: true })).toBe(
      'ALTER TABLE "users" ADD COLUMN "col" SERIAL PRIMARY KEY;',
    );
  });

  it('should quote a string default and escape its quotes', () => {
    expect(addColumn({ type: 'TEXT', defaultValue: "it's" })).toBe(
      `ALTER TABLE "users" ADD COLUMN "col" TEXT DEFAULT 'it''s';`,
    );
  });

  it('should emit a NULL default distinctly from no default', () => {
    expect(addColumn({ defaultValue: null })).toBe('ALTER TABLE "users" ADD COLUMN "col" INTEGER DEFAULT NULL;');
  });

  it('should emit a native boolean default on Postgres', () => {
    expect(addColumn({ type: 'BOOLEAN', defaultValue: false })).toBe(
      'ALTER TABLE "users" ADD COLUMN "col" BOOLEAN DEFAULT FALSE;',
    );
  });

  /** SQLite/MySQL have no boolean literal, so the default has to bind as 0/1. */
  it('should emit an integer boolean default where booleans are integers', () => {
    const sqliteGenerator = new SqlSchemaGenerator(new SqliteDialect());
    expect(addColumn({ type: 'INTEGER', defaultValue: true }, sqliteGenerator)).toBe(
      'ALTER TABLE `users` ADD COLUMN `col` INTEGER DEFAULT 1;',
    );
    expect(addColumn({ type: 'INTEGER', defaultValue: false }, sqliteGenerator)).toBe(
      'ALTER TABLE `users` ADD COLUMN `col` INTEGER DEFAULT 0;',
    );
  });

  it('should emit a column comment where the dialect supports one', () => {
    const mysqlGenerator = new SqlSchemaGenerator(new MySqlDialect());
    expect(addColumn({ comment: "the user's age", nullable: false }, mysqlGenerator)).toBe(
      "ALTER TABLE `users` ADD COLUMN `col` INTEGER NOT NULL COMMENT 'the user''s age';",
    );
  });

  it('should drop a column comment where the dialect has none', () => {
    expect(addColumn({ comment: 'the age' })).toBe('ALTER TABLE "users" ADD COLUMN "col" INTEGER;');
  });

  /**
   * The reverse of an alteration restores the previous column, and re-declaring its PRIMARY KEY
   * there would be rejected as a duplicate constraint.
   */
  it('should strip PRIMARY KEY when restoring a column in the down direction', () => {
    const sql = new SqlSchemaGenerator(new MySqlDialect()).generateAlterTableDown({
      tableName: 'users',
      type: 'alter',
      columnsToAlter: [
        {
          from: {
            name: 'id',
            type: 'BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY',
            nullable: false,
            isPrimaryKey: true,
            isAutoIncrement: true,
            isUnique: false,
          },
          to: {
            name: 'id',
            type: 'BIGINT UNSIGNED',
            nullable: false,
            isPrimaryKey: false,
            isAutoIncrement: false,
            isUnique: false,
          },
        },
      ],
    });
    expect(sql).toEqual(['ALTER TABLE `users` MODIFY COLUMN `id` BIGINT UNSIGNED AUTO_INCREMENT;']);
  });
});

describe('SqlSchemaGenerator table definitions from the migration builder', () => {
  const generator = new SqlSchemaGenerator(new PostgresDialect());

  /** A `TableDefinition` for two columns, with the parts under test overridden. */
  function tableDefinition(overrides: Partial<TableDefinition> = {}): TableDefinition {
    return {
      name: 'memberships',
      columns: [
        column({ name: 'userId' }),
        column({
          name: 'groupId',
          foreignKey: { table: 'groups', columns: ['id'], onDelete: 'CASCADE', onUpdate: 'NO ACTION' },
        }),
      ],
      indexes: [],
      foreignKeys: [],
      ...overrides,
    };
  }

  function column(overrides: Partial<FullColumnDefinition>): FullColumnDefinition {
    return {
      name: 'col',
      type: { category: 'integer' },
      nullable: false,
      primaryKey: false,
      autoIncrement: false,
      unique: false,
      ...overrides,
    };
  }

  it('should generate a composite PRIMARY KEY from the declared key columns', () => {
    const sql = generator
      .generateCreateTableFromDefinition(tableDefinition({ primaryKey: ['userId', 'groupId'] }))
      .join('\n');
    expect(sql).toContain('PRIMARY KEY ("userId", "groupId")');
  });

  it('should ignore a declared key column that no column definition matches', () => {
    const sql = generator
      .generateCreateTableFromDefinition(tableDefinition({ primaryKey: ['userId', 'nope', 'groupId'] }))
      .join('\n');
    expect(sql).toContain('PRIMARY KEY ("userId", "groupId")');
    expect(sql).not.toContain('nope');
  });

  it('should fall back to the columns flagged as primary when no key is declared', () => {
    const definition = tableDefinition();
    definition.columns[0] = column({ name: 'userId', primaryKey: true, autoIncrement: true });
    const sql = generator.generateCreateTableFromDefinition(definition).join('\n');
    expect(sql).toContain('"userId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
  });

  it('should generate the declared indexes as separate statements', () => {
    const statements = generator.generateCreateTableFromDefinition(
      tableDefinition({
        indexes: [
          { name: 'idx_memberships_userId', entries: [{ column: 'userId' }], unique: false },
          {
            name: 'uq_memberships_pair',
            entries: [{ column: 'userId' }, { column: 'groupId' }],
            unique: true,
          },
        ],
      }),
    );
    expect(statements).toHaveLength(3);
    expect(statements[1]).toBe('CREATE INDEX "idx_memberships_userId" ON "memberships" ("userId");');
    expect(statements[2]).toBe('CREATE UNIQUE INDEX "uq_memberships_pair" ON "memberships" ("userId", "groupId");');
  });

  it('should keep the index options a definition declares, not just its columns', () => {
    const statements = generator.generateCreateTableFromDefinition(
      tableDefinition({
        indexes: [
          {
            name: 'idx_memberships_active',
            entries: [
              { column: 'userId', order: 'desc' },
              { column: 'lower("groupId")', expression: true },
            ],
            unique: true,
            where: '"deletedAt" IS NULL',
            include: ['groupId'],
          },
        ],
      }),
    );
    expect(statements[1]).toBe(
      'CREATE UNIQUE INDEX "idx_memberships_active" ON "memberships" ("userId" DESC, (lower("groupId"))) ' +
        'INCLUDE ("groupId") WHERE "deletedAt" IS NULL;',
    );
  });

  it('should generate a table-level FOREIGN KEY with its declared actions', () => {
    const sql = generator
      .generateCreateTableFromDefinition(
        tableDefinition({
          foreignKeys: [
            {
              name: 'fk_memberships_user',
              columns: ['userId'],
              referencesTable: 'users',
              referencesColumns: ['id'],
              onDelete: 'CASCADE',
              onUpdate: 'NO ACTION',
            },
          ],
        }),
      )
      .join('\n');
    expect(sql).toContain(
      'CONSTRAINT "fk_memberships_user" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION',
    );
  });

  it('should name an unnamed table-level FOREIGN KEY after its table and columns', () => {
    const sql = generator
      .generateCreateTableFromDefinition(
        tableDefinition({
          foreignKeys: [
            {
              columns: ['userId'],
              referencesTable: 'users',
              referencesColumns: ['id'],
              onDelete: 'NO ACTION',
              onUpdate: 'NO ACTION',
            },
          ],
        }),
      )
      .join('\n');
    expect(sql).toContain('CONSTRAINT "fk_memberships_userId" FOREIGN KEY ("userId")');
  });

  it('should generate ADD CONSTRAINT for a foreign key added to an existing table', () => {
    const sql = generator.generateAddForeignKeySql('memberships', {
      columns: ['groupId'],
      referencesTable: 'groups',
      referencesColumns: ['id'],
      onDelete: 'SET NULL',
      onUpdate: 'CASCADE',
    });
    expect(sql).toBe(
      'ALTER TABLE "memberships" ADD CONSTRAINT "fk_memberships_groupId" ' +
        'FOREIGN KEY ("groupId") REFERENCES "groups" ("id") ON DELETE SET NULL ON UPDATE CASCADE;',
    );
  });

  /** SQLite cannot add a constraint to an existing table, so this has to fail rather than emit invalid DDL. */
  it('should reject adding a foreign key where the dialect cannot alter constraints', () => {
    const sqliteGenerator = new SqlSchemaGenerator(new SqliteDialect());
    expect(() =>
      sqliteGenerator.generateAddForeignKeySql('memberships', {
        columns: ['groupId'],
        referencesTable: 'groups',
        referencesColumns: ['id'],
        onDelete: 'NO ACTION',
        onUpdate: 'NO ACTION',
      }),
    ).toThrow('does not support adding foreign keys to existing tables');
  });

  it('should rename a table with the dialect syntax', () => {
    expect(generator.generateRenameTableSql('old', 'new')).toBe('ALTER TABLE "old" RENAME TO "new";');
    expect(new SqlSchemaGenerator(new MySqlDialect()).generateRenameTableSql('old', 'new')).toBe(
      'RENAME TABLE `old` TO `new`;',
    );
  });
  describe('generateCreateSchema', () => {
    it('emits cross-entity foreign keys, which the per-entity path dropped', () => {
      const generator = new SqlSchemaGenerator(new PostgresDialect());
      const sql = generator.generateCreateSchema([TestUser, TestPost]);

      const creates = sql.filter((s) => s.startsWith('CREATE TABLE'));
      const fks = sql.filter((s) => s.includes('ADD CONSTRAINT'));

      expect(creates).toHaveLength(2);
      // Constraints come after every table, so a cyclic relation graph is creatable at all.
      expect(creates.every((s) => !s.includes('FOREIGN KEY'))).toBe(true);
      expect(fks.some((s) => s.includes('ALTER TABLE "blog_posts"') && s.includes('"TestUser"'))).toBe(true);
    });

    it('keeps constraints inline on SQLite, which cannot ALTER one in', () => {
      const generator = new SqlSchemaGenerator(new SqliteDialect());
      const sql = generator.generateCreateSchema([TestUser, TestPost]);

      // SQLite resolves a foreign key target lazily, so a forward reference is fine and no ALTER is
      // needed. `features.foreignKeyAlter` is false there, which is what selects this shape.
      expect(sql.some((s) => s.includes('ADD CONSTRAINT'))).toBe(false);
      expect(sql.some((s) => s.startsWith('CREATE TABLE') && s.includes('FOREIGN KEY'))).toBe(true);
    });

    it('narrows creation with `only` while still resolving constraints against the full graph', () => {
      const generator = new SqlSchemaGenerator(new PostgresDialect());
      const sql = generator.generateCreateSchema([TestUser, TestPost], { only: ['blog_posts'] });

      expect(sql.filter((s) => s.startsWith('CREATE TABLE'))).toHaveLength(1);
      expect(sql.some((s) => s.includes('ALTER TABLE "blog_posts"') && s.includes('"TestUser"'))).toBe(true);
    });

    it('emits no foreign keys at all when asked for none', () => {
      const generator = new SqlSchemaGenerator(new PostgresDialect());
      const sql = generator.generateCreateSchema([TestUser, TestPost], { foreignKeys: false });

      expect(sql.filter((s) => s.startsWith('CREATE TABLE'))).toHaveLength(2);
      expect(sql.some((s) => s.includes('FOREIGN KEY') || s.includes('ADD CONSTRAINT'))).toBe(false);
    });
  });

  describe('generateDropSchema', () => {
    it('drops dependents before the tables they reference', () => {
      const generator = new SqlSchemaGenerator(new PostgresDialect());
      const sql = generator.generateDropSchema([TestUser, TestPost]);

      // Declaration order puts `TestUser` first, so a reverse-of-declaration drop would emit it last and
      // be rejected: `blog_posts` still references it.
      expect(sql).toEqual(['DROP TABLE "blog_posts";', 'DROP TABLE "TestUser";']);
    });

    it('adds CASCADE only where the dialect has it, since a cycle has no valid order', () => {
      const options = { ifExists: true, cascade: true };

      expect(new SqlSchemaGenerator(new PostgresDialect()).generateDropSchema([TestUser], options)).toEqual([
        'DROP TABLE IF EXISTS "TestUser" CASCADE;',
      ]);
      expect(new SqlSchemaGenerator(new MySqlDialect()).generateDropSchema([TestUser], options)).toEqual([
        'DROP TABLE IF EXISTS `TestUser`;',
      ]);
    });
  });
});
