import { describe, expect, it } from 'vitest';
import { CockroachDialect } from '../cockroachdb/cockroachDialect.js';
import { MariaDialect, MySqlDialect, PostgresDialect, SqliteDialect } from '../dialect/index.js';
import { Entity, Field, Id, ManyToOne } from '../entity/index.js';
import type { ColumnNode, IndexNode, TableNode } from '../schema/types.js';
import type { ColumnSchema } from '../type/index.js';
import type { FullColumnDefinition, TableDefinition } from './builder/types.js';
import { SqlSchemaGenerator } from './schemaGenerator.js';

// Test entities
@Entity()
class TestUser {
  @Id()
  id?: number;

  @Field({ length: 100 })
  name?: string;

  @Field({ unique: true })
  email?: string;

  @Field({ nullable: false })
  password?: string;

  @Field({ onInsert: Date.now })
  createdAt?: number;
}

@Entity({ name: 'blog_posts' })
class TestPost {
  @Id({ onInsert: () => crypto.randomUUID(), length: 36 })
  id?: string;

  @Field()
  title?: string;

  @Field({ columnType: 'text' })
  content?: string;

  @Field({ type: 'jsonb' })
  metadata?: Record<string, unknown>;

  @Field({ references: () => TestUser })
  authorId?: number;

  @ManyToOne()
  author?: TestUser;
}

@Entity()
class SqliteIndexedEntity {
  @Id() id?: number;
  @Field({ index: true })
  slug?: string;
}

describe('SqlSchemaGenerator (Postgres)', () => {
  const generator = new SqlSchemaGenerator(new PostgresDialect());

  it('should generate CREATE TABLE for simple entity', () => {
    const sql = generator.generateCreateTable(TestUser).join('\n');

    expect(sql).toContain('CREATE TABLE "TestUser"');
    expect(sql).toContain('"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
    expect(sql).toContain('"name" VARCHAR(100)');
    expect(sql).toContain('"email" TEXT UNIQUE');
    expect(sql).toContain('"password" TEXT NOT NULL');
    expect(sql).toContain('"createdAt"');
  });

  it('should generate CREATE TABLE with UUID primary key', () => {
    const sql = generator.generateCreateTable(TestPost).join('\n');

    expect(sql).toContain('CREATE TABLE "blog_posts"');
    expect(sql).toContain('"id" VARCHAR(36) PRIMARY KEY');
    expect(sql).toContain('"title" TEXT');
    expect(sql).toContain('"content" TEXT');
    expect(sql).toContain('"metadata" JSONB');
    expect(sql).toContain('"authorId" BIGINT');
  });

  it('should generate DROP TABLE statement', () => {
    const sql = generator.generateDropTable(TestUser);

    expect(sql).toBe('DROP TABLE IF EXISTS "TestUser";');
  });

  it('should generate CREATE INDEX statement', () => {
    const sql = generator.generateCreateIndex('users', {
      name: 'idx_users_email',
      columns: ['email'],
      unique: true,
    });

    expect(sql).toBe('CREATE UNIQUE INDEX IF NOT EXISTS "idx_users_email" ON "users" ("email");');
  });

  it('should generate CREATE INDEX for HNSW vector index', () => {
    const sql = generator.generateCreateIndex('articles', {
      name: 'idx_articles_embedding_hnsw',
      columns: ['embedding'],
      unique: false,
      type: 'hnsw',
      distance: 'cosine',
    });
    expect(sql).toBe(
      'CREATE INDEX IF NOT EXISTS "idx_articles_embedding_hnsw" ON "articles" USING hnsw ("embedding" vector_cosine_ops);',
    );
  });

  it('should generate CREATE INDEX for HNSW with tuning params', () => {
    const sql = generator.generateCreateIndex('articles', {
      name: 'idx_embedding',
      columns: ['embedding'],
      unique: false,
      type: 'hnsw',
      distance: 'l2',
      m: 16,
      efConstruction: 64,
    });
    expect(sql).toBe(
      'CREATE INDEX IF NOT EXISTS "idx_embedding" ON "articles" USING hnsw ("embedding" vector_l2_ops) WITH (m = 16, ef_construction = 64);',
    );
  });

  it('should generate CREATE INDEX for IVFFlat', () => {
    const sql = generator.generateCreateIndex('articles', {
      name: 'idx_embedding_ivf',
      columns: ['embedding'],
      unique: false,
      type: 'ivfflat',
      distance: 'inner',
      lists: 100,
    });
    expect(sql).toBe(
      'CREATE INDEX IF NOT EXISTS "idx_embedding_ivf" ON "articles" USING ivfflat ("embedding" vector_ip_ops) WITH (lists = 100);',
    );
  });

  it('should not emit operator classes or WITH params for non-Postgres dialects', () => {
    const mysqlGenerator = new SqlSchemaGenerator(new MySqlDialect());
    const sql = mysqlGenerator.generateCreateIndex('articles', {
      name: 'idx_embedding',
      columns: ['embedding'],
      unique: false,
      type: 'hnsw',
      distance: 'cosine',
      m: 16,
      efConstruction: 64,
    });
    // MySQL: no operator class, no WITH params - just USING
    expect(sql).toBe('CREATE INDEX `idx_embedding` ON `articles` USING hnsw (`embedding`);');
  });

  it('should generate CREATE VECTOR INDEX for CockroachDB (native syntax, no USING/WITH)', () => {
    const crdbGenerator = new SqlSchemaGenerator(new CockroachDialect());
    const sql = crdbGenerator.generateCreateIndex('articles', {
      name: 'idx_articles_embedding',
      columns: ['embedding'],
      unique: false,
      type: 'vector',
      distance: 'cosine',
      // CockroachDB has its own tuning knobs, not m/efConstruction/lists - must not appear.
      m: 16,
      efConstruction: 64,
    });
    expect(sql).toBe(
      'CREATE VECTOR INDEX IF NOT EXISTS "idx_articles_embedding" ON "articles" ("embedding" vector_cosine_ops);',
    );
  });

  it('should not add an operator class to a CockroachDB index with a non-vector type', () => {
    const crdbGenerator = new SqlSchemaGenerator(new CockroachDialect());
    const sql = crdbGenerator.generateCreateIndex('articles', {
      name: 'idx_articles_name',
      columns: ['name'],
      unique: false,
      type: 'btree',
    });
    expect(sql).toBe('CREATE INDEX IF NOT EXISTS "idx_articles_name" ON "articles" USING btree ("name");');
  });

  it('should throw for a CockroachDB vector index with an unsupported distance metric, not silently drop the opclass', () => {
    const crdbGenerator = new SqlSchemaGenerator(new CockroachDialect());
    expect(() =>
      crdbGenerator.generateCreateIndex('articles', {
        name: 'idx_articles_embedding',
        columns: ['embedding'],
        unique: false,
        type: 'vector',
        distance: 'l1',
      }),
    ).toThrow('cockroachdb does not support vector distance metric: l1');
  });

  it('should not resolve an operator class via the prototype chain for an unvalidated distance value', () => {
    const crdbGenerator = new SqlSchemaGenerator(new CockroachDialect());
    expect(() =>
      crdbGenerator.generateCreateIndex('articles', {
        name: 'idx_articles_embedding',
        columns: ['embedding'],
        unique: false,
        type: 'vector',
        distance: 'toString' as any, // deliberately unvalidated input, mirroring dynamic/JSON query data
      }),
    ).toThrow('cockroachdb does not support vector distance metric: toString');
  });
  /** Build a minimal TableNode mock with an id + embedding column and the given vector indexes. */
  function buildVectorTableNode(indexes: Partial<IndexNode>[]): TableNode {
    const table = {
      name: 'embeddings',
      primaryKey: [],
      indexes: [],
      outgoingRelations: [],
      incomingRelations: [],
    } as unknown as TableNode;
    (table as { columns: Map<string, ColumnNode> }).columns = new Map<string, ColumnNode>([
      [
        'id',
        {
          name: 'id',
          type: { category: 'integer' },
          nullable: false,
          isPrimaryKey: true,
          isAutoIncrement: true,
          isUnique: false,
          table,
        } as ColumnNode,
      ],
      [
        'embedding',
        {
          name: 'embedding',
          type: { category: 'vector', length: 1536 },
          nullable: false,
          isPrimaryKey: false,
          isAutoIncrement: false,
          isUnique: false,
          table,
        } as ColumnNode,
      ],
    ]);
    (table as { indexes: IndexNode[] }).indexes = indexes.map(
      (idx) =>
        ({
          name: 'idx_vec',
          table,
          columns: [{ name: 'embedding' }],
          unique: false,
          type: 'vector',
          ...idx,
        }) as IndexNode,
    );
    return table;
  }

  it('should emit inline VECTOR INDEX for MariaDB', () => {
    const mariaGenerator = new SqlSchemaGenerator(new MariaDialect());
    const sql = mariaGenerator.generateCreateTableFromNode(buildVectorTableNode([{}])).join('\n');
    expect(sql).toContain('VECTOR INDEX (`embedding`)');
    expect(sql).not.toContain('CREATE INDEX');
    expect(sql).not.toContain('CREATE EXTENSION');
  });

  it('should emit inline VECTOR INDEX with M and DISTANCE for MariaDB', () => {
    const mariaGenerator = new SqlSchemaGenerator(new MariaDialect());
    const sql = mariaGenerator
      .generateCreateTableFromNode(buildVectorTableNode([{ distance: 'cosine', m: 8 }]))
      .join('\n');
    expect(sql).toContain('VECTOR INDEX (`embedding`) M=8 DISTANCE=cosine');
  });

  it('should emit VECTOR INDEX with l2 as euclidean for MariaDB', () => {
    const mariaGenerator = new SqlSchemaGenerator(new MariaDialect());
    const sql = mariaGenerator.generateCreateTableFromNode(buildVectorTableNode([{ distance: 'l2' }])).join('\n');
    expect(sql).toContain('VECTOR INDEX (`embedding`) DISTANCE=euclidean');
  });

  it('should throw for a MariaDB inline vector index with an unsupported distance metric, not silently default to euclidean', () => {
    const mariaGenerator = new SqlSchemaGenerator(new MariaDialect());
    expect(() => mariaGenerator.generateCreateTableFromNode(buildVectorTableNode([{ distance: 'inner' }]))).toThrow(
      'mariadb does not support vector distance metric: inner',
    );
  });

  it('should not resolve an inline vector distance keyword via the prototype chain for an unvalidated distance value', () => {
    const mariaGenerator = new SqlSchemaGenerator(new MariaDialect());
    expect(() =>
      mariaGenerator.generateCreateTableFromNode(buildVectorTableNode([{ distance: 'toString' as any }])),
    ).toThrow('mariadb does not support vector distance metric: toString');
  });

  it('should prepend CREATE EXTENSION for Postgres tables with vector columns', () => {
    const sql = generator.generateCreateTableFromNode(buildVectorTableNode([])).join('\n');
    expect(sql).toMatch(/^CREATE EXTENSION IF NOT EXISTS vector;/);
    expect(sql).toContain('CREATE TABLE');
  });

  it('should generate CREATE TABLE with IF NOT EXISTS', () => {
    const sql = generator.generateCreateTable(TestUser, { ifNotExists: true }).join('\n');
    expect(sql).toContain('CREATE TABLE IF NOT EXISTS "TestUser"');
  });

  it('should handle already-typed column schemas', () => {
    const sql = generator.generateAlterTable({
      tableName: 'users',
      type: 'alter',
      columnsToAdd: [
        {
          name: 'profile_data',
          type: 'JSONB',
          nullable: true,
          isPrimaryKey: false,
          isAutoIncrement: false,
          isUnique: false,
        },
      ],
    });
    // Should NOT be JSONB(JSONB)
    expect(sql[0]).toContain('ADD COLUMN "profile_data" JSONB');
    expect(sql[0]).not.toContain('JSONB(');
  });

  it('should generate ALTER TABLE DOWN statements for column additions', () => {
    const sql = generator.generateAlterTableDown({
      tableName: 'users',
      type: 'alter',
      columnsToAdd: [
        {
          name: 'profile_data',
          type: 'JSONB',
          nullable: true,
          isPrimaryKey: false,
          isAutoIncrement: false,
          isUnique: false,
        },
      ],
    });
    expect(sql[0]).toBe('ALTER TABLE "users" DROP COLUMN "profile_data";');
  });

  it('should generate ALTER TABLE DOWN statements for column alterations', () => {
    const sql = generator.generateAlterTableDown({
      tableName: 'users',
      type: 'alter',
      columnsToAlter: [
        {
          from: {
            name: 'age',
            type: 'INTEGER',
            nullable: true,
            isPrimaryKey: false,
            isAutoIncrement: false,
            isUnique: false,
          },
          to: {
            name: 'age',
            type: 'BIGINT',
            nullable: false,
            isPrimaryKey: false,
            isAutoIncrement: false,
            isUnique: false,
          },
        },
      ],
    });
    expect(sql.length).toBeGreaterThan(0);
    expect(sql[0]).toContain('ALTER TABLE');
    expect(sql[0]).toContain('"age"');
    expect(sql[0]).toContain('INTEGER');
  });

  it('should generate ALTER TABLE DOWN statements for index additions', () => {
    const sql = generator.generateAlterTableDown({
      tableName: 'users',
      type: 'alter',
      indexesToAdd: [{ name: 'idx_users_email', columns: ['email'], unique: true }],
    });
    expect(sql[0]).toBe('DROP INDEX IF EXISTS "idx_users_email";');
  });

  it('should add TODO comment for dropped columns/indexes', () => {
    const sql1 = generator.generateAlterTableDown({
      tableName: 'users',
      type: 'alter',
      columnsToDrop: ['old_column'],
    });
    expect(sql1[0]).toContain('TODO');

    const sql2 = generator.generateAlterTableDown({
      tableName: 'users',
      type: 'alter',
      indexesToDrop: ['idx_old'],
    });
    expect(sql2[0]).toContain('TODO');
  });

  it('should generate ALTER TABLE statements for dropping columns and indexes', () => {
    const sql = generator.generateAlterTable({
      tableName: 'users',
      type: 'alter',
      columnsToDrop: ['old_col'],
      indexesToDrop: ['idx_old'],
      indexesToAdd: [{ name: 'idx_new', columns: ['name'], unique: false }],
    });
    expect(sql).toContain('ALTER TABLE "users" DROP COLUMN "old_col";');
    expect(sql).toContain('DROP INDEX IF EXISTS "idx_old";');
    expect(sql).toContain('CREATE INDEX IF NOT EXISTS "idx_new" ON "users" ("name");');
  });
});

describe('SqlSchemaGenerator (MySQL)', () => {
  const generator = new SqlSchemaGenerator(new MySqlDialect());

  it('should generate CREATE TABLE for simple entity', () => {
    const sql = generator.generateCreateTable(TestUser).join('\n');

    expect(sql).toContain('CREATE TABLE `TestUser`');
    expect(sql).toContain('`id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY');
    expect(sql).toContain('`name` VARCHAR(100)');
    expect(sql).toContain('`email` VARCHAR(255) UNIQUE');
    expect(sql).toContain('ENGINE=InnoDB');
  });

  it('should generate boolean as TINYINT(1)', () => {
    const boolType = generator.getSqlType({ type: Boolean }, Boolean);
    expect(boolType).toBe('TINYINT(1)');
  });

  it('should generate DROP INDEX with ON table', () => {
    const sql = generator.generateDropIndex('users', 'idx_email');
    expect(sql).toBe('DROP INDEX `idx_email` ON `users`;');
  });
});

describe('SqlSchemaGenerator (SQLite)', () => {
  const generator = new SqlSchemaGenerator(new SqliteDialect());

  it('should generate CREATE TABLE for simple entity', () => {
    const sql = generator.generateCreateTable(TestUser).join('\n');

    expect(sql).toContain('CREATE TABLE `TestUser`');
    expect(sql).toContain('`id` INTEGER PRIMARY KEY AUTOINCREMENT');
    expect(sql).toContain('`name` TEXT');
    expect(sql).toContain('`email` TEXT UNIQUE');
  });

  it('should use TEXT for most types (SQLite dynamic typing)', () => {
    expect(generator.getSqlType({ columnType: 'varchar' }, String)).toBe('TEXT');
    expect(generator.getSqlType({ columnType: 'json' }, undefined)).toBe('TEXT');
    expect(generator.getSqlType({ columnType: 'uuid' }, undefined)).toBe('TEXT');
  });

  it('should use INTEGER for numeric types', () => {
    expect(generator.getSqlType({ columnType: 'int' }, undefined)).toBe('INTEGER');
    expect(generator.getSqlType({ columnType: 'bigint' }, undefined)).toBe('INTEGER');
    expect(generator.getSqlType({ type: Boolean }, Boolean)).toBe('INTEGER');
  });

  it('generateCreateTable splits non-inline indexes for separate querier.run', () => {
    const stmts = generator.generateCreateTable(SqliteIndexedEntity);
    expect(stmts).toHaveLength(2);
    expect(stmts[0]).toMatch(/^CREATE TABLE `SqliteIndexedEntity`/);
    expect(stmts[1]).toMatch(/^CREATE INDEX `idx_SqliteIndexedEntity_slug`/);
  });
});

describe('SqlSchemaGenerator Integration', () => {
  const generator = new SqlSchemaGenerator(new PostgresDialect());

  it('should generate CREATE TABLE from TableNode', () => {
    const table = {
      name: 'users',
      columns: new Map<string, ColumnNode>(),
      primaryKey: [],
      indexes: [],
      incomingRelations: [],
      outgoingRelations: [],
    } as unknown as TableNode;
    (table as { columns: Map<string, ColumnNode> }).columns = new Map<string, ColumnNode>([
      [
        'id',
        {
          name: 'id',
          type: { category: 'integer', size: 'big' },
          isPrimaryKey: true,
          isAutoIncrement: true,
          nullable: false,
          table,
        } as ColumnNode,
      ],
      ['name', { name: 'name', type: { category: 'string', length: 100 }, nullable: true, table } as ColumnNode],
    ]);
    (table as { primaryKey: ColumnNode[] }).primaryKey = [table.columns.get('id')!];

    const sql = generator.generateCreateTableFromNode(table).join('\n');
    expect(sql).toContain('CREATE TABLE "users"');
    expect(sql).toContain('"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
    expect(sql).toContain('"name" VARCHAR(100)');
  });

  it('should generate CREATE INDEX from IndexNode', () => {
    const table = { name: 'users' } as TableNode;
    const index: IndexNode = {
      name: 'idx_name',
      table,
      columns: [{ name: 'name' } as ColumnNode],
      unique: true,
    };
    const sql = generator.generateCreateIndexFromNode(index);
    expect(sql).toBe('CREATE UNIQUE INDEX "idx_name" ON "users" ("name");');
  });

  it('should generate DROP TABLE from TableNode', () => {
    const table = { name: 'users' } as TableNode;
    const sql = generator.generateDropTableFromNode(table, { ifExists: true });
    expect(sql).toBe('DROP TABLE IF EXISTS "users";');
  });

  it('should generate DROP TABLE without IF EXISTS by default', () => {
    const table = { name: 'users' } as TableNode;
    expect(generator.generateDropTableFromNode(table)).toBe('DROP TABLE "users";');
  });
});

/**
 * `ColumnSchema` is the shape a diff carries, so these are the columns an `ALTER TABLE ... ADD
 * COLUMN` emits - the qualifiers have to survive the round trip from the diff to the DDL.
 */
describe('SqlSchemaGenerator column definitions from ColumnSchema', () => {
  const generator = new SqlSchemaGenerator(new PostgresDialect());

  /** ADD COLUMN for a single `ColumnSchema`, with only the qualifiers under test overridden. */
  function addColumn(column: Partial<ColumnSchema>, gen = generator): string {
    return gen.generateAlterTable({
      tableName: 'users',
      type: 'alter',
      columnsToAdd: [
        {
          name: 'col',
          type: 'INTEGER',
          nullable: true,
          isPrimaryKey: false,
          isAutoIncrement: false,
          isUnique: false,
          ...column,
        },
      ],
    })[0];
  }

  it('should append precision and scale to a bare type', () => {
    expect(addColumn({ name: 'amount', type: 'NUMERIC', precision: 12, scale: 4 })).toBe(
      'ALTER TABLE "users" ADD COLUMN "amount" NUMERIC(12, 4);',
    );
  });

  it('should append precision alone when there is no scale', () => {
    expect(addColumn({ name: 'amount', type: 'NUMERIC', precision: 12 })).toBe(
      'ALTER TABLE "users" ADD COLUMN "amount" NUMERIC(12);',
    );
  });

  it('should append length when there is no precision', () => {
    expect(addColumn({ name: 'name', type: 'VARCHAR', length: 100 })).toBe(
      'ALTER TABLE "users" ADD COLUMN "name" VARCHAR(100);',
    );
  });

  it('should keep a type that already carries its own parameters', () => {
    expect(addColumn({ name: 'name', type: 'VARCHAR(50)', length: 100, precision: 12, scale: 4 })).toBe(
      'ALTER TABLE "users" ADD COLUMN "name" VARCHAR(50);',
    );
  });

  it('should emit NOT NULL for a non-nullable column', () => {
    expect(addColumn({ nullable: false })).toBe('ALTER TABLE "users" ADD COLUMN "col" INTEGER NOT NULL;');
  });

  it('should emit UNIQUE for a unique column', () => {
    expect(addColumn({ isUnique: true })).toBe('ALTER TABLE "users" ADD COLUMN "col" INTEGER UNIQUE;');
  });

  /** A primary key is already NOT NULL and UNIQUE; repeating either is redundant DDL. */
  it('should emit PRIMARY KEY alone for a non-nullable unique primary key', () => {
    expect(addColumn({ nullable: false, isUnique: true, isPrimaryKey: true })).toBe(
      'ALTER TABLE "users" ADD COLUMN "col" INTEGER PRIMARY KEY;',
    );
  });

  it('should not duplicate a PRIMARY KEY already present in the type', () => {
    expect(addColumn({ type: 'SERIAL PRIMARY KEY', isPrimaryKey: true })).toBe(
      'ALTER TABLE "users" ADD COLUMN "col" SERIAL PRIMARY KEY;',
    );
  });

  it('should quote a string default and escape its quotes', () => {
    expect(addColumn({ type: 'TEXT', defaultValue: "it's" })).toBe(
      `ALTER TABLE "users" ADD COLUMN "col" TEXT DEFAULT 'it''s';`,
    );
  });

  it('should emit a NULL default distinctly from no default', () => {
    expect(addColumn({ defaultValue: null })).toBe('ALTER TABLE "users" ADD COLUMN "col" INTEGER DEFAULT NULL;');
  });

  it('should emit a native boolean default on Postgres', () => {
    expect(addColumn({ type: 'BOOLEAN', defaultValue: false })).toBe(
      'ALTER TABLE "users" ADD COLUMN "col" BOOLEAN DEFAULT FALSE;',
    );
  });

  /** SQLite/MySQL have no boolean literal, so the default has to bind as 0/1. */
  it('should emit an integer boolean default where booleans are integers', () => {
    const sqliteGenerator = new SqlSchemaGenerator(new SqliteDialect());
    expect(addColumn({ type: 'INTEGER', defaultValue: true }, sqliteGenerator)).toBe(
      'ALTER TABLE `users` ADD COLUMN `col` INTEGER DEFAULT 1;',
    );
    expect(addColumn({ type: 'INTEGER', defaultValue: false }, sqliteGenerator)).toBe(
      'ALTER TABLE `users` ADD COLUMN `col` INTEGER DEFAULT 0;',
    );
  });

  it('should emit a column comment where the dialect supports one', () => {
    const mysqlGenerator = new SqlSchemaGenerator(new MySqlDialect());
    expect(addColumn({ comment: "the user's age", nullable: false }, mysqlGenerator)).toBe(
      "ALTER TABLE `users` ADD COLUMN `col` INTEGER NOT NULL COMMENT 'the user''s age';",
    );
  });

  it('should drop a column comment where the dialect has none', () => {
    expect(addColumn({ comment: 'the age' })).toBe('ALTER TABLE "users" ADD COLUMN "col" INTEGER;');
  });

  /**
   * The reverse of an alteration restores the previous column, and re-declaring its PRIMARY KEY
   * there would be rejected as a duplicate constraint.
   */
  it('should strip PRIMARY KEY when restoring a column in the down direction', () => {
    const sql = new SqlSchemaGenerator(new MySqlDialect()).generateAlterTableDown({
      tableName: 'users',
      type: 'alter',
      columnsToAlter: [
        {
          from: {
            name: 'id',
            type: 'BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY',
            nullable: false,
            isPrimaryKey: true,
            isAutoIncrement: true,
            isUnique: false,
          },
          to: {
            name: 'id',
            type: 'BIGINT UNSIGNED',
            nullable: false,
            isPrimaryKey: false,
            isAutoIncrement: false,
            isUnique: false,
          },
        },
      ],
    });
    expect(sql).toEqual(['ALTER TABLE `users` MODIFY COLUMN `id` BIGINT UNSIGNED AUTO_INCREMENT;']);
  });
});

describe('SqlSchemaGenerator table definitions from the migration builder', () => {
  const generator = new SqlSchemaGenerator(new PostgresDialect());

  /** A `TableDefinition` for two columns, with the parts under test overridden. */
  function tableDefinition(overrides: Partial<TableDefinition> = {}): TableDefinition {
    return {
      name: 'memberships',
      columns: [
        column({ name: 'userId' }),
        column({
          name: 'groupId',
          foreignKey: { table: 'groups', columns: ['id'], onDelete: 'CASCADE', onUpdate: 'NO ACTION' },
        }),
      ],
      indexes: [],
      foreignKeys: [],
      ...overrides,
    };
  }

  function column(overrides: Partial<FullColumnDefinition>): FullColumnDefinition {
    return {
      name: 'col',
      type: { category: 'integer' },
      nullable: false,
      primaryKey: false,
      autoIncrement: false,
      unique: false,
      ...overrides,
    };
  }

  it('should generate a composite PRIMARY KEY from the declared key columns', () => {
    const sql = generator
      .generateCreateTableFromDefinition(tableDefinition({ primaryKey: ['userId', 'groupId'] }))
      .join('\n');
    expect(sql).toContain('PRIMARY KEY ("userId", "groupId")');
  });

  it('should ignore a declared key column that no column definition matches', () => {
    const sql = generator
      .generateCreateTableFromDefinition(tableDefinition({ primaryKey: ['userId', 'nope', 'groupId'] }))
      .join('\n');
    expect(sql).toContain('PRIMARY KEY ("userId", "groupId")');
    expect(sql).not.toContain('nope');
  });

  it('should fall back to the columns flagged as primary when no key is declared', () => {
    const definition = tableDefinition();
    definition.columns[0] = column({ name: 'userId', primaryKey: true, autoIncrement: true });
    const sql = generator.generateCreateTableFromDefinition(definition).join('\n');
    expect(sql).toContain('"userId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
  });

  it('should generate the declared indexes as separate statements', () => {
    const statements = generator.generateCreateTableFromDefinition(
      tableDefinition({
        indexes: [
          { name: 'idx_memberships_userId', columns: ['userId'], unique: false },
          { name: 'uq_memberships_pair', columns: ['userId', 'groupId'], unique: true },
        ],
      }),
    );
    expect(statements).toHaveLength(3);
    expect(statements[1]).toBe('CREATE INDEX "idx_memberships_userId" ON "memberships" ("userId");');
    expect(statements[2]).toBe('CREATE UNIQUE INDEX "uq_memberships_pair" ON "memberships" ("userId", "groupId");');
  });

  it('should generate a table-level FOREIGN KEY with its declared actions', () => {
    const sql = generator
      .generateCreateTableFromDefinition(
        tableDefinition({
          foreignKeys: [
            {
              name: 'fk_memberships_user',
              columns: ['userId'],
              referencesTable: 'users',
              referencesColumns: ['id'],
              onDelete: 'CASCADE',
              onUpdate: 'NO ACTION',
            },
          ],
        }),
      )
      .join('\n');
    expect(sql).toContain(
      'CONSTRAINT "fk_memberships_user" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION',
    );
  });

  it('should name an unnamed table-level FOREIGN KEY after its table and columns', () => {
    const sql = generator
      .generateCreateTableFromDefinition(
        tableDefinition({
          foreignKeys: [
            {
              columns: ['userId'],
              referencesTable: 'users',
              referencesColumns: ['id'],
              onDelete: 'NO ACTION',
              onUpdate: 'NO ACTION',
            },
          ],
        }),
      )
      .join('\n');
    expect(sql).toContain('CONSTRAINT "fk_memberships_userId" FOREIGN KEY ("userId")');
  });

  it('should generate ADD CONSTRAINT for a foreign key added to an existing table', () => {
    const sql = generator.generateAddForeignKeySql('memberships', {
      columns: ['groupId'],
      referencesTable: 'groups',
      referencesColumns: ['id'],
      onDelete: 'SET NULL',
      onUpdate: 'CASCADE',
    });
    expect(sql).toBe(
      'ALTER TABLE "memberships" ADD CONSTRAINT "fk_memberships_groupId" ' +
        'FOREIGN KEY ("groupId") REFERENCES "groups" ("id") ON DELETE SET NULL ON UPDATE CASCADE;',
    );
  });

  /** SQLite cannot add a constraint to an existing table, so this has to fail rather than emit invalid DDL. */
  it('should reject adding a foreign key where the dialect cannot alter constraints', () => {
    const sqliteGenerator = new SqlSchemaGenerator(new SqliteDialect());
    expect(() =>
      sqliteGenerator.generateAddForeignKeySql('memberships', {
        columns: ['groupId'],
        referencesTable: 'groups',
        referencesColumns: ['id'],
        onDelete: 'NO ACTION',
        onUpdate: 'NO ACTION',
      }),
    ).toThrow('does not support adding foreign keys to existing tables');
  });

  it('should rename a table with the dialect syntax', () => {
    expect(generator.generateRenameTableSql('old', 'new')).toBe('ALTER TABLE "old" RENAME TO "new";');
    expect(new SqlSchemaGenerator(new MySqlDialect()).generateRenameTableSql('old', 'new')).toBe(
      'RENAME TABLE `old` TO `new`;',
    );
  });
});
