import { describe, expect, it } from 'vitest';
import { CockroachDialect } from '../cockroachdb/cockroachDialect.js';
import { MariaDialect, MySqlDialect, PostgresDialect, SqliteDialect } from '../dialect/index.js';
import { Entity, Field, Id } from '../entity/index.js';
import { SqlSchemaGenerator } from './schemaGenerator.js';

@Entity({ name: 'users' })
class User {
  @Id() id?: number;
  @Field() name?: string;
}

// One row per dialect instead of an `if (dialectName === ...)` ladder inside each test body: the
// expectations are the point of the table, and a new dialect is a row rather than another branch.
const dialects = [
  {
    dialect: new PostgresDialect(),
    serialId: 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
    tableOptions: '',
    booleanType: 'BOOLEAN',
    comment: '',
  },
  {
    dialect: new CockroachDialect(),
    serialId: 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
    tableOptions: '',
    booleanType: 'BOOLEAN',
    comment: '',
  },
  {
    dialect: new MySqlDialect(),
    serialId: 'BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY',
    tableOptions: 'ENGINE=InnoDB',
    booleanType: 'TINYINT(1)',
    comment: " COMMENT 'Testing'",
  },
  {
    dialect: new MariaDialect(),
    serialId: 'BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY',
    tableOptions: 'ENGINE=InnoDB',
    booleanType: 'TINYINT(1)',
    comment: " COMMENT 'Testing'",
  },
  {
    dialect: new SqliteDialect(),
    serialId: 'INTEGER PRIMARY KEY AUTOINCREMENT',
    tableOptions: '',
    booleanType: 'INTEGER',
    comment: '',
  },
];

describe('SqlSchemaGenerator (unified)', () => {
  describe.each(dialects)(
    'Dialect: $dialect.dialectName',
    ({ dialect, serialId, tableOptions, booleanType, comment }) => {
      const generator = new SqlSchemaGenerator(dialect);

      it('should generate correct CREATE TABLE SQL', () => {
        const sql = generator.generateCreateTable(User).join('\n');

        expect(sql).toContain('CREATE TABLE');
        expect(sql).toContain('users');
        expect(sql).toContain('name');
        expect(sql).toContain(serialId);
        expect(sql).toContain(tableOptions);
      });

      it('should generate correct DROP TABLE SQL', () => {
        expect(generator.generateDropTable('users', { ifExists: true })).toContain('DROP TABLE IF EXISTS');
        expect(generator.generateDropTable('users', { ifExists: true })).toContain('users');
      });

      it('should generate correct SQL type for Boolean', () => {
        expect(generator.getSqlType({ type: Boolean })).toBe(booleanType);
      });

      it('should generate correct column comments', () => {
        expect(generator.generateColumnComment('col', 'Testing')).toBe(comment);
      });
    },
  );
});
