import { expect, it } from 'vitest';
import { defineEntity } from '../../entity/index.js';
import { entityTypesSource } from './entityTypes.js';

it('writes an interface per registered entity, relations included', () => {
  class Author {
    id?: number;
    name?: string;
    posts?: Post[];
  }
  class Post {
    id?: number;
    title?: string;
    publishedAt?: Date;
    authorId?: number;
    author?: Author;
  }
  defineEntity(Author, {
    fields: { id: { type: Number, isId: true }, name: { type: String } },
    relations: { posts: { cardinality: '1m', entity: () => Post, mappedBy: 'author' } },
  });
  defineEntity(Post, {
    fields: {
      id: { type: Number, isId: true },
      title: { type: String },
      publishedAt: { type: Date },
      authorId: { references: () => Author },
    },
    relations: { author: { cardinality: 'm1', entity: () => Author } },
  });

  expect(entityTypesSource([Author, Post])).toBe(
    [
      '// Generated by `uql-migrate types`. Do not edit.',
      '',
      'export interface Author {',
      '  id?: number;',
      '  name?: string;',
      '  posts?: Post[];',
      '}',
      'export interface Post {',
      '  id?: number;',
      '  title?: string;',
      '  publishedAt?: Date;',
      '  authorId?: number;',
      '  author?: Author;',
      '}',
      '',
    ].join('\n'),
  );
});

it('emits names a generated file can carry, whatever a content type was called', () => {
  const Outside = { outside: class {} }.outside;
  defineEntity(Outside, { fields: { id: { type: Number, isId: true } } });

  // A slug carries what an identifier cannot, and two of them collide once that is stripped.
  const dashed = { 'blog-post': class {} }['blog-post'];
  defineEntity(dashed, {
    fields: {
      id: { type: Number, isId: true },
      'hero-image': { type: String },
      outsideId: { references: () => Outside },
    },
    relations: { outside: { cardinality: 'm1', entity: () => Outside } },
  });
  const collides = { blogpost: class {} }.blogpost;
  defineEntity(collides, { fields: { id: { type: Number, isId: true } } });
  // A slug can also start with what an identifier cannot.
  const numeric = { '2fa': class {} }['2fa'];
  defineEntity(numeric, { fields: { id: { type: Number, isId: true } } });

  expect(entityTypesSource([numeric])).toContain('export interface Entity2fa {');
  const source = entityTypesSource([dashed, collides]);
  expect(source).toContain('export interface Blogpost {');
  expect(source).toContain('export interface Blogpost2 {');
  expect(source).toContain('  "hero-image"?: string;');
  // The relation's target is outside the set, so naming its interface would not compile.
  expect(source).toContain('  outside?: unknown;');
  expect(entityTypesSource([dashed, Outside])).toContain('  outside?: Outside;');
});
