import { transform } from 'esbuild';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { PgQuerierPool } from '../../postgres/pgQuerierPool.js';
import { PostgresSchemaIntrospector } from '../introspection/postgresIntrospector.js';
import { EntityCodeGenerator } from './entityCodeGenerator.js';

const TABLE = 'codegen_from_db';

/**
 * `generate:from-db` against a real catalogue, which is the only way this is worth testing: every
 * fixture-built `IndexNode` in the unit specs is one someone wrote by hand, and three bugs lived in
 * exactly the gap between those and what Postgres actually reports - an expression clipped to 63
 * characters, a reprint whose newlines broke the string literal it was written into, and an access
 * method reported on every index, which stopped any of them being written on the field.
 */
describe('generate:from-db (PostgreSQL)', () => {
  const pool = new PgQuerierPool({ host: '0.0.0.0', port: 5442, user: 'test', password: 'test', database: 'test' });
  let code: string;

  beforeAll(async () => {
    await pool.withQuerier(async (querier) => {
      await querier.run(`DROP TABLE IF EXISTS "${TABLE}"`);
      await querier.run(
        `CREATE TABLE "${TABLE}" (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
           email TEXT, name TEXT, status TEXT, "tenantId" BIGINT, is_enabled BOOLEAN, "deletedAt" TIMESTAMPTZ)`,
      );
      await querier.run(`CREATE INDEX cfd_plain ON "${TABLE}" (status)`);
      await querier.run(`CREATE UNIQUE INDEX cfd_unique ON "${TABLE}" ("tenantId")`);
      await querier.run(`CREATE INDEX cfd_expr ON "${TABLE}" ((to_tsvector('english', name || ' ' || status)))`);
      await querier.run(`CREATE INDEX cfd_partial ON "${TABLE}" (email) WHERE "deletedAt" IS NULL`);
      await querier.run(`CREATE INDEX cfd_covering ON "${TABLE}" ("tenantId") INCLUDE (status)`);
    });

    const ast = await new PostgresSchemaIntrospector(pool).introspect();
    code = new EntityCodeGenerator(ast).generateForTable(TABLE)!.code;
  });

  afterAll(async () => {
    await pool.withQuerier((querier) => querier.run(`DROP TABLE IF EXISTS "${TABLE}"`));
    await pool.end();
  });

  it('should generate source that parses as TypeScript', async () => {
    await expect(transform(code, { loader: 'ts' })).resolves.toBeDefined();
  });

  it('should carry a plain index on the field and everything else in its own decorator', () => {
    expect(code).toContain("index: 'cfd_plain'");
    expect(code).toContain("{ name: 'cfd_unique', unique: true }");
  });

  // `btree` is reported on every index Postgres has, so writing it would put it in every entity.
  it('should leave the default access method out', () => {
    expect(code).not.toContain('btree');
  });

  it('should write the expression whole, however long the catalogue prints it', () => {
    expect(code).toContain(
      `@Index([raw(${JSON.stringify("to_tsvector('english'::regconfig, (name || ' '::text) || status)")})], { name: 'cfd_expr' })`,
    );
  });

  /**
   * A property the transformer had to rewrite maps to a column the database does not have unless the
   * decorator says which one it is, and a column that is already camelCase must not be rewritten at all.
   */
  it('should name the column wherever the property cannot', () => {
    expect(code).toContain("@Field({ name: 'is_enabled'");
    expect(code).toContain('isEnabled?: boolean;');
    expect(code).toContain('tenantId?: number;');
    expect(code).not.toContain('tenantid');
    expect(code).not.toContain("name: 'tenantId'");
  });

  it('should write a partial predicate and a covering list', () => {
    expect(code).toContain(`where: ${JSON.stringify('"deletedAt" IS NULL')}`);
    expect(code).toContain("{ name: 'cfd_covering', include: ['status'] }");
  });
});
