import type {
  DialectFeatures,
  DialectName,
  EntityMeta,
  ExtraOptions,
  FieldKey,
  FieldOptions,
  InsertIdSource,
  NamingStrategy,
  QueryOptions,
  QueryWhere,
  QueryWhereMap,
} from '../type/index.js';
import { applyFilters, buildQueryWhereAsMap } from '../util/dialect.util.js';
import { qualifyName } from '../util/sql.util.js';

/**
 * Options for initializing a dialect.
 */
export interface DialectOptions {
  readonly namingStrategy?: NamingStrategy;
  /** Default schema for entities naming none; unset leaves them unqualified. See {@link AbstractDialect.resolveSchema}. */
  readonly schema?: string;
  readonly driverCapabilities?: Partial<DialectFeatures>;
}

/**
 * The dialect's share of a pool's {@link ExtraOptions}: what changes the SQL rather than the
 * connection. Every pool builds its dialect through this, so a new option lands here instead of in
 * each of the thirteen constructors.
 */
export function dialectOptionsFrom(extra: ExtraOptions | undefined): DialectOptions {
  return { namingStrategy: extra?.namingStrategy, schema: extra?.schema };
}

/**
 * Base abstract class for all database dialects (SQL and NoSQL).
 */
export abstract class AbstractDialect {
  abstract readonly dialectName: DialectName;

  /** How this dialect surfaces the IDs generated by an INSERT (see {@link InsertIdSource}). */
  abstract readonly insertIdSource: InsertIdSource;

  /**
   * Engine/driver feature defaults for this dialect, before per-instance
   * {@link DialectOptions.driverCapabilities} overrides. Each concrete dialect declares its own.
   */
  protected abstract readonly featureDefaults: DialectFeatures;

  /**
   * How this dialect differs from the family it extends, so a subclass states only its deltas rather
   * than repeating {@link featureDefaults} in full or injecting them through its constructor.
   */
  protected readonly featureOverrides: Partial<DialectFeatures> = {};

  readonly namingStrategy: NamingStrategy | undefined;
  #features?: DialectFeatures;

  constructor(protected readonly options: DialectOptions = {}) {
    this.namingStrategy = options.namingStrategy;
  }

  /**
   * Effective features: {@link featureDefaults}, then this dialect's {@link featureOverrides}, then
   * any per-instance {@link DialectOptions.driverCapabilities}. Computed lazily (and memoized)
   * because both are subclass fields, initialized only after `super()` returns.
   */
  get features(): DialectFeatures {
    this.#features ??= { ...this.featureDefaults, ...this.featureOverrides, ...this.options.driverCapabilities };
    return this.#features;
  }

  /**
   * The table's own name, unqualified, applying naming strategy if necessary. Also the alias the
   * root table gets once {@link resolveTableName} qualifies it, so it has to stay a single
   * identifier: columns are prefixed with it, and a dotted prefix escapes as one identifier that
   * nothing declared.
   */
  resolveTableAlias<E>(meta: EntityMeta<E>): string {
    const className = meta.entity.name;
    const name = meta.name ?? className;
    if (name !== className || !this.namingStrategy) {
      return name;
    }
    return this.namingStrategy.tableName(name);
  }

  /**
   * Where the table lives: {@link resolveTableAlias} behind its schema, when one applies. The schema
   * skips the naming strategy - it names an object the author wrote out, and snake_casing `myCrm`
   * would point at one that does not exist.
   */
  resolveTableName<E>(meta: EntityMeta<E>): string {
    return qualifyName(this.resolveTableAlias(meta), this.resolveSchema(meta));
  }

  /**
   * Which schema an entity is read from: its own wins over the pool's default, the way its `name`
   * wins over the naming strategy. `undefined` is an answer, not a gap - the table stays unqualified
   * and resolves through the connection's `search_path`, which is what every deployment predating
   * this option relies on.
   */
  resolveSchema<E>(meta: EntityMeta<E>): string | undefined {
    return this.features.schemas ? (meta.schema ?? this.options.schema) : undefined;
  }

  /**
   * Resolve the column/field name for a property, applying naming strategy if necessary.
   */
  resolveColumnName(key: string, field: FieldOptions | undefined): string {
    if (!field || field.name !== key || !this.namingStrategy) {
      return field?.name ?? key;
    }
    return this.namingStrategy.columnName(field.name);
  }

  /**
   * {@link resolveColumnName} for a field key of `meta` - the form query builders need, so reading a
   * column never depends on looking the field up by hand first. `MongoDialect` overrides it to map the
   * primary key to `_id`.
   */
  columnOf<E>(meta: EntityMeta<E>, key: string): string {
    return this.resolveColumnName(key, meta.fields[key as FieldKey<E>]);
  }

  /**
   * A `$where` normalized to a map with the entity's active filters merged in - the only way any
   * dialect should enter a new query scope, so a scope cannot be rendered with its `security: true`
   * filters skipped. Recursion within one scope renders the returned map directly instead.
   */
  protected scopedWhereMap<E>(meta: EntityMeta<E>, where: QueryWhere<E> = {}, opts?: QueryOptions): QueryWhereMap<E> {
    return applyFilters(meta, buildQueryWhereAsMap(meta, where), opts);
  }
}
