import type {
  DialectFeatures,
  DialectName,
  EntityMeta,
  FieldOptions,
  InsertIdSource,
  NamingStrategy,
  Type,
} from '../type/index.js';

/**
 * Options for initializing a dialect.
 */
export interface DialectOptions {
  readonly namingStrategy?: NamingStrategy;
  readonly driverCapabilities?: Partial<DialectFeatures>;
}

/**
 * Base abstract class for all database dialects (SQL and NoSQL).
 */
export abstract class AbstractDialect {
  abstract readonly dialectName: DialectName;

  /** How this dialect surfaces the IDs generated by an INSERT (see {@link InsertIdSource}). */
  abstract readonly insertIdSource: InsertIdSource;

  /**
   * Engine/driver feature defaults for this dialect, before per-instance
   * {@link DialectOptions.driverCapabilities} overrides. Each concrete dialect declares its own.
   */
  protected abstract readonly featureDefaults: DialectFeatures;

  readonly namingStrategy: NamingStrategy | undefined;
  #features?: DialectFeatures;

  constructor(protected readonly options: DialectOptions = {}) {
    this.namingStrategy = options.namingStrategy;
  }

  /**
   * Effective features: {@link featureDefaults} merged with any {@link DialectOptions.driverCapabilities}.
   * Computed lazily (and memoized) because `featureDefaults` is a subclass field, initialized only
   * after `super()` returns.
   */
  get features(): DialectFeatures {
    this.#features ??= { ...this.featureDefaults, ...this.options.driverCapabilities };
    return this.#features;
  }

  /**
   * Resolve the table name for an entity, applying naming strategy if necessary.
   */
  resolveTableName<E>(entity: Type<E>, meta: EntityMeta<E>): string {
    const name = meta.name ?? entity.name;
    if (name !== entity.name || !this.namingStrategy) {
      return name;
    }
    return this.namingStrategy.tableName(name);
  }

  /**
   * Resolve the column/field name for a property, applying naming strategy if necessary.
   */
  resolveColumnName(key: string, field: FieldOptions | undefined): string {
    if (!field || field.name !== key || !this.namingStrategy) {
      return field?.name ?? key;
    }
    return this.namingStrategy.columnName(field.name);
  }
}
