import type { Dialect, VectorDistance } from '../type/index.js';

export type IsolationLevelStrategy = 'inline' | 'set-before' | 'none';
export type InsertIdStrategy = 'first' | 'last';
export type VectorIndexStyle = 'inline' | 'create';
export type QuoteChar = '"' | '`';
export type AlterColumnSyntax = 'ALTER COLUMN' | 'MODIFY COLUMN' | 'none';
export type DropForeignKeySyntax = 'DROP CONSTRAINT' | 'DROP FOREIGN KEY';
export type DropIndexSyntax = 'on-table' | 'standalone';
export type RenameTableSyntax = 'rename-table' | 'alter-table';
export type BooleanLiteral = 'native' | 'integer';
export type AlterColumnStrategy = 'separate-clauses' | 'single-statement';

export interface DialectFeatures {
  returning: boolean;
  ifNotExists: boolean;
  indexIfNotExists: boolean;
  dropTableCascade: boolean;
  renameColumn: boolean;
  foreignKeyAlter: boolean;
  /** Whether the dialect supports inline COMMENT on columns (MySQL/MariaDB). */
  columnComment: boolean;
  /** How vector indexes are emitted: inline in CREATE TABLE or as standalone CREATE INDEX. */
  vectorIndexStyle: VectorIndexStyle;
  /** Whether the dialect requires/allows (n) length constraints on vector types. */
  vectorSupportsLength: boolean;
  /** Whether the dialect natively supports the TIMESTAMPTZ alias/type. */
  supportsTimestamptz: boolean;
  /** Whether the dialect defaults to TEXT for strings when no length is specified (e.g. Postgres). */
  defaultStringAsText: boolean;
}

export interface DialectConfig {
  quoteChar: QuoteChar;
  serialPrimaryKey: string;
  tableOptions: string;
  alterColumnSyntax: AlterColumnSyntax;
  dropForeignKeySyntax: DropForeignKeySyntax;
  beginTransactionCommand: string;
  commitTransactionCommand: string;
  rollbackTransactionCommand: string;
  isolationLevelStrategy: IsolationLevelStrategy;
  /** How DROP INDEX is emitted: `'on-table'` = `DROP INDEX x ON t`, `'standalone'` = `DROP INDEX IF EXISTS x`. */
  dropIndexSyntax: DropIndexSyntax;
  /** How RENAME TABLE is emitted: `'rename-table'` = `RENAME TABLE`, `'alter-table'` = `ALTER TABLE RENAME TO`. */
  renameTableSyntax: RenameTableSyntax;
  /** How boolean literals are formatted: `'native'` = true/false, `'integer'` = 1/0. */
  booleanLiteral: BooleanLiteral;
  /** How ALTER COLUMN is structured: `'separate-clauses'` = Postgres multi-statement, `'single-statement'` = MySQL/MariaDB MODIFY. */
  alterColumnStrategy: AlterColumnStrategy;
  /** Operator class map for pgvector indexes. Only set for Postgres. */
  vectorOpsClass?: Readonly<Record<VectorDistance, string>>;
  /** Extension name required for vector support (e.g. 'vector' for pgvector). */
  vectorExtension?: string;
  /** Strategy for resolving the auto-generated ID from an INSERT operation: 'first' (MySQL/MariaDB) or 'last' (SQLite/others). */
  insertIdStrategy: InsertIdStrategy;
  features: DialectFeatures;
}

const PG_VECTOR_OPS_CLASS: Readonly<Record<VectorDistance, string>> = {
  cosine: 'vector_cosine_ops',
  l2: 'vector_l2_ops',
  inner: 'vector_ip_ops',
  l1: 'vector_l1_ops',
  hamming: 'bit_hamming_ops',
};

export const DIALECT_CONFIG: Record<Dialect, DialectConfig> = {
  postgres: {
    quoteChar: '"',
    serialPrimaryKey: 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
    tableOptions: '',
    beginTransactionCommand: 'BEGIN TRANSACTION',
    commitTransactionCommand: 'COMMIT',
    rollbackTransactionCommand: 'ROLLBACK',
    isolationLevelStrategy: 'inline',
    alterColumnSyntax: 'ALTER COLUMN',
    dropForeignKeySyntax: 'DROP CONSTRAINT',
    dropIndexSyntax: 'standalone',
    renameTableSyntax: 'alter-table',
    booleanLiteral: 'native',
    alterColumnStrategy: 'separate-clauses',
    insertIdStrategy: 'last',
    vectorOpsClass: PG_VECTOR_OPS_CLASS,
    vectorExtension: 'vector',
    features: {
      returning: true,
      ifNotExists: true,
      indexIfNotExists: true,
      dropTableCascade: true,
      renameColumn: true,
      foreignKeyAlter: true,
      columnComment: false,
      vectorIndexStyle: 'create',
      vectorSupportsLength: true,
      supportsTimestamptz: true,
      defaultStringAsText: true,
    },
  },
  cockroachdb: {
    quoteChar: '"',
    serialPrimaryKey: 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
    tableOptions: '',
    beginTransactionCommand: 'BEGIN TRANSACTION',
    commitTransactionCommand: 'COMMIT',
    rollbackTransactionCommand: 'ROLLBACK',
    isolationLevelStrategy: 'inline',
    alterColumnSyntax: 'ALTER COLUMN',
    dropForeignKeySyntax: 'DROP CONSTRAINT',
    dropIndexSyntax: 'standalone',
    renameTableSyntax: 'alter-table',
    booleanLiteral: 'native',
    alterColumnStrategy: 'separate-clauses',
    insertIdStrategy: 'last',
    vectorOpsClass: PG_VECTOR_OPS_CLASS,
    // CockroachDB 24.2+ has built-in pgvector support — no CREATE EXTENSION needed.
    features: {
      returning: true,
      ifNotExists: true,
      indexIfNotExists: true,
      dropTableCascade: true,
      renameColumn: true,
      foreignKeyAlter: true,
      columnComment: false,
      vectorIndexStyle: 'create',
      vectorSupportsLength: true,
      supportsTimestamptz: true,
      defaultStringAsText: true,
    },
  },
  mysql: {
    quoteChar: '`',
    serialPrimaryKey: 'BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY',
    tableOptions: 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
    beginTransactionCommand: 'START TRANSACTION',
    commitTransactionCommand: 'COMMIT',
    rollbackTransactionCommand: 'ROLLBACK',
    isolationLevelStrategy: 'set-before',
    alterColumnSyntax: 'MODIFY COLUMN',
    dropForeignKeySyntax: 'DROP FOREIGN KEY',
    dropIndexSyntax: 'on-table',
    renameTableSyntax: 'rename-table',
    booleanLiteral: 'native',
    alterColumnStrategy: 'single-statement',
    insertIdStrategy: 'first',
    features: {
      returning: false,
      ifNotExists: true,
      indexIfNotExists: false,
      dropTableCascade: false,
      renameColumn: true,
      foreignKeyAlter: true,
      columnComment: true,
      vectorIndexStyle: 'create',
      vectorSupportsLength: false,
      supportsTimestamptz: false,
      defaultStringAsText: false,
    },
  },
  mariadb: {
    quoteChar: '`',
    serialPrimaryKey: 'BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY',
    tableOptions: 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
    beginTransactionCommand: 'START TRANSACTION',
    commitTransactionCommand: 'COMMIT',
    rollbackTransactionCommand: 'ROLLBACK',
    isolationLevelStrategy: 'set-before',
    alterColumnSyntax: 'MODIFY COLUMN',
    dropForeignKeySyntax: 'DROP FOREIGN KEY',
    dropIndexSyntax: 'on-table',
    renameTableSyntax: 'rename-table',
    booleanLiteral: 'native',
    alterColumnStrategy: 'single-statement',
    insertIdStrategy: 'first',
    features: {
      returning: true,
      ifNotExists: true,
      indexIfNotExists: false,
      dropTableCascade: false,
      renameColumn: true,
      foreignKeyAlter: true,
      columnComment: true,
      vectorIndexStyle: 'inline',
      vectorSupportsLength: true,
      supportsTimestamptz: false,
      defaultStringAsText: false,
    },
  },
  sqlite: {
    quoteChar: '`',
    serialPrimaryKey: 'INTEGER PRIMARY KEY AUTOINCREMENT',
    tableOptions: '',
    beginTransactionCommand: 'BEGIN TRANSACTION',
    commitTransactionCommand: 'COMMIT',
    rollbackTransactionCommand: 'ROLLBACK',
    isolationLevelStrategy: 'none',
    alterColumnSyntax: 'none',
    dropForeignKeySyntax: 'DROP CONSTRAINT',
    dropIndexSyntax: 'standalone',
    renameTableSyntax: 'alter-table',
    booleanLiteral: 'integer',
    alterColumnStrategy: 'single-statement',
    insertIdStrategy: 'last',
    features: {
      returning: true,
      ifNotExists: true,
      indexIfNotExists: false,
      dropTableCascade: false,
      renameColumn: true,
      foreignKeyAlter: false,
      columnComment: false,
      vectorIndexStyle: 'create', // Doesn't matter, sqlite has no vector native type
      vectorSupportsLength: false,
      supportsTimestamptz: false,
      defaultStringAsText: false, // SQLite falls back to generic TEXT explicitly elsewhere
    },
  },
  mongodb: {
    quoteChar: '"',
    serialPrimaryKey: '',
    tableOptions: '',
    beginTransactionCommand: '',
    commitTransactionCommand: '',
    rollbackTransactionCommand: '',
    isolationLevelStrategy: 'none',
    alterColumnSyntax: 'none',
    dropForeignKeySyntax: 'DROP CONSTRAINT',
    dropIndexSyntax: 'standalone',
    renameTableSyntax: 'alter-table',
    booleanLiteral: 'native',
    alterColumnStrategy: 'single-statement',
    insertIdStrategy: 'last',
    features: {
      returning: false,
      ifNotExists: false,
      indexIfNotExists: false,
      dropTableCascade: false,
      renameColumn: false,
      foreignKeyAlter: false,
      columnComment: false,
      vectorIndexStyle: 'create',
      vectorSupportsLength: false,
      supportsTimestamptz: false,
      defaultStringAsText: false,
    },
  },
};

export function getDialectConfig(dialect: Dialect): DialectConfig {
  return DIALECT_CONFIG[dialect];
}
