import type { IndexType } from '../schema/types.js';
import {
  type DialectFeatures,
  type EntityMeta,
  type FieldOptions,
  type JsonColumnType,
  type Query,
  type QueryContext,
  QueryRaw,
  type QuerySizeComparisonOps,
  type QueryTextSearchOptions,
  type Type,
} from '../type/index.js';
import { hasVectorNear, textSearchFields } from '../util/dialect.util.js';
import { escapeSingleQuotes } from '../util/sqlLiteral.js';
import { AbstractSqlDialect, type CarriedFields, type RelationRows } from './abstractSqlDialect.js';
import { JSON_PULL_ALIAS, RELATION_ROW_ALIAS } from './aliases.js';
import { BYTES_PREFIX } from './hydrateColumn.js';
import { jsonSetTarget } from './jsonSql.js';
import { PG_VECTOR_METRICS } from './pgVectorMetrics.js';
import { resolveVectorCast, toSparsevecLiteral } from './vectorCast.js';

/**
 * Shared AST/quoting/JSONB/full-text-search/vector-search implementation between Postgres and
 * CockroachDB (wire- and SQL-compatible for everything below, including `TO_TSVECTOR`/`TO_TSQUERY`
 * and pgvector's `<=>`/`<->`/`<#>` distance operators, which CockroachDB implements natively).
 * `xmax`-based upsert `created` detection is Postgres-only (CockroachDB has no `xmax`/`ctid`) and
 * stays in {@link PostgresDialect}, along with the `vectorExtension`/`vectorIndexStyle` values that
 * differ (Postgres needs `CREATE EXTENSION vector` and pgvector's `USING ivfflat/hnsw` index
 * syntax; CockroachDB's vector type and `CREATE VECTOR INDEX` syntax are both native).
 */
export abstract class PgLikeSqlDialect extends AbstractSqlDialect {
  /** `FOR UPDATE` and a window function cannot share a statement here. See the base declaration. */
  override readonly supportsWindowWithRowLock = false;

  /** Default {@link DialectFeatures} for Postgres-wire dialects. */
  protected override readonly featureDefaults: DialectFeatures = {
    explicitJsonCast: false,
    nativeArrays: true,
    supportsJsonb: true,
    ifNotExists: true,
    indexIfNotExists: true,
    schemas: true,
    dropTableCascade: true,
    foreignKeyAlter: true,
    primaryKeyAlter: true,
    generatedColumnAdd: true,
    commentSyntax: 'statement',
    vectorIndexRequiresNotNull: false,
    vectorSupportsLength: true,
    supportsTimestamptz: true,
    stringSizing: 'bounded-text',
    supportsUnsigned: false,
    serverSideCursors: true,
  };

  override readonly escapeIdChar = '"';
  // Shared default for both dialects. CockroachDB docs flag sequential PKs as a hotspotting risk
  // under heavy concurrent insert load (writes concentrate on one range); this default still beats
  // `SERIAL` (CockroachDB's `unique_rowid()`, a ~64-bit value that overflows JS's safe-integer
  // range). High-throughput CockroachDB users should override this per-entity with a UUID PK.
  override readonly autoIncrementSuffix: string = 'GENERATED BY DEFAULT AS IDENTITY';
  override readonly tableOptions = '';
  override readonly beginTransactionCommand = 'BEGIN';
  override readonly commitTransactionCommand = 'COMMIT';
  override readonly rollbackTransactionCommand = 'ROLLBACK';
  override readonly alterColumnStrategy = 'separate-clauses';

  /**
   * `JSON_AGG` of each row whole, read through a LATERAL projection of the columns it answers under:
   * the sort terms carried out beside them order it without joining the object, and no function call
   * builds it, so a wide row meets no argument limit. `json` has no equality, so under a parent's
   * `DISTINCT` the array is compared as `jsonb`.
   */
  protected override appendRelationArray(ctx: QueryContext, rows: RelationRows): void {
    const { from, pairs, order } = this.derivedRelation(ctx, rows);
    const row = this.escapeId(RELATION_ROW_ALIAS, true);
    const columns = pairs.map(([, column]) => column).join(', ');
    const array = /*sql*/ `(SELECT COALESCE(JSON_AGG(${row}${order ? ` ORDER BY ${order}` : ''}), '[]'::json) FROM ${from} CROSS JOIN LATERAL (SELECT ${columns}) ${row})`;
    ctx.append(rows.distinct ? `${array}::jsonb` : array);
  }

  /**
   * What JSON would round or cannot spell crosses it as text, for the field's own decode to read back:
   * a column declared numeric, whatever it decodes as, a vector, and bytes as hex.
   */
  protected override readonly carriedFields = {
    numeric: (expr) => `${expr}::text`,
    vector: (expr) => `${expr}::text`,
    blob: (expr) => `${this.escape(BYTES_PREFIX)} || ENCODE(${expr}, 'hex')`,
  } satisfies CarriedFields;

  /** `$N` placeholders carry their own index, so the upsert's assignments need no scratch context. */
  protected override readonly upsertUpdateBindsInPlace = true;
  override readonly insertIdSource = 'returning';
  override readonly maxBindValues: number = 65535;

  override readonly vectorMetrics = PG_VECTOR_METRICS;

  /** `SET LOCAL` applies to the enclosing transaction and to nothing at all without one. */
  override readonly vectorTuningNeedsTransaction = true;

  /**
   * The GUC each pgvector index type reads for "how much of the index to explore". They are not the
   * same quantity - `ef_search` is a candidate-list size, `probes` a count of lists - which is why
   * `$candidates` is documented in the index's own units rather than as a portable number.
   */
  private static readonly ANN_SETTINGS: ReadonlyMap<IndexType, string> = new Map<IndexType, string>([
    ['hnsw', 'hnsw.ef_search'],
    ['ivfflat', 'ivfflat.probes'],
  ]);

  /**
   * `SET LOCAL hnsw.ef_search = N`, plus `hnsw.iterative_scan` when the query also filters by
   * distance. Without iterative scan, HNSW returns its candidate list and the predicate then removes
   * from it, so a `$near` can hand back fewer rows than qualify - the recall bug `$candidates`
   * exists to answer. `strict_order`, never `relaxed_order`: the latter returns rows out of distance
   * order, which would quietly contradict the `ORDER BY` the caller asked for.
   */
  override vectorTuningStatements<E>(meta: EntityMeta<E>, q: Query<E>): readonly string[] {
    const indexType = this.tunedVectorIndex(meta, q)?.type;
    const setting = indexType ? PgLikeSqlDialect.ANN_SETTINGS.get(indexType) : undefined;
    if (!setting) {
      return [];
    }
    const statements = [`SET LOCAL ${setting} = ${q.$candidates}`];
    if (indexType === 'hnsw' && hasVectorNear(q.$where)) {
      statements.push('SET LOCAL hnsw.iterative_scan = strict_order');
    }
    return statements;
  }

  override normalizeValue(value: unknown): unknown {
    if (value != null && typeof value === 'object' && Array.isArray(value)) {
      return this.features.nativeArrays ? value : toPgArray(value);
    }
    return super.normalizeValue(value);
  }

  override placeholder(index: number): string {
    return `$${index}`;
  }

  /**
   * `TO_TSVECTOR(...) @@ WEBSEARCH_TO_TSQUERY(...)`. `WEBSEARCH_TO_TSQUERY` takes free-form user input
   * (quoted phrases, `or`, `-negation`) and never raises a syntax error, unlike `TO_TSQUERY`, which
   * rejects anything unparseable - including a plain two-word search.
   */
  protected override appendTextSearch<E>(
    ctx: QueryContext,
    _entity: Type<E>,
    meta: EntityMeta<E>,
    search: QueryTextSearchOptions<E>,
  ): void {
    const fields = textSearchFields(meta, search)
      .map((key) => this.escapeId(this.resolveColumnName(key, meta.fields[key])))
      .join(` || ' ' || `);
    // The config is bound once and its numbered placeholder reused by both calls.
    const config = search.$config ? `${this.addValue(ctx.values, search.$config)}::regconfig, ` : '';
    ctx.append(`TO_TSVECTOR(${config}${fields}) @@ WEBSEARCH_TO_TSQUERY(${config}`);
    ctx.addValue(search.$value);
    ctx.append(')');
  }

  protected override jsonAll(ctx: QueryContext, jsonField: string, value: unknown): string {
    return `${jsonField} @> ${this.jsonVal(ctx, value)}`;
  }

  protected override jsonSize(ctx: QueryContext, jsonField: string, value: number | QuerySizeComparisonOps): string {
    return this.buildFragment(ctx, (fragmentCtx) =>
      this.buildSizeComparison(fragmentCtx, () => fragmentCtx.append(`JSONB_ARRAY_LENGTH(${jsonField})`), value),
    );
  }

  /**
   * Object elements stay `jsonb` so each field can pick `->` or `->>`. Scalar elements are exploded
   * as text unless they are compared as JSON, where `_text` would yield `text = jsonb`.
   */
  protected override jsonElemFrom(jsonField: string, fields: readonly string[], alias: string, asJson = false): string {
    const fn = fields.length || asJson ? 'JSONB_ARRAY_ELEMENTS' : 'JSONB_ARRAY_ELEMENTS_TEXT';
    return `${fn}(${jsonField}) AS ${alias}`;
  }

  protected override jsonElemRef(alias: string, field?: string, asJson = false): string {
    if (field === undefined) {
      return alias;
    }
    return asJson ? `${alias}->'${escapeSingleQuotes(field)}'` : `${alias}->>'${escapeSingleQuotes(field)}'`;
  }

  protected override get regexpOp(): string {
    return '~';
  }

  protected override readonly caseInsensitiveMatch = 'ilike';

  protected override get neOp(): string {
    return 'IS DISTINCT FROM';
  }

  protected override formatIn(ctx: QueryContext, values: unknown[], negate: boolean): string {
    if (values.length === 0) return negate ? ' NOT IN (NULL)' : ' IN (NULL)';
    const ph = this.addValue(ctx.values, values);
    return negate ? ` <> ALL(${ph})` : ` = ANY(${ph})`;
  }

  protected override numericCast(expr: string): string {
    return `(${expr})::numeric`;
  }

  protected override appendJsonValue(ctx: QueryContext, value: unknown, type: JsonColumnType): void {
    ctx.append(this.jsonVal(ctx, value, type));
  }

  /**
   * pgvector needs the cast to pick the right type, and `sparsevec` needs its own literal: the dense
   * `[1,0,2]` every other type takes is rejected as "invalid input syntax for type sparsevec".
   */
  protected override appendVectorValue(ctx: QueryContext, value: readonly unknown[], field?: FieldOptions): void {
    const vectorType = this.supportedVectorType(resolveVectorCast(field));
    ctx.addValue(vectorType === 'sparsevec' ? toSparsevecLiteral(value) : `[${value.join(',')}]`);
    ctx.append(`::${vectorType}`);
  }

  /**
   * `create_if_missing => false` keeps an absent key (and a NULL column) untouched; `WITH
   * ORDINALITY` keeps the surviving elements in their original order.
   */
  protected override jsonPullKey(
    ctx: QueryContext,
    expr: string,
    escapedCol: string,
    key: string,
    value: unknown,
  ): string {
    const escapedKey = escapeSingleQuotes(key);
    const kept = `SELECT JSONB_AGG(${JSON_PULL_ALIAS}.val ORDER BY ${JSON_PULL_ALIAS}.ord) FROM JSONB_ARRAY_ELEMENTS(${escapedCol}->'${escapedKey}') WITH ORDINALITY AS ${JSON_PULL_ALIAS}(val, ord) WHERE ${JSON_PULL_ALIAS}.val <> ${this.jsonVal(ctx, value)}`;
    return `JSONB_SET(${expr}, '{${escapedKey}}', COALESCE((${kept}), '[]'::jsonb), false)`;
  }

  /**
   * The plain values merge as one bound object; a `raw()` one is an SQL expression rather than JSON,
   * so it merges through `JSONB_BUILD_OBJECT` and is evaluated in place - stringified with the rest,
   * it would land as `{}`.
   */
  protected override jsonSet(
    ctx: QueryContext,
    expr: string,
    set: Record<string, unknown>,
    field?: FieldOptions,
  ): string {
    const entries = Object.entries(set);
    const merged = this.jsonVal(ctx, Object.fromEntries(entries.filter(([, value]) => !(value instanceof QueryRaw))));
    const raws = entries.flatMap(([key, value]) =>
      value instanceof QueryRaw
        ? [` || JSONB_BUILD_OBJECT('${escapeSingleQuotes(key)}', ${this.rawFragment(ctx, value)})`]
        : [],
    );
    return `${jsonSetTarget(expr, field, `'{}'::jsonb`)} || ${merged}${raws.join('')}`;
  }

  /** The only fragment that references `expr` twice - safe here because placeholders are numbered. */
  protected override jsonPush(ctx: QueryContext, expr: string, push: Record<string, unknown>): string {
    return Object.entries(push).reduce((acc, [key, value]) => {
      const escapedKey = escapeSingleQuotes(key);
      const ph = this.jsonVal(ctx, value);
      return `JSONB_SET(${acc}, '{${escapedKey}}', COALESCE((${acc})->'${escapedKey}', '[]'::jsonb) || JSONB_BUILD_ARRAY(${ph}))`;
    }, expr);
  }

  protected override jsonUnset(ctx: QueryContext, expr: string, unset: readonly string[]): string {
    return `(${expr}) - ${this.addValue(ctx.values, [...unset])}::text[]`;
  }

  /** Postgres binds JSON with a numbered placeholder and an explicit cast, per driver capability. */
  protected override jsonScalarParam(ctx: QueryContext, value: unknown): string {
    return this.jsonVal(ctx, value);
  }

  /**
   * Helper to add a JSON value to context with appropriate stringification and cast.
   */
  private jsonVal(ctx: QueryContext, value: unknown, type: JsonColumnType = 'jsonb'): string {
    if (value instanceof QueryRaw) return this.rawFragment(ctx, value);
    if (value == null) return `${this.addValue(ctx.values, null)}::${type}`;

    const json = JSON.stringify(value);
    const ph = this.addValue(ctx.values, json);
    return this.features.explicitJsonCast ? `(${ph}::text)::${type}` : `${ph}::${type}`;
  }
}

/**
 * Converts a JS array to a Postgres array literal string: `{"val1","val2"}`.
 * Safely handles nesting and escaping of special characters.
 */
function toPgArray(arr: unknown[]): string {
  const elements = arr.map((val) => {
    if (val == null) return 'NULL';
    if (Array.isArray(val)) return toPgArray(val);
    if (typeof val === 'boolean') return val ? 'true' : 'false';
    if (val instanceof Uint8Array || (typeof Buffer !== 'undefined' && Buffer.isBuffer(val))) {
      const hex = Array.from(val)
        .map((b) => b.toString(16).padStart(2, '0'))
        .join('');
      return `"\\\\x${hex}"`;
    }
    const str = String(val);
    const escaped = str.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
    return `"${escaped}"`;
  });
  return `{${elements.join(',')}}`;
}
