import { getMeta } from '../entity/index.js';
import {
  type DialectFeatures,
  type EntityMeta,
  type FieldOptions,
  type JsonColumnType,
  type QueryComparisonOptions,
  type QueryConflictPaths,
  type QueryContext,
  type QueryOptions,
  QueryRaw,
  type QuerySizeComparisonOps,
  type QueryTextSearchOptions,
  type QueryVectorSearch,
  type Type,
  type VectorDistance,
} from '../type/index.js';
import { escapeAnsiSqlLiteral, escapeSingleQuotes } from '../util/ansiSqlLiteral.js';
import { isJsonType } from '../util/index.js';
import { AbstractSqlDialect } from './abstractSqlDialect.js';
import { jsonSetTarget } from './jsonSql.js';

/**
 * Shared AST/quoting/JSONB/full-text-search/vector-search implementation between Postgres and
 * CockroachDB (wire- and SQL-compatible for everything below, including `to_tsvector`/`to_tsquery`
 * and pgvector's `<=>`/`<->`/`<#>` distance operators, which CockroachDB implements natively).
 * `xmax`-based upsert `created` detection is Postgres-only (CockroachDB has no `xmax`/`ctid`) and
 * stays in {@link PostgresDialect}, along with the `vectorExtension`/`vectorIndexStyle` values that
 * differ (Postgres needs `CREATE EXTENSION vector` and pgvector's `USING ivfflat/hnsw` index
 * syntax; CockroachDB's vector type and `CREATE VECTOR INDEX` syntax are both native).
 */
export abstract class PgLikeSqlDialect extends AbstractSqlDialect {
  /** Default {@link DialectFeatures} for Postgres-wire dialects. */
  protected override readonly featureDefaults: DialectFeatures = {
    explicitJsonCast: false,
    nativeArrays: true,
    supportsJsonb: true,
    ifNotExists: true,
    indexIfNotExists: true,
    dropTableCascade: true,
    renameColumn: true,
    foreignKeyAlter: true,
    columnComment: false,
    vectorIndexStyle: 'create',
    vectorSupportsLength: true,
    supportsTimestamptz: true,
    defaultStringAsText: true,
  };

  override readonly escapeIdChar = '"';
  // Shared default for both dialects. CockroachDB docs flag sequential PKs as a hotspotting risk
  // under heavy concurrent insert load (writes concentrate on one range); this default still beats
  // `SERIAL` (CockroachDB's `unique_rowid()`, a ~64-bit value that overflows JS's safe-integer
  // range). High-throughput CockroachDB users should override this per-entity with a UUID PK.
  override readonly serialPrimaryKey: string = 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY';
  override readonly tableOptions = '';
  override readonly beginTransactionCommand = 'BEGIN';
  override readonly commitTransactionCommand = 'COMMIT';
  override readonly rollbackTransactionCommand = 'ROLLBACK';
  override readonly alterColumnStrategy = 'separate-clauses';
  override readonly insertIdSource = 'returning';
  override readonly maxBindValues: number = 65535;

  override readonly vectorOpsClass: ReadonlyMap<VectorDistance, string> | undefined = new Map([
    ['cosine', 'vector_cosine_ops'],
    ['l2', 'vector_l2_ops'],
    ['inner', 'vector_ip_ops'],
    ['l1', 'vector_l1_ops'],
    ['hamming', 'bit_hamming_ops'],
  ]);

  override normalizeValue(value: unknown): unknown {
    if (value != null && typeof value === 'object' && Array.isArray(value)) {
      return this.features.nativeArrays ? value : toPgArray(value);
    }
    return super.normalizeValue(value);
  }

  override placeholder(index: number): string {
    return `$${index}`;
  }

  override insert<E>(ctx: QueryContext, entity: Type<E>, payload: E | E[], opts?: QueryOptions): void {
    super.insert(ctx, entity, payload, opts);
    ctx.append(' ' + this.returningId(entity));
  }

  override upsert<E>(ctx: QueryContext, entity: Type<E>, conflictPaths: QueryConflictPaths<E>, payload: E | E[]): void {
    this.buildUpsertOnConflict(ctx, entity, conflictPaths, payload);
  }

  /**
   * Shared `INSERT ... ON CONFLICT (...) DO UPDATE/NOTHING RETURNING ...` builder, mirroring
   * {@link AbstractSqlDialect.onConflictUpsert}'s "assemble everything, don't hand back fragments"
   * shape for the `$N`-placeholder Postgres-wire dialects. `extraReturning` lets {@link PostgresDialect}
   * append `(xmax = 0) AS "_created"` to detect insert-vs-update; CockroachDB has no `xmax`/`ctid`
   * system columns, so it uses the default (empty) and `created` stays `undefined` in the result.
   */
  protected buildUpsertOnConflict<E>(
    ctx: QueryContext,
    entity: Type<E>,
    conflictPaths: QueryConflictPaths<E>,
    payload: E | E[],
    extraReturning = '',
  ): void {
    const meta = getMeta(entity);
    const update = this.getUpsertUpdateAssignments(ctx, meta, conflictPaths, payload, (name) => `EXCLUDED.${name}`);
    const keysStr = this.getUpsertConflictPathsStr(meta, conflictPaths);
    const onConflict = update ? `DO UPDATE SET ${update}` : 'DO NOTHING';
    super.insert(ctx, entity, payload);
    ctx.append(` ON CONFLICT (${keysStr}) ${onConflict} ${this.returningId(entity)}${extraReturning}`);
  }

  /**
   * Full-text search: `to_tsvector(...) @@ websearch_to_tsquery(...)`. `websearch_to_tsquery` takes
   * free-form user input (quoted phrases, `or`, `-negation`) and never raises a syntax error, unlike
   * `to_tsquery`, which rejects anything unparseable - including a plain two-word search.
   */
  override compare<E>(
    ctx: QueryContext,
    entity: Type<E>,
    key: string,
    val: unknown,
    opts: QueryComparisonOptions = {},
  ): void {
    if (key === '$text') {
      const meta = getMeta(entity);
      const search = val as QueryTextSearchOptions<E>;
      const fields = (search.$fields ?? [])
        .map((fKey) => {
          const field = meta.fields[fKey];
          const columnName = this.resolveColumnName(fKey, field!);
          return this.escapeId(columnName);
        })
        .join(` || ' ' || `);
      // The config is bound once and its numbered placeholder reused by both calls.
      const config = search.$config ? `${this.addValue(ctx.values, search.$config)}::regconfig, ` : '';
      ctx.append(`to_tsvector(${config}${fields}) @@ websearch_to_tsquery(${config}`);
      ctx.addValue(search.$value);
      ctx.append(')');
      return;
    }
    super.compare(ctx, entity, key, val, opts);
  }

  protected override jsonAll(ctx: QueryContext, jsonField: string, value: unknown): string {
    return `${jsonField} @> ${this.jsonVal(ctx, value)}`;
  }

  protected override jsonSize(ctx: QueryContext, jsonField: string, value: number | QuerySizeComparisonOps): string {
    const tmpCtx = this.createContext();
    this.buildSizeComparison(tmpCtx, () => tmpCtx.append(`jsonb_array_length(${jsonField})`), value);
    ctx.pushValue(...tmpCtx.values);
    return tmpCtx.sql;
  }

  /**
   * Object elements stay `jsonb` so each field can pick `->` or `->>`. Scalar elements are exploded
   * as text unless they are compared as JSON, where `_text` would yield `text = jsonb`.
   */
  protected override jsonElemFrom(jsonField: string, fields: readonly string[], asJson = false): string {
    const fn = fields.length || asJson ? 'jsonb_array_elements' : 'jsonb_array_elements_text';
    return `${fn}(${jsonField}) AS elem`;
  }

  protected override jsonElemRef(field?: string, asJson = false): string {
    if (field === undefined) {
      return 'elem';
    }
    return asJson ? `elem->'${escapeSingleQuotes(field)}'` : `elem->>'${escapeSingleQuotes(field)}'`;
  }

  protected override get regexpOp(): string {
    return '~';
  }

  protected override ilikeExpr(f: string, ph: string): string {
    return `${f} ILIKE ${ph}`;
  }

  protected override get neOp(): string {
    return 'IS DISTINCT FROM';
  }

  protected override formatIn(ctx: QueryContext, values: unknown[], negate: boolean): string {
    if (values.length === 0) return negate ? ' NOT IN (NULL)' : ' IN (NULL)';
    const ph = this.addValue(ctx.values, values);
    return negate ? ` <> ALL(${ph})` : ` = ANY(${ph})`;
  }

  protected override numericCast(expr: string): string {
    return `(${expr})::numeric`;
  }

  protected override formatPersistableValue<E>(ctx: QueryContext, field: FieldOptions, value: unknown): void {
    if (value instanceof QueryRaw) {
      super.formatPersistableValue(ctx, field, value);
      return;
    }
    if (isJsonType(field.type)) {
      ctx.append(this.jsonVal(ctx, value, field.type as JsonColumnType));
      return;
    }
    if (field.type === 'vector' && Array.isArray(value)) {
      ctx.addValue(`[${value.join(',')}]`);
      ctx.append('::vector');
      return;
    }
    super.formatPersistableValue(ctx, field, value);
  }

  /**
   * `create_if_missing => false` keeps an absent key (and a NULL column) untouched; `WITH
   * ORDINALITY` keeps the surviving elements in their original order.
   */
  protected override jsonPullKey(
    ctx: QueryContext,
    expr: string,
    escapedCol: string,
    key: string,
    value: unknown,
  ): string {
    const escapedKey = escapeSingleQuotes(key);
    const kept = `SELECT jsonb_agg(uql_pull.val ORDER BY uql_pull.ord) FROM jsonb_array_elements(${escapedCol}->'${escapedKey}') WITH ORDINALITY AS uql_pull(val, ord) WHERE uql_pull.val <> ${this.jsonVal(ctx, value)}`;
    return `jsonb_set(${expr}, '{${escapedKey}}', COALESCE((${kept}), '[]'::jsonb), false)`;
  }

  protected override jsonSet(
    ctx: QueryContext,
    expr: string,
    set: Record<string, unknown>,
    field?: FieldOptions,
  ): string {
    return `${jsonSetTarget(expr, field, `'{}'::jsonb`)} || ${this.jsonVal(ctx, set)}`;
  }

  /** The only fragment that references `expr` twice - safe here because placeholders are numbered. */
  protected override jsonPush(ctx: QueryContext, expr: string, push: Record<string, unknown>): string {
    return Object.entries(push).reduce((acc, [key, value]) => {
      const escapedKey = escapeSingleQuotes(key);
      const ph = this.jsonVal(ctx, value);
      return `jsonb_set(${acc}, '{${escapedKey}}', COALESCE((${acc})->'${escapedKey}', '[]'::jsonb) || jsonb_build_array(${ph}))`;
    }, expr);
  }

  protected override jsonUnset(ctx: QueryContext, expr: string, unset: readonly string[]): string {
    return `(${expr}) - ${this.addValue(ctx.values, [...unset])}::text[]`;
  }

  /** Postgres binds JSON with a numbered placeholder and an explicit cast, per driver capability. */
  protected override jsonScalarParam(ctx: QueryContext, value: unknown): string {
    return this.jsonVal(ctx, value);
  }

  /**
   * Helper to add a JSON value to context with appropriate stringification and cast.
   */
  private jsonVal(ctx: QueryContext, value: unknown, type: JsonColumnType = 'jsonb'): string {
    if (value instanceof QueryRaw) return this.addValue(ctx.values, value);
    if (value == null) return `${this.addValue(ctx.values, null)}::${type}`;

    const json = JSON.stringify(value);
    const ph = this.addValue(ctx.values, json);
    return this.features.explicitJsonCast ? `(${ph}::text)::${type}` : `${ph}::${type}`;
  }

  override escape(value: unknown): string {
    return escapeAnsiSqlLiteral(value);
  }

  /**
   * pgvector distance operators. Not every dialect supports every metric - see
   * {@link CockroachDialect.vectorOpsClass} for which ones each dialect actually has; the
   * `vectorOpsClass` key set (checked in `appendVectorSort` below via `vectorOpsClass.get`)
   * is the single source of truth for that, not this map.
   */
  private static readonly VECTOR_OPS: Record<VectorDistance, string> = {
    cosine: '<=>',
    l2: '<->',
    inner: '<#>',
    l1: '<+>',
    hamming: '<~>',
  };

  /** Emit a pgvector-style distance expression: `"col" <op> $N::<vectorType>`. */
  protected override appendVectorSort<E>(
    ctx: QueryContext,
    meta: EntityMeta<E>,
    key: string,
    search: QueryVectorSearch,
  ): void {
    const { colName, distance, vectorCast } = this.resolveVectorSortParams(meta, key, search);
    if (!this.vectorOpsClass!.get(distance)) {
      throw new TypeError(`${this.dialectName} does not support vector distance metric: ${distance}`);
    }
    const op = PgLikeSqlDialect.VECTOR_OPS[distance];
    ctx.append(`${this.escapeId(colName)} ${op} `);
    ctx.addValue(`[${search.$vector.join(',')}]`);
    ctx.append(`::${vectorCast}`);
  }
}

/**
 * Converts a JS array to a Postgres array literal string: `{"val1","val2"}`.
 * Safely handles nesting and escaping of special characters.
 */
function toPgArray(arr: unknown[]): string {
  const elements = arr.map((val) => {
    if (val == null) return 'NULL';
    if (Array.isArray(val)) return toPgArray(val);
    if (typeof val === 'boolean') return val ? 'true' : 'false';
    if (val instanceof Uint8Array || (typeof Buffer !== 'undefined' && Buffer.isBuffer(val))) {
      const hex = Array.from(val)
        .map((b) => b.toString(16).padStart(2, '0'))
        .join('');
      return `"\\\\x${hex}"`;
    }
    const str = String(val);
    const escaped = str.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
    return `"${escaped}"`;
  });
  return `{${elements.join(',')}}`;
}
