import type { IndexType } from '../schema/types.js';
import {
  type DialectFeatures,
  type EntityMeta,
  type FieldOptions,
  type JsonColumnType,
  type Query,
  type QueryContext,
  QueryRaw,
  type QuerySizeComparisonOps,
  type QueryTextSearchOptions,
  type Type,
  type VectorDistance,
  type VectorOperatorMetric,
} from '../type/index.js';
import { hasVectorNear } from '../util/dialect.util.js';
import { escapeSingleQuotes } from '../util/sqlLiteral.js';
import { AbstractSqlDialect } from './abstractSqlDialect.js';
import { JSON_PULL_ALIAS } from './aliases.js';
import { jsonSetTarget } from './jsonSql.js';
import { resolveVectorCast, toSparsevecLiteral } from './vectorCast.js';

/**
 * Shared AST/quoting/JSONB/full-text-search/vector-search implementation between Postgres and
 * CockroachDB (wire- and SQL-compatible for everything below, including `to_tsvector`/`to_tsquery`
 * and pgvector's `<=>`/`<->`/`<#>` distance operators, which CockroachDB implements natively).
 * `xmax`-based upsert `created` detection is Postgres-only (CockroachDB has no `xmax`/`ctid`) and
 * stays in {@link PostgresDialect}, along with the `vectorExtension`/`vectorIndexStyle` values that
 * differ (Postgres needs `CREATE EXTENSION vector` and pgvector's `USING ivfflat/hnsw` index
 * syntax; CockroachDB's vector type and `CREATE VECTOR INDEX` syntax are both native).
 */
export abstract class PgLikeSqlDialect extends AbstractSqlDialect {
  /** `FOR UPDATE` and a window function cannot share a statement here. See the base declaration. */
  override readonly supportsWindowWithRowLock = false;

  /** Default {@link DialectFeatures} for Postgres-wire dialects. */
  protected override readonly featureDefaults: DialectFeatures = {
    explicitJsonCast: false,
    nativeArrays: true,
    supportsJsonb: true,
    ifNotExists: true,
    indexIfNotExists: true,
    schemas: true,
    dropTableCascade: true,
    renameColumn: true,
    foreignKeyAlter: true,
    columnComment: false,
    vectorIndexRequiresNotNull: false,
    vectorSupportsLength: true,
    supportsTimestamptz: true,
    defaultStringAsText: true,
  };

  override readonly escapeIdChar = '"';
  // Shared default for both dialects. CockroachDB docs flag sequential PKs as a hotspotting risk
  // under heavy concurrent insert load (writes concentrate on one range); this default still beats
  // `SERIAL` (CockroachDB's `unique_rowid()`, a ~64-bit value that overflows JS's safe-integer
  // range). High-throughput CockroachDB users should override this per-entity with a UUID PK.
  override readonly serialPrimaryKey: string = 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY';
  override readonly tableOptions = '';
  override readonly beginTransactionCommand = 'BEGIN';
  override readonly commitTransactionCommand = 'COMMIT';
  override readonly rollbackTransactionCommand = 'ROLLBACK';
  override readonly alterColumnStrategy = 'separate-clauses';

  /** `$N` placeholders carry their own index, so the upsert's assignments need no scratch context. */
  protected override readonly upsertUpdateBindsInPlace = true;
  override readonly insertIdSource = 'returning';
  override readonly maxBindValues: number = 65535;

  /**
   * Each metric's pgvector distance operator and the operator-class suffix its index takes, in one
   * place so a dialect cannot end up with the operator but not the opclass. The key set is the single
   * source of truth for which metrics the dialect supports at all: CockroachDB narrows it to three.
   */
  override readonly vectorMetrics: ReadonlyMap<VectorDistance, VectorOperatorMetric> = new Map([
    ['cosine', { op: '<=>', opsSuffix: 'cosine' }],
    ['l2', { op: '<->', opsSuffix: 'l2' }],
    ['inner', { op: '<#>', opsSuffix: 'ip' }],
    ['l1', { op: '<+>', opsSuffix: 'l1' }],
  ]);

  /** `SET LOCAL` applies to the enclosing transaction and to nothing at all without one. */
  override readonly vectorTuningNeedsTransaction = true;

  /**
   * The GUC each pgvector index type reads for "how much of the index to explore". They are not the
   * same quantity - `ef_search` is a candidate-list size, `probes` a count of lists - which is why
   * `$candidates` is documented in the index's own units rather than as a portable number.
   */
  private static readonly ANN_SETTINGS: ReadonlyMap<IndexType, string> = new Map<IndexType, string>([
    ['hnsw', 'hnsw.ef_search'],
    ['ivfflat', 'ivfflat.probes'],
  ]);

  /**
   * `SET LOCAL hnsw.ef_search = N`, plus `hnsw.iterative_scan` when the query also filters by
   * distance. Without iterative scan, HNSW returns its candidate list and the predicate then removes
   * from it, so a `$near` can hand back fewer rows than qualify - the recall bug `$candidates`
   * exists to answer. `strict_order`, never `relaxed_order`: the latter returns rows out of distance
   * order, which would quietly contradict the `ORDER BY` the caller asked for.
   */
  override vectorTuningStatements<E>(meta: EntityMeta<E>, q: Query<E>): readonly string[] {
    const indexType = this.tunedVectorIndex(meta, q)?.type;
    const setting = indexType ? PgLikeSqlDialect.ANN_SETTINGS.get(indexType) : undefined;
    if (!setting) {
      return [];
    }
    const statements = [`SET LOCAL ${setting} = ${q.$candidates}`];
    if (indexType === 'hnsw' && hasVectorNear(q.$where)) {
      statements.push('SET LOCAL hnsw.iterative_scan = strict_order');
    }
    return statements;
  }

  override normalizeValue(value: unknown): unknown {
    if (value != null && typeof value === 'object' && Array.isArray(value)) {
      return this.features.nativeArrays ? value : toPgArray(value);
    }
    return super.normalizeValue(value);
  }

  override placeholder(index: number): string {
    return `$${index}`;
  }

  /**
   * `to_tsvector(...) @@ websearch_to_tsquery(...)`. `websearch_to_tsquery` takes free-form user input
   * (quoted phrases, `or`, `-negation`) and never raises a syntax error, unlike `to_tsquery`, which
   * rejects anything unparseable - including a plain two-word search.
   */
  protected override appendTextSearch<E>(
    ctx: QueryContext,
    _entity: Type<E>,
    meta: EntityMeta<E>,
    search: QueryTextSearchOptions<E>,
  ): void {
    const fields = (search.$fields ?? [])
      .map((key) => this.escapeId(this.resolveColumnName(key, meta.fields[key])))
      .join(` || ' ' || `);
    // The config is bound once and its numbered placeholder reused by both calls.
    const config = search.$config ? `${this.addValue(ctx.values, search.$config)}::regconfig, ` : '';
    ctx.append(`to_tsvector(${config}${fields}) @@ websearch_to_tsquery(${config}`);
    ctx.addValue(search.$value);
    ctx.append(')');
  }

  protected override jsonAll(ctx: QueryContext, jsonField: string, value: unknown): string {
    return `${jsonField} @> ${this.jsonVal(ctx, value)}`;
  }

  protected override jsonSize(ctx: QueryContext, jsonField: string, value: number | QuerySizeComparisonOps): string {
    return this.buildFragment(ctx, (fragmentCtx) =>
      this.buildSizeComparison(fragmentCtx, () => fragmentCtx.append(`jsonb_array_length(${jsonField})`), value),
    );
  }

  /**
   * Object elements stay `jsonb` so each field can pick `->` or `->>`. Scalar elements are exploded
   * as text unless they are compared as JSON, where `_text` would yield `text = jsonb`.
   */
  protected override jsonElemFrom(jsonField: string, fields: readonly string[], alias: string, asJson = false): string {
    const fn = fields.length || asJson ? 'jsonb_array_elements' : 'jsonb_array_elements_text';
    return `${fn}(${jsonField}) AS ${alias}`;
  }

  protected override jsonElemRef(alias: string, field?: string, asJson = false): string {
    if (field === undefined) {
      return alias;
    }
    return asJson ? `${alias}->'${escapeSingleQuotes(field)}'` : `${alias}->>'${escapeSingleQuotes(field)}'`;
  }

  protected override get regexpOp(): string {
    return '~';
  }

  protected override readonly caseInsensitiveMatch = 'ilike';

  protected override get neOp(): string {
    return 'IS DISTINCT FROM';
  }

  protected override formatIn(ctx: QueryContext, values: unknown[], negate: boolean): string {
    if (values.length === 0) return negate ? ' NOT IN (NULL)' : ' IN (NULL)';
    const ph = this.addValue(ctx.values, values);
    return negate ? ` <> ALL(${ph})` : ` = ANY(${ph})`;
  }

  protected override numericCast(expr: string): string {
    return `(${expr})::numeric`;
  }

  protected override appendJsonValue(ctx: QueryContext, value: unknown, type: JsonColumnType): void {
    ctx.append(this.jsonVal(ctx, value, type));
  }

  /**
   * pgvector needs the cast to pick the right type, and `sparsevec` needs its own literal: the dense
   * `[1,0,2]` every other type takes is rejected as "invalid input syntax for type sparsevec".
   */
  protected override appendVectorValue(ctx: QueryContext, value: readonly unknown[], field?: FieldOptions): void {
    const vectorType = this.supportedVectorType(resolveVectorCast(field));
    ctx.addValue(vectorType === 'sparsevec' ? toSparsevecLiteral(value) : `[${value.join(',')}]`);
    ctx.append(`::${vectorType}`);
  }

  /**
   * `create_if_missing => false` keeps an absent key (and a NULL column) untouched; `WITH
   * ORDINALITY` keeps the surviving elements in their original order.
   */
  protected override jsonPullKey(
    ctx: QueryContext,
    expr: string,
    escapedCol: string,
    key: string,
    value: unknown,
  ): string {
    const escapedKey = escapeSingleQuotes(key);
    const kept = `SELECT jsonb_agg(${JSON_PULL_ALIAS}.val ORDER BY ${JSON_PULL_ALIAS}.ord) FROM jsonb_array_elements(${escapedCol}->'${escapedKey}') WITH ORDINALITY AS ${JSON_PULL_ALIAS}(val, ord) WHERE ${JSON_PULL_ALIAS}.val <> ${this.jsonVal(ctx, value)}`;
    return `jsonb_set(${expr}, '{${escapedKey}}', COALESCE((${kept}), '[]'::jsonb), false)`;
  }

  protected override jsonSet(
    ctx: QueryContext,
    expr: string,
    set: Record<string, unknown>,
    field?: FieldOptions,
  ): string {
    return `${jsonSetTarget(expr, field, `'{}'::jsonb`)} || ${this.jsonVal(ctx, set)}`;
  }

  /** The only fragment that references `expr` twice - safe here because placeholders are numbered. */
  protected override jsonPush(ctx: QueryContext, expr: string, push: Record<string, unknown>): string {
    return Object.entries(push).reduce((acc, [key, value]) => {
      const escapedKey = escapeSingleQuotes(key);
      const ph = this.jsonVal(ctx, value);
      return `jsonb_set(${acc}, '{${escapedKey}}', COALESCE((${acc})->'${escapedKey}', '[]'::jsonb) || jsonb_build_array(${ph}))`;
    }, expr);
  }

  protected override jsonUnset(ctx: QueryContext, expr: string, unset: readonly string[]): string {
    return `(${expr}) - ${this.addValue(ctx.values, [...unset])}::text[]`;
  }

  /** Postgres binds JSON with a numbered placeholder and an explicit cast, per driver capability. */
  protected override jsonScalarParam(ctx: QueryContext, value: unknown): string {
    return this.jsonVal(ctx, value);
  }

  /**
   * Helper to add a JSON value to context with appropriate stringification and cast.
   */
  private jsonVal(ctx: QueryContext, value: unknown, type: JsonColumnType = 'jsonb'): string {
    if (value instanceof QueryRaw) return this.addValue(ctx.values, value);
    if (value == null) return `${this.addValue(ctx.values, null)}::${type}`;

    const json = JSON.stringify(value);
    const ph = this.addValue(ctx.values, json);
    return this.features.explicitJsonCast ? `(${ph}::text)::${type}` : `${ph}::${type}`;
  }
}

/**
 * Converts a JS array to a Postgres array literal string: `{"val1","val2"}`.
 * Safely handles nesting and escaping of special characters.
 */
function toPgArray(arr: unknown[]): string {
  const elements = arr.map((val) => {
    if (val == null) return 'NULL';
    if (Array.isArray(val)) return toPgArray(val);
    if (typeof val === 'boolean') return val ? 'true' : 'false';
    if (val instanceof Uint8Array || (typeof Buffer !== 'undefined' && Buffer.isBuffer(val))) {
      const hex = Array.from(val)
        .map((b) => b.toString(16).padStart(2, '0'))
        .join('');
      return `"\\\\x${hex}"`;
    }
    const str = String(val);
    const escaped = str.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
    return `"${escaped}"`;
  });
  return `{${elements.join(',')}}`;
}
