import { getMeta } from '../../entity/index.js';
import { canonicalToTypeScript } from '../../schema/canonicalType.js';
import { resolveColumnCanonicalType } from '../../schema/schemaASTBuilder.js';
import type { EntityMeta, FieldMeta, RelationMeta, Type } from '../../type/index.js';
import { isToManyRelation, upperFirst } from '../../util/index.js';
import { isIdentifierName } from './sourceLiteral.js';

/**
 * A `.d.ts` for the entities as registered, so a shape that only exists at runtime reaches the
 * compiler too. Interfaces, not the entity classes `generate:from-db` writes: those are the source of
 * a schema, these describe one already defined elsewhere.
 */
export function entityTypesSource(entities: readonly Type<object>[]): string {
  const metas = [...entities]
    .map((entity) => getMeta(entity))
    .sort((a, b) => a.entity.name.localeCompare(b.entity.name));
  const names = interfaceNames(metas);

  const interfaces = metas.map((meta) => {
    const members = [
      ...Object.entries<FieldMeta | undefined>(meta.fields).map(([key, field]) => member(key, fieldType(field))),
      ...Object.entries<RelationMeta | undefined>(meta.relations).map(([key, rel]) =>
        member(key, relationType(rel, names)),
      ),
    ];
    return `export interface ${names.get(meta.entity)} {\n${members.join('\n')}\n}`;
  });

  return ['// Generated by `uql-migrate types`. Do not edit.', '', ...interfaces, ''].join('\n');
}

/**
 * One interface name per entity, settled before anything is written so a relation and its target
 * agree. A class minted at runtime is named after the content type it came from, which nothing stops
 * from carrying a dash or colliding with another once the dashes are gone - and either would emit a
 * file that does not compile.
 */
function interfaceNames(metas: readonly EntityMeta<object>[]): Map<Type<object>, string> {
  const taken = new Set<string>();
  return new Map(
    metas.map((meta) => {
      const base = identifier(upperFirst(meta.entity.name));
      let name = base;
      for (let n = 2; taken.has(name); n++) {
        name = `${base}${n}`;
      }
      taken.add(name);
      return [meta.entity, name];
    }),
  );
}

/** `text` as an identifier: what cannot be in one is dropped, and what cannot start one is prefixed. */
function identifier(text: string): string {
  const stripped = text.replace(/[^\p{ID_Continue}$\u200C\u200D]/gu, '');
  return isIdentifierName(stripped) ? stripped : `Entity${stripped}`;
}

/** A column name a property cannot hold - `hero-image` - is quoted rather than dropped. */
function member(key: string, type: string): string {
  const name = isIdentifierName(key) ? key : JSON.stringify(key);
  return `  ${name}?: ${type};`;
}

/**
 * The property type a column reads back as, resolved the way the DDL resolves it - so a foreign key
 * reports the type of the key it points at rather than the fallback its own options carry.
 */
function fieldType(field: FieldMeta | undefined): string {
  return field ? canonicalToTypeScript(resolveColumnCanonicalType(field)) : 'unknown';
}

/**
 * A relation is the related interface, a list where the cardinality says so - and `unknown` where the
 * target is outside the set, since naming an interface the file does not declare would not compile.
 */
function relationType(relation: RelationMeta | undefined, names: ReadonlyMap<Type<object>, string>): string {
  const target = relation && names.get(relation.entity());
  if (!target) {
    return 'unknown';
  }
  return isToManyRelation(relation) ? `${target}[]` : target;
}
