import { expect, it } from 'vitest';
import { defineEntity } from '../../entity/index.js';
import { raw } from '../../util/index.js';
import { entityTypesSource } from './entityTypes.js';

it('should write an interface per registered entity, relations included', () => {
  class Author {
    id?: number;
    name?: string | null;
    posts?: Post[];
  }
  class Post {
    id?: number;
    title?: string | null;
    publishedAt?: Date | null;
    authorId?: number | null;
    author?: Author;
  }
  defineEntity(Author, {
    fields: { id: { type: Number, isId: true }, name: { type: String } },
    relations: { posts: { cardinality: '1m', entity: () => Post, mappedBy: (post) => post.author } },
  });
  defineEntity(Post, {
    fields: {
      id: { type: Number, isId: true },
      title: { type: String },
      publishedAt: { type: Date },
      authorId: { references: () => Author },
    },
    relations: { author: { cardinality: 'm1', entity: () => Author, references: (post) => post.authorId } },
  });

  expect(entityTypesSource([Author, Post])).toBe(
    [
      '// Generated by `uql-migrate types`. Do not edit.',
      '',
      'export interface Author {',
      '  id: number;',
      '  name?: string | null;',
      '  posts?: Post[];',
      '}',
      'export interface Post {',
      '  id: number;',
      '  title?: string | null;',
      '  publishedAt?: Date | null;',
      '  authorId?: number | null;',
      '  author?: Author;',
      '}',
      '',
    ].join('\n'),
  );
});

it('should emit names a generated file can carry, whatever a content type was called', () => {
  const Outside = { outside: class {} }.outside;
  defineEntity(Outside, { fields: { id: { type: Number, isId: true } } });

  // A slug carries what an identifier cannot, and two of them collide once that is stripped.
  const dashed = { 'blog-post': class {} }['blog-post'];
  defineEntity(dashed, {
    fields: {
      id: { type: Number, isId: true },
      'hero-image': { type: String },
      outsideId: { references: () => Outside },
    },
    relations: { outside: { cardinality: 'm1', entity: () => Outside, references: () => 'outsideId' } },
  });
  const collides = { blogpost: class {} }.blogpost;
  defineEntity(collides, { fields: { id: { type: Number, isId: true } } });
  // A slug can also start with what an identifier cannot.
  const numeric = { '2fa': class {} }['2fa'];
  defineEntity(numeric, { fields: { id: { type: Number, isId: true } } });

  expect(entityTypesSource([numeric])).toContain('export interface Entity2fa {');
  const source = entityTypesSource([dashed, collides]);
  expect(source).toContain('export interface Blogpost {');
  expect(source).toContain('export interface Blogpost2 {');
  expect(source).toContain('  "hero-image"?: string | null;');
  // The relation's target is outside the set, so naming its interface would not compile.
  expect(source).toContain('  outside?: unknown;');
  expect(entityTypesSource([dashed, Outside])).toContain('  outside?: Outside;');
});

it('should keep the letters of a name in any script', () => {
  const owner = { dueño: class {} }.dueño;
  defineEntity(owner, { fields: { id: { type: Number, isId: true }, größe: { type: String } } });

  const source = entityTypesSource([owner]);
  expect(source).toContain('export interface Dueño {');
  expect(source).toContain('  größe?: string | null;');
});

/** Declared as a class would declare it, so a read has what every row has and an insert names it. */
it('should declare each field as present, filled, optional or nullable as its column is', () => {
  const Invoice = { Invoice: class {} }.Invoice;
  defineEntity(Invoice, {
    fields: {
      id: { type: Number, isId: true },
      number: { type: String, nullable: false },
      status: { type: String, nullable: false, defaultValue: 'draft' },
      issuedAt: { type: Date, nullable: false, onInsert: () => new Date() },
      pdf: { type: 'blob', nullable: false, eager: false },
      note: { type: String },
      total: { type: Number, nullable: false, computed: raw`1`, stored: true },
    },
  });

  expect(entityTypesSource([Invoice])).toBe(
    [
      '// Generated by `uql-migrate types`. Do not edit.',
      '',
      "import type { Filled } from 'uql-orm';",
      '',
      'export interface Invoice {',
      '  id: number;',
      '  number: string;',
      '  status: Filled<string>;',
      '  issuedAt: Filled<Date>;',
      '  pdf?: Uint8Array;',
      '  note?: string | null;',
      '  readonly total: number;',
      '}',
      '',
    ].join('\n'),
  );
});
