import { getMeta } from '../../entity/index.js';
import { canonicalToTypeScript, resolveColumnCanonicalType } from '../../schema/canonicalType.js';
import type { EntityMeta, FieldMeta, RelationMeta, Type } from '../../type/index.js';
import { isToManyRelation, upperFirst } from '../../util/index.js';
import { isIdentifierName } from './sourceLiteral.js';

/**
 * A `.d.ts` for the entities as registered, so a shape that only exists at runtime reaches the
 * compiler too. Interfaces, not the entity classes `generate:from-db` writes: those are the source of
 * a schema, these describe one already defined elsewhere.
 */
export function entityTypesSource(entities: readonly Type<object>[]): string {
  const metas = [...entities]
    .map((entity) => getMeta(entity))
    .sort((a, b) => a.entity.name.localeCompare(b.entity.name));
  const names = interfaceNames(metas);

  const interfaces = metas.map((meta) => {
    const members = [
      ...Object.entries<FieldMeta | undefined>(meta.fields).map(([key, field]) => fieldMember(key, field)),
      ...Object.entries<RelationMeta | undefined>(meta.relations).map(
        ([key, rel]) => `  ${propertyName(key)}?: ${relationType(rel, names)};`,
      ),
    ];
    return `export interface ${names.get(meta.entity)} {\n${members.join('\n')}\n}`;
  });

  const imports = metas.some((meta) =>
    Object.values<FieldMeta | undefined>(meta.fields).some((field) => field && isFilledField(field)),
  )
    ? ["import type { Filled } from 'uql-orm';", '']
    : [];
  return ['// Generated by `uql-migrate types`. Do not edit.', '', ...imports, ...interfaces, ''].join('\n');
}

/**
 * One interface name per entity, settled before anything is written so a relation and its target
 * agree. A class minted at runtime is named after the content type it came from, which nothing stops
 * from carrying a dash or colliding with another once the dashes are gone - and either would emit a
 * file that does not compile.
 */
function interfaceNames(metas: readonly EntityMeta<object>[]): Map<Type<object>, string> {
  const taken = new Set<string>();
  return new Map(
    metas.map((meta) => {
      const base = identifier(upperFirst(meta.entity.name));
      let name = base;
      for (let n = 2; taken.has(name); n++) {
        name = `${base}${n}`;
      }
      taken.add(name);
      return [meta.entity, name];
    }),
  );
}

/** `text` as an identifier: what cannot be in one is dropped, and what cannot start one is prefixed. */
function identifier(text: string): string {
  const stripped = text.replace(/[^\p{ID_Continue}$\u200C\u200D]/gu, '');
  return isIdentifierName(stripped) ? stripped : `Entity${stripped}`;
}

/** A column name a property cannot hold - `hero-image` - is quoted rather than dropped. */
function propertyName(key: string): string {
  return isIdentifierName(key) ? key : JSON.stringify(key);
}

/**
 * A field as an entity class declares it: required where every read has it and an insert names it, a
 * key included, which an insert leaves out anyway; `Filled` where a default fills it; optional where a
 * read skips it (`eager: false`); `| null` where the column holds NULL; `readonly` where it is computed.
 */
function fieldMember(key: string, field: FieldMeta | undefined): string {
  const type = fieldType(field);
  const name = propertyName(key);
  if (!field) {
    return `  ${name}?: ${type};`;
  }
  if (isFilledField(field)) {
    return `  ${name}: Filled<${type}>;`;
  }
  const written = field.computed === undefined ? '' : 'readonly ';
  if (!field.isId && field.nullable !== false) {
    return `  ${written}${name}?: ${type} | null;`;
  }
  const optional = !field.isId && field.eager === false;
  return `  ${written}${name}${optional ? '?' : ''}: ${type};`;
}

/** A non-null field a default or `onInsert` fills, which every read has and an insert may leave out. */
function isFilledField(field: FieldMeta): boolean {
  return (
    !field.isId &&
    field.nullable === false &&
    field.eager !== false &&
    field.computed === undefined &&
    (field.defaultValue !== undefined || field.onInsert !== undefined)
  );
}

/**
 * The property type a column reads back as, resolved the way the DDL resolves it - so a foreign key
 * reports the type of the key it points at rather than the fallback its own options carry.
 */
function fieldType(field: FieldMeta | undefined): string {
  return field ? canonicalToTypeScript(resolveColumnCanonicalType(field)) : 'unknown';
}

/**
 * A relation is the related interface, a list where the cardinality says so - and `unknown` where the
 * target is outside the set, since naming an interface the file does not declare would not compile.
 */
function relationType(relation: RelationMeta | undefined, names: ReadonlyMap<Type<object>, string>): string {
  const target = relation && names.get(relation.entity());
  if (!target) {
    return 'unknown';
  }
  return isToManyRelation(relation) ? `${target}[]` : target;
}
