import { transform } from 'esbuild';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { PgQuerierPool } from '../../postgres/pgQuerierPool.js';
import { assertDefined, postgresConnection, provisioningTimeout } from '../../test/index.js';
import { PostgresSchemaIntrospector } from '../introspection/postgresIntrospector.js';
import { EntityCodeGenerator } from './entityCodeGenerator.js';

const TABLE = 'codegen_from_db';

/**
 * `generate:from-db` against a real catalogue, whose reports hand-built `IndexNode`s do not reproduce:
 * an expression past 63 characters, a reprint with newlines, an access method on every index.
 */
describe('generate:from-db (PostgreSQL)', () => {
  const pool = new PgQuerierPool(postgresConnection());
  let code: string;

  beforeAll(async () => {
    await pool.withQuerier(async (querier) => {
      await querier.run(`DROP TABLE IF EXISTS "${TABLE}"`);
      await querier.run(
        `CREATE TABLE "${TABLE}" (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
           email TEXT, name TEXT, status TEXT, "tenantId" BIGINT, is_enabled BOOLEAN, "deletedAt" TIMESTAMPTZ,
           "nameUpper" TEXT GENERATED ALWAYS AS (upper(name)) STORED)`,
      );
      await querier.run(`CREATE INDEX cfd_plain ON "${TABLE}" (status)`);
      await querier.run(`CREATE UNIQUE INDEX cfd_unique ON "${TABLE}" ("tenantId")`);
      await querier.run(`CREATE INDEX cfd_expr ON "${TABLE}" ((to_tsvector('english', name || ' ' || status)))`);
      await querier.run(`CREATE INDEX cfd_partial ON "${TABLE}" (email) WHERE "deletedAt" IS NULL`);
      await querier.run(`CREATE INDEX cfd_covering ON "${TABLE}" ("tenantId") INCLUDE (status)`);
    });

    // Only this table: the suites share one database, and scanning every relation while another
    // drops one is how Postgres comes back with "could not open relation with OID".
    const ast = await new PostgresSchemaIntrospector(pool).introspect([TABLE]);
    const generated = new EntityCodeGenerator(ast).generateForTable(TABLE);
    assertDefined(generated);
    code = generated.code;
  }, provisioningTimeout);

  afterAll(async () => {
    await pool.withQuerier((querier) => querier.run(`DROP TABLE IF EXISTS "${TABLE}"`));
    await pool.end();
  }, provisioningTimeout);

  it('should generate source that parses as TypeScript', async () => {
    await expect(transform(code, { loader: 'ts' })).resolves.toBeDefined();
  });

  // The expression comes back as Postgres reprints it, which is what the entity then declares.
  it('should carry a stored generated column as a computed field the database owns', () => {
    expect(code).toContain('computed: raw`upper(name)`, stored: true');
    expect(code).toContain('readonly nameUpper?');
  });

  it('should carry a plain index on the field and everything else in its own decorator', () => {
    expect(code).toContain("index: 'cfd_plain'");
    expect(code).toContain("{ name: 'cfd_unique', unique: true }");
  });

  // `btree` is reported on every index Postgres has, so writing it would put it in every entity.
  it('should leave the default access method out', () => {
    expect(code).not.toContain('btree');
  });

  it('should write the expression whole, however long the catalogue prints it', () => {
    expect(code).toContain(
      "=> [raw`to_tsvector('english'::regconfig, (name || ' '::text) || status)`], { name: 'cfd_expr' })",
    );
  });

  /**
   * A property the transformer had to rewrite maps to a column the database does not have unless the
   * decorator says which one it is, and a column that is already camelCase must not be rewritten at all.
   */
  it('should name the column wherever the property cannot', () => {
    expect(code).toContain("@Field({ name: 'is_enabled'");
    expect(code).toContain('isEnabled?: boolean;');
    expect(code).toContain('tenantId?: number;');
    expect(code).not.toContain('tenantid');
    expect(code).not.toContain("name: 'tenantId'");
  });

  it('should write a partial predicate and a covering list', () => {
    expect(code).toContain('where: raw`"deletedAt" IS NULL`');
    expect(code).toMatch(/\{ name: 'cfd_covering', include: \((\w+)\) => \[\1\.status\] \}/);
  });
});
