import { neonConfig, types } from '@neondatabase/serverless';
import { expect } from 'vitest';
import ws from 'ws';
import { PgLikeQuerierIt } from '../querier/pgLikeQuerier-test.js';
import { createSpec } from '../test/index.js';
import { NeonQuerierPool } from './neonQuerierPool.js';

// Real Neon always fronts Postgres over a secure websocket; locally there's no hosted project to
// hit, so `neon-wsproxy` (docker-compose) stands in as a plain websocket->TCP proxy in front of
// the same Postgres container the `postgres`/`cockroachdb` suites use. `forceDisablePgSSL`
// defaults to `true` already, which is correct here (the local Postgres doesn't speak TLS).
neonConfig.webSocketConstructor = ws;
neonConfig.useSecureWebSocket = false;
neonConfig.wsProxy = (host, port) => `localhost:5433/v1?address=${host}:${port}`;
// Required for SCRAM auth to succeed against a plain (non-Neon) Postgres through a local proxy -
// without it the client offers a SASL mechanism the server rejects.
neonConfig.pipelineConnect = false;
neonConfig.pipelineTLS = false;

// `@neondatabase/serverless` has its own type-parser registry, separate from `pg`'s (see
// `test/pgTypeParsers.util.ts`) - same INT8/FLOAT8/NUMERIC-as-JS-number fix, different package.
types.setTypeParser(types.builtins['INT8'], (value: string) => Number.parseInt(value, 10));
types.setTypeParser(types.builtins['FLOAT8'], (value: string) => Number.parseFloat(value));
types.setTypeParser(types.builtins['NUMERIC'], (value: string) => Number.parseFloat(value));

export class NeonQuerierIt extends PgLikeQuerierIt {
  constructor() {
    super(
      new NeonQuerierPool({
        host: 'postgres',
        port: 5432,
        user: 'test',
        password: 'test',
        database: 'test_neon',
      }),
      'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
    );
  }

  override async beforeAll() {
    const querier = await this.pool.getQuerier();
    try {
      // pgvector extension must exist before any vector column can be created
      await querier.run('CREATE EXTENSION IF NOT EXISTS vector');
    } finally {
      await querier.release();
    }
    await super.beforeAll();
  }

  /** Same Postgres backend as `pgQuerier.test.ts` (just tunneled through wsproxy), so `xmax` still works. */
  protected override assertUpsertCreatedOnInsert(created: boolean | undefined): void {
    expect(created).toBe(true);
  }

  protected override assertUpsertCreatedOnUpdate(created: boolean | undefined): void {
    expect(created).toBe(false);
  }
}

createSpec(new NeonQuerierIt());
