import { types } from 'pg';
import { expect } from 'vitest';
import { AbstractSqlQuerierIt } from '../querier/abstractSqlQuerier-test.js';
import { createSpec, TaxCategory } from '../test/index.js';
import { PgQuerierPool } from './pgQuerierPool.js';

types.setTypeParser(types.builtins.INT8, (value: string) => Number.parseInt(value, 10));
types.setTypeParser(types.builtins.FLOAT8, (value: string) => Number.parseFloat(value));
types.setTypeParser(types.builtins.NUMERIC, (value: string) => Number.parseFloat(value));

export class PostgresQuerierIt extends AbstractSqlQuerierIt {
  constructor() {
    super(
      new PgQuerierPool({
        host: '0.0.0.0',
        port: 5442,
        user: 'test',
        password: 'test',
        database: 'test',
      }),
      'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
    );
  }

  override async shouldUpsertOne() {
    const pk = '507f1f77bcf86cd799439011';

    const insertResult = await this.querier.upsertOne(TaxCategory, { pk: true }, { pk, name: 'Some Name C' });
    expect(insertResult.changes).toBeGreaterThanOrEqual(1);
    expect(insertResult.firstId).toBeDefined();
    expect(insertResult.created).toBe(true);

    const updateResult = await this.querier.upsertOne(TaxCategory, { pk: true }, { pk, name: 'Some Name D' });
    expect(updateResult.changes).toBeGreaterThanOrEqual(1);
    expect(updateResult.firstId).toBeDefined();
    expect(updateResult.created).toBe(false);

    const record = await this.querier.findOne(TaxCategory, { $select: { name: true }, $where: { pk } });
    expect(record).toMatchObject({ name: 'Some Name D' });
  }
}

createSpec(new PostgresQuerierIt());
