import { expect } from 'vitest';
import { PgLikeQuerierIt } from '../querier/pgLikeQuerier-test.js';
import { createSpec } from '../test/index.js';
import { configurePgNumericTypeParsers } from '../test/pgTypeParsers.util.js';
import { PgQuerierPool } from './pgQuerierPool.js';

configurePgNumericTypeParsers();

export class PostgresQuerierIt extends PgLikeQuerierIt {
  constructor() {
    super(
      new PgQuerierPool({
        host: '0.0.0.0',
        port: 5442,
        user: 'test',
        password: 'test',
        database: 'test_pg',
      }),
      'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
    );
  }

  override async beforeAll() {
    const querier = await this.pool.getQuerier();
    try {
      // pgvector extension must exist before any vector column can be created
      await querier.run('CREATE EXTENSION IF NOT EXISTS vector');
    } finally {
      await querier.release();
    }
    await super.beforeAll();
  }

  /** Postgres's `xmax` system column exposes the `created` flag on upsert. */
  protected override assertUpsertCreatedOnInsert(created: boolean | undefined): void {
    expect(created).toBe(true);
  }

  protected override assertUpsertCreatedOnUpdate(created: boolean | undefined): void {
    expect(created).toBe(false);
  }
}

createSpec(new PostgresQuerierIt());
