import type { DialectOptions } from '../dialect/abstractDialect.js';
import { AbstractSqlDialect } from '../dialect/abstractSqlDialect.js';
import { buildElemMatchConditions } from '../dialect/jsonArrayElemMatchUtils.js';
import { getMeta } from '../entity/index.js';
import {
  type DialectFeatures,
  type EntityMeta,
  type FieldOptions,
  type JsonColumnType,
  type JsonUpdateOp,
  type QueryComparisonOptions,
  type QueryConflictPaths,
  type QueryContext,
  type QueryOptions,
  QueryRaw,
  type QuerySizeComparisonOps,
  type QueryTextSearchOptions,
  type QueryVectorSearch,
  type SqlDialectName,
  type Type,
  type VectorDistance,
} from '../type/index.js';
import { escapeAnsiSqlLiteral } from '../util/ansiSqlLiteral.js';
import { hasKeys, isJsonType } from '../util/index.js';

/**
 * PostgreSQL dialect (AST, quoting, BIGINT IDENTITY PKs).
 * For node-pg use PgDialect. Neon, Bun SQL, and Cockroach use driver-specific subclasses.
 */
export class PostgresDialect extends AbstractSqlDialect {
  /** Default {@link DialectFeatures} before wire/driver-specific patches (e.g. {@link PgDialect}). */
  static readonly defaultDialectFeatures: DialectFeatures = {
    explicitJsonCast: false,
    nativeArrays: true,
    supportsJsonb: true,
    returning: true,
    ifNotExists: true,
    indexIfNotExists: true,
    dropTableCascade: true,
    renameColumn: true,
    foreignKeyAlter: true,
    columnComment: false,
    vectorIndexStyle: 'create',
    vectorSupportsLength: true,
    supportsTimestamptz: true,
    defaultStringAsText: true,
  };

  override readonly dialectName: SqlDialectName = 'postgres';

  override readonly quoteChar = '"';
  override readonly serialPrimaryKey: string = 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY';
  override readonly tableOptions = '';
  override readonly beginTransactionCommand = 'BEGIN';
  override readonly commitTransactionCommand = 'COMMIT';
  override readonly rollbackTransactionCommand = 'ROLLBACK';
  override readonly alterColumnStrategy = 'separate-clauses';
  override readonly insertIdStrategy = 'last';

  constructor(options: DialectOptions = {}) {
    super(PostgresDialect.defaultDialectFeatures, options);
  }

  override readonly vectorOpsClass: Readonly<Record<VectorDistance, string>> | undefined = {
    cosine: 'vector_cosine_ops',
    l2: 'vector_l2_ops',
    inner: 'vector_ip_ops',
    l1: 'vector_l1_ops',
    hamming: 'bit_hamming_ops',
  };

  override readonly vectorExtension: string | undefined = 'vector';

  override normalizeValue(value: unknown): unknown {
    if (value != null && typeof value === 'object' && Array.isArray(value)) {
      return this.features.nativeArrays ? value : toPgArray(value);
    }
    return super.normalizeValue(value);
  }

  override placeholder(index: number): string {
    return `$${index}`;
  }

  override insert<E>(ctx: QueryContext, entity: Type<E>, payload: E | E[], opts?: QueryOptions): void {
    super.insert(ctx, entity, payload, opts);
    ctx.append(' ' + this.returningId(entity));
  }

  override upsert<E>(ctx: QueryContext, entity: Type<E>, conflictPaths: QueryConflictPaths<E>, payload: E | E[]): void {
    const meta = getMeta(entity);
    const update = this.getUpsertUpdateAssignments(ctx, meta, conflictPaths, payload, (name) => `EXCLUDED.${name}`);
    const keysStr = this.getUpsertConflictPathsStr(meta, conflictPaths);
    const onConflict = update ? `DO UPDATE SET ${update}` : 'DO NOTHING';
    super.insert(ctx, entity, payload);
    // xmax system column is 0 for newly inserted rows, non-zero for updated rows (MVCC).
    ctx.append(
      ` ON CONFLICT (${keysStr}) ${onConflict} ${this.returningId(entity)}, (xmax = 0) AS ${this.escapeId('_created')}`,
    );
  }

  override compare<E>(
    ctx: QueryContext,
    entity: Type<E>,
    key: string,
    val: unknown,
    opts: QueryComparisonOptions = {},
  ): void {
    if (key === '$text') {
      const meta = getMeta(entity);
      const search = val as QueryTextSearchOptions<E>;
      const fields = (search.$fields ?? [])
        .map((fKey) => {
          const field = meta.fields[fKey];
          const columnName = this.resolveColumnName(fKey, field!);
          return this.escapeId(columnName);
        })
        .join(` || ' ' || `);
      ctx.append(`to_tsvector(${fields}) @@ to_tsquery(`);
      ctx.addValue(search.$value);
      ctx.append(')');
      return;
    }
    super.compare(ctx, entity, key, val, opts);
  }

  protected override jsonAll(ctx: QueryContext, jsonField: string, value: unknown): string {
    return `${jsonField} @> ${this.jsonVal(ctx, value)}`;
  }

  protected override jsonSize(ctx: QueryContext, jsonField: string, value: number | QuerySizeComparisonOps): string {
    const tmpCtx = this.createContext();
    this.buildSizeComparison(tmpCtx, () => tmpCtx.append(`jsonb_array_length(${jsonField})`), value);
    ctx.pushValue(...tmpCtx.values);
    return tmpCtx.sql;
  }

  protected override jsonElemMatch(ctx: QueryContext, jsonField: string, match: Record<string, unknown>): string {
    // Primitive element match: keys are operators (e.g. { $startsWith: 'ad' } on a string[])
    const isPrimitiveElement = Object.keys(match).some((k) => k.startsWith('$'));
    if (isPrimitiveElement) {
      const conditions = Object.entries(match).map(([op, opVal]) =>
        this.buildJsonFieldCondition(ctx, () => 'elem', '', op, opVal),
      );
      return `EXISTS (SELECT 1 FROM jsonb_array_elements_text(${jsonField}) AS elem WHERE ${conditions.join(' AND ')})`;
    }

    const hasOperators = Object.values(match).some(
      (v) => v && typeof v === 'object' && !Array.isArray(v) && Object.keys(v).some((k) => k.startsWith('$')),
    );

    if (!hasOperators) {
      return `${jsonField} @> ${this.jsonVal(ctx, [match])}`;
    }

    const conditions = buildElemMatchConditions(
      match,
      (field, op, opVal) =>
        this.buildJsonFieldCondition(ctx, (f) => `elem->>'${this.escapeJsonKey(f)}'`, field, op, opVal),
      (field, val) => `elem->>'${this.escapeJsonKey(field)}' = ${this.addValue(ctx.values, val)}`,
    );

    return `EXISTS (SELECT 1 FROM jsonb_array_elements(${jsonField}) AS elem WHERE ${conditions.join(' AND ')})`;
  }

  protected override get regexpOp(): string {
    return '~';
  }

  protected override ilikeExpr(f: string, ph: string): string {
    return `${f} ILIKE ${ph}`;
  }

  protected override get neOp(): string {
    return 'IS DISTINCT FROM';
  }

  protected override formatIn(ctx: QueryContext, values: unknown[], negate: boolean): string {
    if (values.length === 0) return negate ? ' NOT IN (NULL)' : ' IN (NULL)';
    const ph = this.addValue(ctx.values, values);
    return negate ? ` <> ALL(${ph})` : ` = ANY(${ph})`;
  }

  protected override numericCast(expr: string): string {
    return `(${expr})::numeric`;
  }

  protected override formatPersistableValue<E>(ctx: QueryContext, field: FieldOptions, value: unknown): void {
    if (value instanceof QueryRaw) {
      super.formatPersistableValue(ctx, field, value);
      return;
    }
    if (isJsonType(field.type)) {
      ctx.append(this.jsonVal(ctx, value, field.type as JsonColumnType));
      return;
    }
    if (field.type === 'vector' && Array.isArray(value)) {
      ctx.addValue(`[${value.join(',')}]`);
      ctx.append('::vector');
      return;
    }
    super.formatPersistableValue(ctx, field, value);
  }

  /** pgvector distance operators. */
  private static readonly VECTOR_OPS: Record<VectorDistance, string> = {
    cosine: '<=>',
    l2: '<->',
    inner: '<#>',
    l1: '<+>',
    hamming: '<~>',
  };

  /** Emit a pgvector distance expression: `"col" <op> $N::<vectorType>`. */
  protected override appendVectorSort<E>(
    ctx: QueryContext,
    meta: EntityMeta<E>,
    key: string,
    search: QueryVectorSearch,
  ): void {
    const { colName, distance, vectorCast } = this.resolveVectorSortParams(meta, key, search);
    const op = PostgresDialect.VECTOR_OPS[distance];
    ctx.append(`${this.escapeId(colName)} ${op} `);
    ctx.addValue(`[${search.$vector.join(',')}]`);
    ctx.append(`::${vectorCast}`);
  }

  protected override formatJsonUpdate<E>(ctx: QueryContext, escapedCol: string, value: JsonUpdateOp<E>): void {
    let expr = escapedCol;
    if (hasKeys(value.$merge)) {
      expr = `COALESCE(${escapedCol}, '{}'::jsonb) || ${this.jsonVal(ctx, value.$merge)}`;
    }
    if (hasKeys(value.$push)) {
      const push = value.$push as Record<string, unknown>;
      for (const [key, v] of Object.entries(push)) {
        const currentExpr = expr;
        const ph = this.jsonVal(ctx, v);
        expr = `jsonb_set(${currentExpr}, '{${this.escapeJsonKey(key)}}', COALESCE((${currentExpr})->'${this.escapeJsonKey(
          key,
        )}', '[]'::jsonb) || jsonb_build_array(${ph}))`;
      }
    }
    if (value.$unset?.length) {
      for (const key of value.$unset) {
        expr = `(${expr}) - '${this.escapeJsonKey(key)}'`;
      }
    }
    ctx.append(`${escapedCol} = ${expr}`);
  }

  /**
   * Helper to add a JSON value to context with appropriate stringification and cast.
   */
  private jsonVal(ctx: QueryContext, value: unknown, type: JsonColumnType = 'jsonb'): string {
    if (value instanceof QueryRaw) return this.addValue(ctx.values, value);
    if (value == null) return `${this.addValue(ctx.values, null)}::${type}`;

    const json = JSON.stringify(value);
    const ph = this.addValue(ctx.values, json);
    return this.features.explicitJsonCast ? `(${ph}::text)::${type}` : `${ph}::${type}`;
  }

  override escape(value: unknown): string {
    return escapeAnsiSqlLiteral(value);
  }
}

/**
 * Converts a JS array to a Postgres array literal string: `{"val1","val2"}`.
 * Safely handles nesting and escaping of special characters.
 */
function toPgArray(arr: unknown[]): string {
  const elements = arr.map((val) => {
    if (val == null) return 'NULL';
    if (Array.isArray(val)) return toPgArray(val);
    if (typeof val === 'boolean') return val ? 'true' : 'false';
    if (val instanceof Uint8Array || (typeof Buffer !== 'undefined' && Buffer.isBuffer(val))) {
      const hex = Array.from(val)
        .map((b) => b.toString(16).padStart(2, '0'))
        .join('');
      return `"\\\\x${hex}"`;
    }
    const str = String(val);
    const escaped = str.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
    return `"${escaped}"`;
  });
  return `{${elements.join(',')}}`;
}
