import { describeMigratorSync } from './migrator-sync-test.js';

describeMigratorSync('cockroachdb', {
  serialIdColumn: '"id" INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
  textType: 'TEXT',
  doubleType: 'DOUBLE PRECISION',
  keyColumnType: 'INT8',
  keepsComments: true,
});
