import { describeMigratorSync } from './migrator-sync-test.js';

describeMigratorSync('pglite', {
  serialIdColumn: '"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
  textType: 'TEXT',
  doubleType: 'DOUBLE PRECISION',
  keyColumnType: 'BIGINT',
  keepsComments: true,
});
