import { v7 as uuidv7 } from 'uuid';
import { afterAll, describe, expect, it } from 'vitest';
import { CockroachDialect } from '../cockroachdb/cockroachDialect.js';
import { Entity, Field, getMeta, Id, Index, ManyToOne, removeEntity, Trigger } from '../entity/index.js';
import { MariaDialect } from '../maria/mariaDialect.js';
import { MsSqlDialect } from '../mssql/mssqlDialect.js';
import { MySqlDialect } from '../mysql/mysqlDialect.js';
import { SnakeCaseNamingStrategy } from '../namingStrategy/snakeCaseNamingStrategy.js';
import { PostgresDialect } from '../postgres/postgresDialect.js';
import { SchemaAST } from '../schema/schemaAST.js';
import type { IndexNode, TableNode } from '../schema/types.js';
import { SqliteDialect } from '../sqlite/sqliteDialect.js';
import { assertDefined, mockSqlTableNode, mockTableNode } from '../test/index.js';
import type { ColumnSchema, SchemaDiff } from '../type/index.js';
import { raw } from '../util/index.js';
import type { FullColumnDefinition, TableDefinition } from './builder/types.js';
import { buildEntityAST, SqlSchemaGenerator } from './schemaGenerator.js';

// Test entities
@Entity()
class TestUser {
  @Id({ type: Number })
  id?: number;

  @Field({ type: String, length: 100 })
  name?: string | null;

  @Field({ type: String, unique: true })
  email?: string | null;

  @Field({ type: String, nullable: false })
  password?: string;

  @Field({ type: Number, onInsert: Date.now })
  createdAt?: number | null;
}

@Entity({ name: 'blog_posts' })
class TestPost {
  @Id({ type: String, onInsert: uuidv7, length: 36 })
  id?: string;

  @Field({ type: String })
  title?: string | null;

  @Field({ type: String, columnType: 'text' })
  content?: string | null;

  @Field({ type: 'jsonb' })
  metadata?: Record<string, unknown> | null;

  @Field({ references: () => TestUser })
  authorId?: number | null;

  @ManyToOne({ entity: () => TestUser, references: (testPost) => testPost.authorId })
  author?: TestUser;
}

@Entity()
class SqliteIndexedEntity {
  @Id({ type: Number }) id?: number;
  @Field({ type: String, index: true })
  slug?: string | null;
}

describe('SqlSchemaGenerator (Postgres)', () => {
  const generator = new SqlSchemaGenerator(new PostgresDialect());

  it('should generate CREATE TABLE for simple entity', () => {
    const sql = generator.generateCreateSchema([TestUser]).join('\n');

    expect(sql).toContain('CREATE TABLE "TestUser"');
    expect(sql).toContain('"id" BIGINT GENERATED BY DEFAULT AS IDENTITY');
    expect(sql).toContain('"name" VARCHAR(100)');
    expect(sql).toContain('"email" TEXT UNIQUE');
    expect(sql).toContain('"password" TEXT NOT NULL');
    expect(sql).toContain('"createdAt"');
  });

  it('should generate CREATE TABLE with UUID primary key', () => {
    const sql = generator.generateCreateSchema([TestPost]).join('\n');

    expect(sql).toContain('CREATE TABLE "blog_posts"');
    expect(sql).toContain('"id" VARCHAR(36)');
    expect(sql).toContain('"title" TEXT');
    expect(sql).toContain('"content" TEXT');
    expect(sql).toContain('"metadata" JSONB');
    expect(sql).toContain('"authorId" BIGINT');
  });

  it('should generate DROP TABLE statement', () => {
    const sql = generator.generateDropTable('TestUser', { ifExists: true });

    expect(sql).toBe('DROP TABLE IF EXISTS "TestUser";');
  });
  /** An `embeddings` table of an id and an embedding, with the vector indexes given. */
  function buildVectorTableNode(indexes: Partial<IndexNode>[]): TableNode {
    const table = mockTableNode('embeddings', [
      { name: 'id', type: { category: 'integer' }, nullable: false, isPrimaryKey: true, isAutoIncrement: true },
      { name: 'embedding', type: { category: 'vector', length: 1536 }, nullable: false },
    ]);
    table.indexes.push(
      ...indexes.map((idx) => ({
        name: 'vec_idx',
        table,
        entries: [{ column: 'embedding' }],
        unique: false,
        type: 'vector' as const,
        ...idx,
      })),
    );
    return table;
  }

  /**
   * MySQL scores a column by `MATCH` over exactly that column, which only a `FULLTEXT` index of its own
   * serves, so a weighted index declares one per column heavier than its lightest; Postgres needs none.
   */
  it('should declare a fulltext index for each heavier column where the engine scores through one', () => {
    @Entity()
    @Index((doc) => [{ column: doc.title, weight: 3 }, doc.summary, doc.body], { type: 'fulltext' })
    class WeightedDoc {
      @Id({ type: Number }) id?: number;
      @Field({ type: String }) title?: string | null;
      @Field({ type: String }) summary?: string | null;
      @Field({ type: String }) body?: string | null;
    }
    const indexes = (dialect: MySqlDialect | PostgresDialect) =>
      new SqlSchemaGenerator(dialect)
        .buildAST([WeightedDoc])
        .getTable('WeightedDoc')
        ?.indexes.map(({ name, entries, type }) => ({ name, columns: entries.map((entry) => entry.column), type }));

    expect(indexes(new MySqlDialect())).toEqual([
      { name: 'WeightedDoc__title_summary_body_idx', columns: ['title', 'summary', 'body'], type: 'fulltext' },
      { name: 'WeightedDoc__title_score_idx', columns: ['title'], type: 'fulltext' },
    ]);
    expect(indexes(new PostgresDialect())).toEqual([
      { name: 'WeightedDoc__title_summary_body_idx', columns: ['title', 'summary', 'body'], type: 'fulltext' },
    ]);
  });

  /** InnoDB fills a fulltext index added beside another on a loaded table only once the table is optimized. */
  it('should optimize a MySQL-family table a fulltext index is added to, and no other', () => {
    const diff: SchemaDiff = {
      tableName: 'docs',
      type: 'alter',
      indexesToAdd: [
        { name: 'docs_title_idx', entries: [{ column: 'title' }], unique: false, type: 'fulltext' },
        { name: 'docs_slug_idx', entries: [{ column: 'slug' }], unique: false },
      ],
    };
    expect(new SqlSchemaGenerator(new MySqlDialect()).generateAlterTable(diff)).toEqual([
      'CREATE FULLTEXT INDEX `docs_title_idx` ON `docs` (`title`);',
      'OPTIMIZE TABLE `docs`;',
      'CREATE INDEX `docs_slug_idx` ON `docs` (`slug`);',
    ]);
    expect(new SqlSchemaGenerator(new PostgresDialect()).generateAlterTable(diff)).not.toContain(
      expect.stringContaining('OPTIMIZE'),
    );
  });

  it('should emit CREATE VECTOR INDEX for MariaDB', () => {
    const mariaGenerator = new SqlSchemaGenerator(new MariaDialect());
    const statements = mariaGenerator.generateCreateTableFromNode(buildVectorTableNode([{}]));
    expect(statements.at(-1)).toBe('CREATE VECTOR INDEX `vec_idx` ON `embeddings` (`embedding`);');
    expect(statements[0]).not.toContain('VECTOR INDEX');
    expect(statements.join('\n')).not.toContain('CREATE EXTENSION');
  });

  // Verified against MariaDB 12.3: a nullable column makes the whole statement fail with
  // "All parts of a VECTOR index must be NOT NULL", whatever the entity declared.
  it('should force NOT NULL on a MariaDB indexed vector column', () => {
    const mariaGenerator = new SqlSchemaGenerator(new MariaDialect());
    const table = buildVectorTableNode([{ distance: 'cosine' }]);
    (table.columns.get('embedding') as { nullable: boolean }).nullable = true;

    const sql = mariaGenerator.generateCreateTableFromNode(table).join('\n');

    expect(sql).toContain('`embedding` VECTOR(1536) NOT NULL');
  });

  it('should emit CREATE VECTOR INDEX with M and DISTANCE for MariaDB', () => {
    const mariaGenerator = new SqlSchemaGenerator(new MariaDialect());
    const sql = mariaGenerator
      .generateCreateTableFromNode(buildVectorTableNode([{ distance: 'cosine', m: 8 }]))
      .join('\n');
    expect(sql).toContain('ON `embeddings` (`embedding`) M=8 DISTANCE=cosine;');
  });

  it('should emit CREATE VECTOR INDEX with l2 as euclidean for MariaDB', () => {
    const mariaGenerator = new SqlSchemaGenerator(new MariaDialect());
    const sql = mariaGenerator.generateCreateTableFromNode(buildVectorTableNode([{ distance: 'l2' }])).join('\n');
    expect(sql).toContain('ON `embeddings` (`embedding`) DISTANCE=euclidean;');
  });

  // pgvector's index types are not access methods MariaDB has, so they are named rather than
  // compiled into a ` USING hnsw` the server can only answer with a syntax error.
  it.each(['hnsw', 'ivfflat'] as const)('should reject a %s index on MariaDB', (type) => {
    const mariaGenerator = new SqlSchemaGenerator(new MariaDialect());
    expect(() => mariaGenerator.generateCreateTableFromNode(buildVectorTableNode([{ type }]))).toThrow(
      `mariadb has no ${type} index (index "vec_idx"); declare type: 'vector' instead`,
    );
  });

  it('should throw for a MariaDB vector index with an unsupported distance metric, not silently default to euclidean', () => {
    const mariaGenerator = new SqlSchemaGenerator(new MariaDialect());
    expect(() => mariaGenerator.generateCreateTableFromNode(buildVectorTableNode([{ distance: 'inner' }]))).toThrow(
      'mariadb does not support vector distance metric: inner',
    );
  });

  it('should not resolve a vector distance keyword via the prototype chain for an unvalidated distance value', () => {
    const mariaGenerator = new SqlSchemaGenerator(new MariaDialect());
    expect(() =>
      // @ts-expect-error: an inherited property, which a plain lookup would take for a metric
      mariaGenerator.generateCreateTableFromNode(buildVectorTableNode([{ distance: 'toString' }])),
    ).toThrow('mariadb does not support vector distance metric: toString');
  });

  it('should prepend CREATE EXTENSION for Postgres tables with vector columns', () => {
    const sql = generator.generateCreateTableFromNode(buildVectorTableNode([])).join('\n');
    expect(sql).toMatch(/^CREATE EXTENSION IF NOT EXISTS vector;/);
    expect(sql).toContain('CREATE TABLE');
  });

  it('should generate CREATE TABLE with IF NOT EXISTS', () => {
    const sql = generator.generateCreateSchema([TestUser], { ifNotExists: true }).join('\n');
    expect(sql).toContain('CREATE TABLE IF NOT EXISTS "TestUser"');
  });

  /** A table created only if missing creates its indexes the same way, or re-creating a schema fails on the first. */
  it('should create a table indexes IF NOT EXISTS along with the table', () => {
    const guarded = generator.generateCreateSchema([TestUser, TestPost], { ifNotExists: true }).join('\n');
    const plain = generator.generateCreateSchema([TestUser, TestPost]).join('\n');

    expect(guarded).toContain('CREATE INDEX IF NOT EXISTS "blog_posts__authorId_idx" ON "blog_posts" ("authorId");');
    expect(plain).toContain('CREATE INDEX "blog_posts__authorId_idx" ON "blog_posts" ("authorId");');
  });

  it('should handle already-typed column schemas', () => {
    const sql = generator.generateAlterTable({
      tableName: 'users',
      type: 'alter',
      columnsToAdd: [
        {
          name: 'profile_data',
          type: 'JSONB',
          nullable: true,
          isPrimaryKey: false,
          isAutoIncrement: false,
          isUnique: false,
        },
      ],
    });
    // Should NOT be JSONB(JSONB)
    expect(sql[0]).toContain('ADD COLUMN "profile_data" JSONB');
    expect(sql[0]).not.toContain('JSONB(');
  });

  it('should generate ALTER TABLE DOWN statements for column additions', () => {
    const sql = generator.generateAlterTableDown({
      tableName: 'users',
      type: 'alter',
      columnsToAdd: [
        {
          name: 'profile_data',
          type: 'JSONB',
          nullable: true,
          isPrimaryKey: false,
          isAutoIncrement: false,
          isUnique: false,
        },
      ],
    });
    expect(sql[0]).toBe('ALTER TABLE "users" DROP COLUMN "profile_data";');
  });

  it('should generate ALTER TABLE DOWN statements for column alterations', () => {
    const sql = generator.generateAlterTableDown({
      tableName: 'users',
      type: 'alter',
      columnsToAlter: [
        {
          from: {
            name: 'age',
            type: 'INTEGER',
            nullable: true,
            isPrimaryKey: false,
            isAutoIncrement: false,
            isUnique: false,
          },
          to: {
            name: 'age',
            type: 'BIGINT',
            nullable: false,
            isPrimaryKey: false,
            isAutoIncrement: false,
            isUnique: false,
          },
        },
      ],
    });
    expect(sql.length).toBeGreaterThan(0);
    expect(sql[0]).toContain('ALTER TABLE');
    expect(sql[0]).toContain('"age"');
    expect(sql[0]).toContain('INTEGER');
  });

  it('should generate ALTER TABLE DOWN statements for index additions', () => {
    const sql = generator.generateAlterTableDown({
      tableName: 'users',
      type: 'alter',
      indexesToAdd: [{ name: 'users__email_idx', entries: [{ column: 'email' }], unique: true }],
    });
    expect(sql[0]).toBe('DROP INDEX IF EXISTS "users__email_idx";');
  });

  it('should add TODO comment for dropped columns', () => {
    const sql = generator.generateAlterTableDown({
      tableName: 'users',
      type: 'alter',
      columnsToDrop: ['old_column'],
    });
    expect(sql[0]).toContain('TODO');
  });

  it('should drop an index before recreating one under its name, and reverse both on the way down', () => {
    const diff: SchemaDiff = {
      tableName: 'users',
      type: 'alter',
      indexesToDrop: [{ name: 'lookup', entries: [{ column: 'name' }], unique: false }],
      indexesToAdd: [{ name: 'lookup', entries: [{ column: 'name' }, { column: 'email' }], unique: false }],
    };

    expect(generator.generateAlterTable(diff)).toEqual([
      'DROP INDEX IF EXISTS "lookup";',
      'CREATE INDEX IF NOT EXISTS "lookup" ON "users" ("name", "email");',
    ]);
    expect(generator.generateAlterTableDown(diff)).toEqual([
      'DROP INDEX IF EXISTS "lookup";',
      'CREATE INDEX IF NOT EXISTS "lookup" ON "users" ("name");',
    ]);
  });

  it('should generate ALTER TABLE statements for dropping columns and indexes', () => {
    const sql = generator.generateAlterTable({
      tableName: 'users',
      type: 'alter',
      columnsToDrop: ['old_col'],
      indexesToDrop: [{ name: 'old_idx', entries: [{ column: 'old_col' }], unique: false }],
      indexesToAdd: [{ name: 'new_idx', entries: [{ column: 'name' }], unique: false }],
    });
    expect(sql).toEqual([
      'DROP INDEX IF EXISTS "old_idx";',
      'ALTER TABLE "users" DROP COLUMN "old_col";',
      'CREATE INDEX IF NOT EXISTS "new_idx" ON "users" ("name");',
    ]);
  });
});

describe('SqlSchemaGenerator (MySQL)', () => {
  const generator = new SqlSchemaGenerator(new MySqlDialect());

  /** MySQL's `CREATE INDEX` takes no `IF NOT EXISTS`, so a guarded table's indexes stay plain there. */
  it('should leave a table indexes unguarded where the engine cannot guard one', () => {
    const sql = generator.generateCreateSchema([TestUser, TestPost], { ifNotExists: true }).join('\n');

    expect(sql).toContain('CREATE TABLE IF NOT EXISTS `blog_posts`');
    expect(sql).not.toContain('INDEX IF NOT EXISTS');
  });

  it('should generate CREATE TABLE for simple entity', () => {
    const sql = generator.generateCreateSchema([TestUser]).join('\n');

    expect(sql).toContain('CREATE TABLE `TestUser`');
    expect(sql).toContain('`id` BIGINT AUTO_INCREMENT');
    expect(sql).toContain('`name` VARCHAR(100)');
    expect(sql).toContain('`email` VARCHAR(255) UNIQUE');
    expect(sql).toContain('ENGINE=InnoDB');
  });

  it('should generate boolean as TINYINT(1)', () => {
    const boolType = generator.getSqlType({ type: Boolean });
    expect(boolType).toBe('TINYINT(1)');
  });

  it('should generate DROP INDEX with ON table', () => {
    const sql = generator.generateDropIndex('users', 'email_idx');
    expect(sql).toBe('DROP INDEX `email_idx` ON `users`;');
  });
});

describe('SqlSchemaGenerator (SQLite)', () => {
  const generator = new SqlSchemaGenerator(new SqliteDialect());

  it('should generate CREATE TABLE for simple entity', () => {
    const sql = generator.generateCreateSchema([TestUser]).join('\n');

    expect(sql).toContain('CREATE TABLE `TestUser`');
    expect(sql).toContain('`id` INTEGER PRIMARY KEY AUTOINCREMENT');
    expect(sql).toContain('`name` TEXT');
    expect(sql).toContain('`email` TEXT UNIQUE');
  });

  it('should use TEXT for most types (SQLite dynamic typing)', () => {
    expect(generator.getSqlType({ columnType: 'varchar' })).toBe('TEXT');
    expect(generator.getSqlType({ columnType: 'json' })).toBe('TEXT');
    expect(generator.getSqlType({ columnType: 'uuid' })).toBe('TEXT');
  });

  it('should use INTEGER for numeric types', () => {
    expect(generator.getSqlType({ columnType: 'int' })).toBe('INTEGER');
    expect(generator.getSqlType({ columnType: 'bigint' })).toBe('INTEGER');
    expect(generator.getSqlType({ type: Boolean })).toBe('INTEGER');
  });

  it('should split non-inline indexes into statements of their own', () => {
    const stmts = generator.generateCreateSchema([SqliteIndexedEntity]);
    expect(stmts).toHaveLength(2);
    expect(stmts[0]).toMatch(/^CREATE TABLE `SqliteIndexedEntity`/);
    expect(stmts[1]).toMatch(/^CREATE INDEX `SqliteIndexedEntity__slug_idx`/);
  });
});

describe('SqlSchemaGenerator Integration', () => {
  const generator = new SqlSchemaGenerator(new PostgresDialect());

  it('should generate CREATE TABLE from TableNode', () => {
    const table = mockTableNode('users', [
      {
        name: 'id',
        type: { category: 'integer', size: 'big' },
        isPrimaryKey: true,
        isAutoIncrement: true,
        nullable: false,
      },
      { name: 'name', type: { category: 'string', length: 100 } },
    ]);

    const sql = generator.generateCreateTableFromNode(table).join('\n');
    expect(sql).toContain('CREATE TABLE "users"');
    expect(sql).toContain('"id" BIGINT GENERATED BY DEFAULT AS IDENTITY');
    expect(sql).toContain('"name" VARCHAR(100)');
  });

  it('should generate CREATE INDEX from IndexNode', () => {
    const table = mockTableNode('users', [{ name: 'name' }]);
    const index: IndexNode = {
      name: 'name_idx',
      table,
      entries: [{ column: 'name' }],
      unique: true,
    };
    const sql = generator.generateCreateIndexFromNode(index);
    expect(sql).toBe('CREATE UNIQUE INDEX "name_idx" ON "users" ("name");');
  });

  // The predicate reaches the index, so the soft-delete pattern stays unique among live rows only.
  it('should carry a partial index predicate from IndexNode', () => {
    const table = mockTableNode('users', [{ name: 'email' }]);
    const index: IndexNode = {
      name: 'live_email_idx',
      table,
      entries: [{ column: 'email' }],
      unique: true,
      where: '"deletedAt" IS NULL',
    };
    const sql = generator.generateCreateIndexFromNode(index);
    expect(sql).toBe('CREATE UNIQUE INDEX "live_email_idx" ON "users" ("email") WHERE "deletedAt" IS NULL;');
  });

  it('should generate DROP TABLE from TableNode', () => {
    const table = mockTableNode('users', []);
    const sql = generator.generateDropTable(table.name, { ifExists: true });
    expect(sql).toBe('DROP TABLE IF EXISTS "users";');
  });

  it('should generate DROP TABLE without IF EXISTS by default', () => {
    const table = mockTableNode('users', []);
    expect(generator.generateDropTable(table.name)).toBe('DROP TABLE "users";');
  });
});

/**
 * `ColumnSchema` is the shape a diff carries, so these are the columns an `ALTER TABLE ... ADD
 * COLUMN` emits - the qualifiers have to survive the round trip from the diff to the DDL.
 */
describe('SqlSchemaGenerator column definitions from ColumnSchema', () => {
  const generator = new SqlSchemaGenerator(new PostgresDialect());

  /** ADD COLUMN for a single `ColumnSchema`, with only the qualifiers under test overridden. */
  function addColumn(column: Partial<ColumnSchema>, gen = generator): string {
    return gen.generateAlterTable({
      tableName: 'users',
      type: 'alter',
      columnsToAdd: [
        {
          name: 'col',
          type: 'INTEGER',
          nullable: true,
          isPrimaryKey: false,
          isAutoIncrement: false,
          isUnique: false,
          ...column,
        },
      ],
    })[0];
  }

  it('should append precision and scale to a bare type', () => {
    expect(addColumn({ name: 'amount', type: 'NUMERIC', precision: 12, scale: 4 })).toBe(
      'ALTER TABLE "users" ADD COLUMN "amount" NUMERIC(12, 4);',
    );
  });

  it('should append precision alone when there is no scale', () => {
    expect(addColumn({ name: 'amount', type: 'NUMERIC', precision: 12 })).toBe(
      'ALTER TABLE "users" ADD COLUMN "amount" NUMERIC(12);',
    );
  });

  it('should append length when there is no precision', () => {
    expect(addColumn({ name: 'name', type: 'VARCHAR', length: 100 })).toBe(
      'ALTER TABLE "users" ADD COLUMN "name" VARCHAR(100);',
    );
  });

  it('should keep a type that already carries its own parameters', () => {
    expect(addColumn({ name: 'name', type: 'VARCHAR(50)', length: 100, precision: 12, scale: 4 })).toBe(
      'ALTER TABLE "users" ADD COLUMN "name" VARCHAR(50);',
    );
  });

  it('should emit NOT NULL for a non-nullable column', () => {
    expect(addColumn({ nullable: false })).toBe('ALTER TABLE "users" ADD COLUMN "col" INTEGER NOT NULL;');
  });

  it('should emit UNIQUE for a unique column', () => {
    expect(addColumn({ isUnique: true })).toBe('ALTER TABLE "users" ADD COLUMN "col" INTEGER UNIQUE;');
  });

  /** `UNIQUE` is the key's, which the table declares as its own constraint; `NOT NULL` is not left to it. */
  it('should emit a key column NOT NULL, leaving the key to the table', () => {
    expect(addColumn({ nullable: false, isUnique: true, isPrimaryKey: true })).toBe(
      'ALTER TABLE "users" ADD COLUMN "col" INTEGER NOT NULL;',
    );
  });

  it('should quote a string default and escape its quotes', () => {
    expect(addColumn({ type: 'TEXT', defaultValue: "it's" })).toBe(
      `ALTER TABLE "users" ADD COLUMN "col" TEXT DEFAULT 'it''s';`,
    );
  });

  it('should emit a NULL default distinctly from no default', () => {
    expect(addColumn({ defaultValue: null })).toBe('ALTER TABLE "users" ADD COLUMN "col" INTEGER DEFAULT NULL;');
  });

  it('should emit a native boolean default on Postgres', () => {
    expect(addColumn({ type: 'BOOLEAN', defaultValue: false })).toBe(
      'ALTER TABLE "users" ADD COLUMN "col" BOOLEAN DEFAULT FALSE;',
    );
  });

  /** SQLite/MySQL have no boolean literal, so the default has to bind as 0/1. */
  it('should emit an integer boolean default where booleans are integers', () => {
    const sqliteGenerator = new SqlSchemaGenerator(new SqliteDialect());
    expect(addColumn({ type: 'INTEGER', defaultValue: true }, sqliteGenerator)).toBe(
      'ALTER TABLE `users` ADD COLUMN `col` INTEGER DEFAULT 1;',
    );
    expect(addColumn({ type: 'INTEGER', defaultValue: false }, sqliteGenerator)).toBe(
      'ALTER TABLE `users` ADD COLUMN `col` INTEGER DEFAULT 0;',
    );
  });

  it('should emit a column comment where the dialect supports one', () => {
    const mysqlGenerator = new SqlSchemaGenerator(new MySqlDialect());
    expect(addColumn({ comment: "the user's age", nullable: false }, mysqlGenerator)).toBe(
      "ALTER TABLE `users` ADD COLUMN `col` INTEGER NOT NULL COMMENT 'the user\\'s age';",
    );
  });

  it('should drop a column comment where the dialect has none', () => {
    expect(addColumn({ comment: 'the age' })).toBe('ALTER TABLE "users" ADD COLUMN "col" INTEGER;');
  });

  /**
   * The reverse of an alteration restores the previous column, and re-declaring its PRIMARY KEY
   * there would be rejected as a duplicate constraint.
   */
  it('should strip PRIMARY KEY when restoring a column in the down direction', () => {
    const sql = new SqlSchemaGenerator(new MySqlDialect()).generateAlterTableDown({
      tableName: 'users',
      type: 'alter',
      columnsToAlter: [
        {
          from: {
            name: 'id',
            type: 'BIGINT UNSIGNED AUTO_INCREMENT',
            nullable: false,
            isPrimaryKey: true,
            isAutoIncrement: true,
            isUnique: false,
          },
          to: {
            name: 'id',
            type: 'BIGINT UNSIGNED',
            nullable: false,
            isPrimaryKey: false,
            isAutoIncrement: false,
            isUnique: false,
          },
        },
      ],
    });
    expect(sql).toEqual(['ALTER TABLE `users` MODIFY COLUMN `id` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL;']);
  });
});

describe('SqlSchemaGenerator table definitions from the migration builder', () => {
  const generator = new SqlSchemaGenerator(new PostgresDialect());

  /** A `TableDefinition` for two columns, with the parts under test overridden. */
  function tableDefinition(overrides: Partial<TableDefinition> = {}): TableDefinition {
    return {
      name: 'memberships',
      columns: [
        column({ name: 'userId' }),
        column({
          name: 'groupId',
          foreignKey: { references: { table: 'groups', columns: ['id'] }, onDelete: 'CASCADE', onUpdate: 'NO ACTION' },
        }),
      ],
      indexes: [],
      foreignKeys: [],
      ...overrides,
    };
  }

  function column(overrides: Partial<FullColumnDefinition>): FullColumnDefinition {
    return {
      name: 'col',
      type: { category: 'integer' },
      nullable: false,
      isPrimaryKey: false,
      isAutoIncrement: false,
      isUnique: false,
      ...overrides,
    };
  }

  it('should generate a composite PRIMARY KEY from the declared key columns', () => {
    const sql = generator
      .generateCreateTableFromDefinition(tableDefinition({ primaryKey: ['userId', 'groupId'] }))
      .join('\n');
    expect(sql).toContain('PRIMARY KEY ("userId", "groupId")');
  });

  /** A table's comment is its own statement where the engine takes one, and part of the CREATE where it does not. */
  it('should comment the table the way its engine spells a comment', () => {
    const definition = tableDefinition({ comment: 'Who belongs where' });

    expect(generator.generateCreateTableFromDefinition(definition)).toContain(
      `COMMENT ON TABLE "memberships" IS 'Who belongs where';`,
    );

    const [createSql] = new SqlSchemaGenerator(new MySqlDialect()).generateCreateTableFromDefinition(definition);
    expect(createSql).toMatch(/\) .*COMMENT='Who belongs where';$/);
  });

  it('should ignore a declared key column that no column definition matches', () => {
    const sql = generator
      .generateCreateTableFromDefinition(tableDefinition({ primaryKey: ['userId', 'nope', 'groupId'] }))
      .join('\n');
    expect(sql).toContain('PRIMARY KEY ("userId", "groupId")');
    expect(sql).not.toContain('nope');
  });

  it('should fall back to the columns flagged as primary when no key is declared', () => {
    const definition = tableDefinition();
    definition.columns[0] = column({ name: 'userId', isPrimaryKey: true, isAutoIncrement: true });
    const sql = generator.generateCreateTableFromDefinition(definition).join('\n');
    // The column declares a plain integer, and the key is spelled from it, so a foreign key can match it.
    expect(sql).toContain('"userId" INTEGER GENERATED BY DEFAULT AS IDENTITY');
  });

  it('should generate the declared indexes as separate statements', () => {
    const statements = generator.generateCreateTableFromDefinition(
      tableDefinition({
        indexes: [
          { name: 'memberships_userId_idx', entries: [{ column: 'userId' }], unique: false },
          {
            name: 'memberships_pair_uk',
            entries: [{ column: 'userId' }, { column: 'groupId' }],
            unique: true,
          },
        ],
      }),
    );
    expect(statements).toHaveLength(3);
    expect(statements[1]).toBe('CREATE INDEX "memberships_userId_idx" ON "memberships" ("userId");');
    expect(statements[2]).toBe('CREATE UNIQUE INDEX "memberships_pair_uk" ON "memberships" ("userId", "groupId");');
  });

  it('should render the SQL of a builder index for its engine', () => {
    expect(
      generator.generateCreateIndexFromDefinition('memberships', {
        name: 'memberships_email_uk',
        entries: [{ column: raw`lower("email")` }],
        unique: true,
        where: raw`"deletedAt" IS NULL`,
      }),
    ).toBe(
      'CREATE UNIQUE INDEX IF NOT EXISTS "memberships_email_uk" ON "memberships" ((lower("email"))) WHERE "deletedAt" IS NULL;',
    );
  });

  it('should keep the index options a definition declares, not just its columns', () => {
    const statements = generator.generateCreateTableFromDefinition(
      tableDefinition({
        indexes: [
          {
            name: 'memberships_active_idx',
            entries: [{ column: 'userId', order: 'desc' }, { column: raw`lower("groupId")` }],
            unique: true,
            where: raw`"deletedAt" IS NULL`,
            include: ['groupId'],
          },
        ],
      }),
    );
    expect(statements[1]).toBe(
      'CREATE UNIQUE INDEX "memberships_active_idx" ON "memberships" ("userId" DESC, (lower("groupId"))) ' +
        'INCLUDE ("groupId") WHERE "deletedAt" IS NULL;',
    );
  });

  it('should generate a table-level FOREIGN KEY with its declared actions', () => {
    const sql = generator
      .generateCreateTableFromDefinition(
        tableDefinition({
          foreignKeys: [
            {
              name: 'memberships_user_fk',
              columns: ['userId'],
              references: { table: 'users', columns: ['id'] },
              onDelete: 'CASCADE',
              onUpdate: 'NO ACTION',
            },
          ],
        }),
      )
      .join('\n');
    expect(sql).toContain(
      'CONSTRAINT "memberships_user_fk" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION',
    );
  });

  it('should name an unnamed table-level FOREIGN KEY after its table and columns', () => {
    const sql = generator
      .generateCreateTableFromDefinition(
        tableDefinition({
          foreignKeys: [
            {
              columns: ['userId'],
              references: { table: 'users', columns: ['id'] },
              onDelete: 'NO ACTION',
              onUpdate: 'NO ACTION',
            },
          ],
        }),
      )
      .join('\n');
    expect(sql).toContain('CONSTRAINT "memberships__userId_fk" FOREIGN KEY ("userId")');
  });

  it('should generate ADD CONSTRAINT for a foreign key added to an existing table', () => {
    const sql = generator.generateAddForeignKeySql('memberships', {
      columns: ['groupId'],
      references: { table: 'groups', columns: ['id'] },
      onDelete: 'SET NULL',
      onUpdate: 'CASCADE',
    });
    expect(sql).toBe(
      'ALTER TABLE "memberships" ADD CONSTRAINT "memberships__groupId_fk" ' +
        'FOREIGN KEY ("groupId") REFERENCES "groups" ("id") ON DELETE SET NULL ON UPDATE CASCADE;',
    );
  });

  /** SQLite cannot add a constraint to an existing table, so this has to fail rather than emit invalid DDL. */
  it('should reject adding a foreign key where the dialect cannot alter constraints', () => {
    const sqliteGenerator = new SqlSchemaGenerator(new SqliteDialect());
    expect(() =>
      sqliteGenerator.generateAddForeignKeySql('memberships', {
        columns: ['groupId'],
        references: { table: 'groups', columns: ['id'] },
        onDelete: 'NO ACTION',
        onUpdate: 'NO ACTION',
      }),
    ).toThrow('does not support adding foreign keys to existing tables');
  });

  it('should rename a table with ALTER TABLE, which MySQL takes too', () => {
    expect(generator.generateRenameTableSql('old', 'new')).toBe('ALTER TABLE "old" RENAME TO "new";');
    expect(new SqlSchemaGenerator(new MySqlDialect()).generateRenameTableSql('old', 'new')).toBe(
      'ALTER TABLE `old` RENAME TO `new`;',
    );
  });
  describe('generateCreateSchema', () => {
    it('should emit cross-entity foreign keys, which the per-entity path dropped', () => {
      const generator = new SqlSchemaGenerator(new PostgresDialect());
      const sql = generator.generateCreateSchema([TestUser, TestPost]);

      const creates = sql.filter((s) => s.startsWith('CREATE TABLE'));
      const fks = sql.filter((s) => s.includes('ADD CONSTRAINT'));

      expect(creates).toHaveLength(2);
      // Constraints come after every table, so a cyclic relation graph is creatable at all.
      expect(creates.every((s) => !s.includes('FOREIGN KEY'))).toBe(true);
      expect(fks.some((s) => s.includes('ALTER TABLE "blog_posts"') && s.includes('"TestUser"'))).toBe(true);
    });

    it('should keep constraints inline on SQLite, which cannot ALTER one in', () => {
      const generator = new SqlSchemaGenerator(new SqliteDialect());
      const sql = generator.generateCreateSchema([TestUser, TestPost]);

      // SQLite resolves a foreign key target lazily, so a forward reference is fine and no ALTER is
      // needed. `features.foreignKeyAlter` is false there, which is what selects this shape.
      expect(sql.some((s) => s.includes('ADD CONSTRAINT'))).toBe(false);
      expect(sql.some((s) => s.startsWith('CREATE TABLE') && s.includes('FOREIGN KEY'))).toBe(true);
    });

    it('should narrow creation with `only` while still resolving constraints against the full graph', () => {
      const generator = new SqlSchemaGenerator(new PostgresDialect());
      const sql = generator.generateCreateSchema([TestUser, TestPost], { only: ['blog_posts'] });

      expect(sql.filter((s) => s.startsWith('CREATE TABLE'))).toHaveLength(1);
      expect(sql.some((s) => s.includes('ALTER TABLE "blog_posts"') && s.includes('"TestUser"'))).toBe(true);
    });

    it('should emit no foreign keys at all when asked for none', () => {
      const generator = new SqlSchemaGenerator(new PostgresDialect());
      const sql = generator.generateCreateSchema([TestUser, TestPost], { foreignKeys: false });

      expect(sql.filter((s) => s.startsWith('CREATE TABLE'))).toHaveLength(2);
      expect(sql.some((s) => s.includes('FOREIGN KEY') || s.includes('ADD CONSTRAINT'))).toBe(false);
    });
  });

  describe('generateDropSchema', () => {
    it('should drop dependents before the tables they reference', () => {
      const generator = new SqlSchemaGenerator(new PostgresDialect());
      const sql = generator.generateDropSchema([TestUser, TestPost]);

      // Declaration order puts `TestUser` first, so a reverse-of-declaration drop would emit it last and
      // be rejected: `blog_posts` still references it.
      expect(sql).toEqual(['DROP TABLE "blog_posts";', 'DROP TABLE "TestUser";']);
    });

    it('should add CASCADE only where the dialect has it, since a cycle has no valid order', () => {
      const options = { ifExists: true, cascade: true };

      expect(new SqlSchemaGenerator(new PostgresDialect()).generateDropSchema([TestUser], options)).toEqual([
        'DROP TABLE IF EXISTS "TestUser" CASCADE;',
      ]);
      expect(new SqlSchemaGenerator(new MySqlDialect()).generateDropSchema([TestUser], options)).toEqual([
        'DROP TABLE IF EXISTS `TestUser`;',
      ]);
    });
  });
});

/** Exposes the default comparison a diff runs, which is protected. */
class DefaultsProbe extends SqlSchemaGenerator {
  defaultsMatch(current: unknown, desired: unknown): boolean {
    return this.isDefaultValueEqual(current, desired);
  }
}

@Entity()
class DiffUser {
  @Id({ type: Number }) id?: number;
  @Field({ type: String, columnType: 'varchar', length: 255 }) name?: string | null;
  @Field({ type: String, columnType: 'varchar', length: 100 }) email?: string | null;
  @Field({ type: String, columnType: 'varchar', length: 255, index: true }) status?: string | null;
}

@Entity()
class DefaultsEntity {
  @Id({ type: Number }) id?: number;
  @Field({ type: String, columnType: 'varchar', length: 20, defaultValue: 'active' }) status?: string | null;
  @Field({ type: Number, columnType: 'int', defaultValue: 0 }) attempts?: number | null;
}

@Entity()
class EnumAltered {
  @Id({ type: Number }) id?: number;
  @Field({ type: String, columnType: 'varchar', length: 20, enum: ['draft', 'paid'] as const })
  status?: 'draft' | 'paid' | null;
}

@Entity()
class ComputedEntity {
  @Id({ type: Number }) id?: number;
  @Field({ type: Number, computed: raw`1 + 1` }) total?: number | null;
}

describe('SqlSchemaGenerator diffs (Postgres)', () => {
  const generator = new DefaultsProbe(new PostgresDialect());

  it('should refuse to drop a key whose constraint introspection did not name', () => {
    expect(() => generator.generateDropPrimaryKeySql('users')).toThrow(
      'Cannot drop the primary key of "users": postgres names the constraint',
    );
  });

  it('should expose the naming strategy of its dialect', () => {
    const namingStrategy = new SnakeCaseNamingStrategy();
    expect(new SqlSchemaGenerator(new PostgresDialect({ namingStrategy })).namingStrategy).toBe(namingStrategy);
  });

  it('should type a foreign key as the key it points at', () => {
    @Entity()
    class RefTarget {
      @Id({ type: String, columnType: 'uuid' }) id?: string;
    }
    @Entity()
    class RefSource {
      @Id({ type: Number }) id?: number;
      @Field({ references: () => RefTarget }) ownerId?: string | null;
    }
    const { ownerId } = getMeta(RefSource).fields;
    assertDefined(ownerId);
    expect(generator.getSqlType(ownerId)).toBe('UUID');
  });

  /** One resolution for the column a table gets and the type this reports, so the two cannot disagree. */
  it('should type a foreign key as its create statement does, its own columnType first, and a shared key never serial', () => {
    @Entity()
    class Account {
      @Id({ type: Number }) id?: number;
    }
    @Entity()
    class AccountProfile {
      @Id({ type: Number, references: () => Account }) id?: number;
      @Field({ references: () => Account, columnType: 'int' }) backupId?: number | null;
    }
    const { id, backupId } = getMeta(AccountProfile).fields;
    assertDefined(id);
    assertDefined(backupId);
    const ddl = generator.generateCreateSchema([Account, AccountProfile]).join('\n');

    expect(generator.getSqlType(id)).toBe('BIGINT');
    expect(generator.getSqlType(backupId)).toBe('INTEGER');
    expect(ddl).toContain('CREATE TABLE "AccountProfile" (\n  "id" BIGINT NOT NULL,\n  "backupId" INTEGER,');
  });

  it('should comment a column of a table that has no comment of its own', () => {
    @Entity()
    class Commented {
      @Id({ type: Number }) id?: number;
      @Field({ type: String, comment: 'Shown to users' }) label?: string | null;
    }
    const statements = generator.generateCreateSchema([Commented]);
    expect(statements).toContainEqual(expect.stringContaining('COMMENT ON COLUMN'));
    expect(statements.filter((statement) => statement.startsWith('COMMENT ON TABLE'))).toEqual([]);
  });

  /** Reversing a key change restores only the side that had one: a key added from none drops, one removed adds back. */
  it('should reverse a primary key change that added a key, or removed one', () => {
    const added = generator.generateAlterTableDown({
      tableName: 'users',
      type: 'alter',
      primaryKey: { from: [], to: ['id'] },
    });
    expect(added).toEqual([expect.stringContaining('DROP CONSTRAINT')]);

    const removed = generator.generateAlterTableDown({
      tableName: 'users',
      type: 'alter',
      primaryKey: { from: ['id'], to: [] },
    });
    expect(removed).toEqual([expect.stringContaining('ADD CONSTRAINT')]);
  });

  it('should diff nothing where the desired schema has no table for the entity', () => {
    const current = buildEntityAST(generator, [DiffUser]).getTable('DiffUser');
    expect(generator.diffSchema(DiffUser, current, new SchemaAST())).toBeUndefined();
  });

  it('should read a cast NULL as no default, whichever side spells it', () => {
    expect(generator.defaultsMatch('NULL::character varying', 'NULL')).toBe(true);
  });

  it('should detect new columns', () => {
    const currentSchema = mockSqlTableNode('DiffUser', [
      { name: 'id', sql: 'INTEGER', isPrimaryKey: true, isAutoIncrement: true },
      { name: 'name', sql: 'VARCHAR', length: 255 },
    ]);

    const diff = generator.diffSchema(DiffUser, currentSchema);

    expect(diff).toBeDefined();
    expect(diff?.type).toBe('alter');
    expect(diff?.columnsToAdd).toHaveLength(2);
    expect(diff?.columnsToAdd?.[0].name).toBe('email');
    expect(diff?.columnsToAdd?.[1].name).toBe('status');
  });

  it('should detect a column whose type changed', () => {
    const currentSchema = mockSqlTableNode('DiffUser', [
      { name: 'id', sql: 'BIGINT', isPrimaryKey: true, isAutoIncrement: true },
      { name: 'name', sql: 'TEXT' },
      { name: 'email', sql: 'VARCHAR', length: 50 },
      { name: 'status', sql: 'VARCHAR', length: 255 },
    ]);

    const diff = generator.diffSchema(DiffUser, currentSchema);

    expect(diff).toBeDefined();
    expect(diff?.type).toBe('alter');
    expect(diff?.columnsToAlter).toHaveLength(2);
    expect(diff?.columnsToAlter?.map((c) => c.to.name)).toContain('name');
    expect(diff?.columnsToAlter?.map((c) => c.to.name)).toContain('email');
  });

  /**
   * An altered column carries no values to restate: MySQL answers a restated `CHECK` by adding a
   * second constraint rather than replacing the first. They reach the database with the column, which
   * is also why changing an enum is a hand-written migration.
   */
  it('should leave an enum off a column it alters', () => {
    const currentSchema = mockSqlTableNode('EnumAltered', [
      { name: 'id', sql: 'INTEGER', isPrimaryKey: true, isAutoIncrement: true },
      { name: 'status', sql: 'VARCHAR', length: 10 },
    ]);

    const diff = generator.diffSchema(EnumAltered, currentSchema, generator.buildAST([EnumAltered]));

    expect(diff?.columnsToAlter?.[0].to.name).toBe('status');
    expect(diff?.columnsToAlter?.[0].to.enum).toBeUndefined();
  });

  it('should detect columns to drop', () => {
    const currentSchema = mockSqlTableNode('DiffUser', [
      { name: 'id', sql: 'INTEGER', isPrimaryKey: true, isAutoIncrement: true },
      { name: 'name', sql: 'VARCHAR', length: 255 },
      { name: 'email', sql: 'VARCHAR', length: 100 },
      { name: 'status', sql: 'VARCHAR', length: 255 },
      { name: 'old_col', sql: 'VARCHAR' },
    ]);

    const diff = generator.diffSchema(DiffUser, currentSchema);

    expect(diff).toBeDefined();
    expect(diff?.type).toBe('alter');
    expect(diff?.columnsToDrop).toEqual(['old_col']);
  });

  it('should add an index the entity declares and the table has not got', () => {
    const currentSchema = mockSqlTableNode('DiffUser', [
      { name: 'id', sql: 'INTEGER', isPrimaryKey: true, isAutoIncrement: true },
      { name: 'name', sql: 'VARCHAR', length: 255 },
      { name: 'email', sql: 'VARCHAR', length: 100 },
      { name: 'status', sql: 'VARCHAR', length: 255 },
    ]);

    const diff = generator.diffSchema(DiffUser, currentSchema);

    expect(diff?.columnsToAdd).toBeUndefined();
    expect(diff?.indexesToAdd?.map((index) => index.name)).toEqual(['DiffUser__status_idx']);
  });

  it('should leave alone an index the entity never declared', () => {
    const currentSchema = mockSqlTableNode('DiffUser', [
      { name: 'id', sql: 'INTEGER', isPrimaryKey: true, isAutoIncrement: true },
      { name: 'name', sql: 'VARCHAR', length: 255 },
      { name: 'email', sql: 'VARCHAR', length: 100 },
      { name: 'status', sql: 'VARCHAR', length: 255 },
    ]);
    // With their real entries, as an introspector reports them: an index is recognised by the
    // columns it covers, so the one the entity declares is already present under any name.
    currentSchema.indexes.push(
      { name: 'DiffUser__status_idx', table: currentSchema, entries: [{ column: 'status' }], unique: false },
      { name: 'made_by_a_dba_idx', table: currentSchema, entries: [{ column: 'email' }], unique: false },
    );

    expect(generator.diffSchema(DiffUser, currentSchema)).toBeUndefined();
  });

  /**
   * The reason an index is recognised by its shape. Renaming the convention, an engine truncating a
   * name past its identifier limit, and SQLite reporting a name it made up all produce the same
   * thing: an index that is already there under a name we did not choose. Keying on the name
   * re-created it on every migration, forever.
   */
  it('should leave alone an index it would have named differently', () => {
    const currentSchema = mockSqlTableNode('DiffUser', [
      { name: 'id', sql: 'INTEGER', isPrimaryKey: true, isAutoIncrement: true },
      { name: 'name', sql: 'VARCHAR', length: 255 },
      { name: 'email', sql: 'VARCHAR', length: 100 },
      { name: 'status', sql: 'VARCHAR', length: 255 },
    ]);
    currentSchema.indexes.push({
      name: 'whatever_the_dba_called_it',
      table: currentSchema,
      entries: [{ column: 'status' }],
      unique: false,
    });

    expect(generator.diffSchema(DiffUser, currentSchema)).toBeUndefined();
  });

  /** Same columns, different uniqueness: a different index, which no engine can alter into the other. */
  it('should still create an index whose uniqueness differs', () => {
    const currentSchema = mockSqlTableNode('DiffUser', [
      { name: 'id', sql: 'INTEGER', isPrimaryKey: true, isAutoIncrement: true },
      { name: 'name', sql: 'VARCHAR', length: 255 },
      { name: 'email', sql: 'VARCHAR', length: 100 },
      { name: 'status', sql: 'VARCHAR', length: 255 },
    ]);
    currentSchema.indexes.push({
      name: 'DiffUser__status_idx',
      table: currentSchema,
      entries: [{ column: 'status' }],
      unique: true,
    });

    expect(generator.diffSchema(DiffUser, currentSchema)?.indexesToAdd).toHaveLength(1);
  });

  /**
   * Engines disagree on how they report "no default": MariaDB says `null` where MySQL says nothing at
   * all. Read as different values, that asked to `MODIFY` every nullable column on every sync.
   */
  it('should read a reported null default and an absent one as the same', () => {
    expect(generator.defaultsMatch(null, undefined)).toBe(true);
    expect(generator.defaultsMatch(undefined, null)).toBe(true);
    expect(generator.defaultsMatch(null, null)).toBe(true);
    expect(generator.defaultsMatch(null, 'active')).toBe(false);
    expect(generator.defaultsMatch(undefined, 0)).toBe(false);
  });

  /** A default comes back in the engine's own spelling, quoted and cast, and still reads as the entity's. */
  it('should treat engine-spelled defaults as unchanged', () => {
    const currentSchema = defaultsTableNode("'active'::character varying");

    expect(generator.diffSchema(DefaultsEntity, currentSchema)).toBeUndefined();
  });

  it('should detect a genuinely changed default', () => {
    const currentSchema = defaultsTableNode("'inactive'::character varying");

    const diff = generator.diffSchema(DefaultsEntity, currentSchema);

    expect(diff?.columnsToAlter).toHaveLength(1);
    expect(diff?.columnsToAlter?.[0].from.defaultValue).toBe("'inactive'::character varying");
    expect(diff?.columnsToAlter?.[0].to.defaultValue).toBe('active');
  });

  it('should detect a default replacing an existing NULL default', () => {
    const currentSchema = defaultsTableNode(null);

    const diff = generator.diffSchema(DefaultsEntity, currentSchema);

    expect(diff?.columnsToAlter).toHaveLength(1);
    expect(diff?.columnsToAlter?.[0].to.defaultValue).toBe('active');
  });

  it('should detect a default added to a column that had none', () => {
    const currentSchema = defaultsTableNode(undefined);

    const diff = generator.diffSchema(DefaultsEntity, currentSchema);

    expect(diff?.columnsToAlter).toHaveLength(1);
    expect(diff?.columnsToAlter?.[0].to.defaultValue).toBe('active');
  });

  /** An inlined computed field is a query-time expression, never a column, so it must not show up as a diff. */
  it('should skip inlined computed fields', () => {
    const currentSchema = mockSqlTableNode('ComputedEntity', [
      { name: 'id', sql: 'INTEGER', isPrimaryKey: true, isAutoIncrement: true },
    ]);

    expect(generator.diffSchema(ComputedEntity, currentSchema)).toBeUndefined();
  });

  /** `DefaultsEntity` as it stands in the database, with `status`'s stored default under test. */
  function defaultsTableNode(statusDefault: unknown) {
    return mockSqlTableNode('DefaultsEntity', [
      { name: 'id', sql: 'INTEGER', isPrimaryKey: true, isAutoIncrement: true },
      { name: 'status', sql: 'VARCHAR', length: 20, defaultValue: statusDefault },
      { name: 'attempts', sql: 'INTEGER', defaultValue: '0' },
    ]);
  }

  it('should produce the SQL of an alter', () => {
    const sql = generator.generateAlterTable({
      tableName: 'users',
      type: 'alter',
      columnsToAdd: [
        {
          name: 'age',
          type: 'INTEGER',
          nullable: true,
          isPrimaryKey: false,
          isAutoIncrement: false,
          isUnique: false,
        },
      ],
      columnsToDrop: ['old_name'],
      indexesToAdd: [{ name: 'age_idx', entries: [{ column: 'age' }], unique: false }],
      indexesToDrop: [{ name: 'old_idx', entries: [{ column: 'old_name' }], unique: false }],
    });

    expect(sql).toContain('ALTER TABLE "users" ADD COLUMN "age" INTEGER;');
    expect(sql).toContain('ALTER TABLE "users" DROP COLUMN "old_name";');
    expect(sql).toContain('CREATE INDEX IF NOT EXISTS "age_idx" ON "users" ("age");');
    expect(sql).toContain('DROP INDEX IF EXISTS "old_idx";');
  });
});

@Entity({ name: 'users' })
class UsersTable {
  @Id({ type: Number }) id?: number;
  @Field({ type: String }) name?: string | null;
}

/** A row per dialect, so a new dialect is a row rather than a branch in each test. */
const everyDialect = [
  {
    dialect: new PostgresDialect(),
    serialId: 'BIGINT GENERATED BY DEFAULT AS IDENTITY',
    tableOptions: '',
    booleanType: 'BOOLEAN',
    comment: '',
  },
  {
    dialect: new CockroachDialect(),
    serialId: 'BIGINT GENERATED BY DEFAULT AS IDENTITY',
    tableOptions: '',
    booleanType: 'BOOLEAN',
    comment: '',
  },
  {
    dialect: new MySqlDialect(),
    serialId: 'BIGINT AUTO_INCREMENT',
    tableOptions: 'ENGINE=InnoDB',
    booleanType: 'TINYINT(1)',
    comment: " COMMENT 'Testing'",
  },
  {
    dialect: new MariaDialect(),
    serialId: 'BIGINT AUTO_INCREMENT',
    tableOptions: 'ENGINE=InnoDB',
    booleanType: 'TINYINT(1)',
    comment: " COMMENT 'Testing'",
  },
  {
    dialect: new SqliteDialect(),
    serialId: 'INTEGER PRIMARY KEY AUTOINCREMENT',
    tableOptions: '',
    booleanType: 'INTEGER',
    comment: '',
  },
];

describe('SqlSchemaGenerator on every dialect', () => {
  describe.each(everyDialect)(
    'Dialect: $dialect.dialectName',
    ({ dialect, serialId, tableOptions, booleanType, comment }) => {
      const generator = new SqlSchemaGenerator(dialect);

      it('should generate correct CREATE TABLE SQL', () => {
        const sql = generator.generateCreateSchema([UsersTable]).join('\n');

        expect(sql).toContain('CREATE TABLE');
        expect(sql).toContain('users');
        expect(sql).toContain('name');
        expect(sql).toContain(serialId);
        expect(sql).toContain(tableOptions);
      });

      it('should generate correct DROP TABLE SQL', () => {
        expect(generator.generateDropTable('users', { ifExists: true })).toContain('DROP TABLE IF EXISTS');
        expect(generator.generateDropTable('users', { ifExists: true })).toContain('users');
      });

      it('should generate correct SQL type for Boolean', () => {
        expect(generator.getSqlType({ type: Boolean })).toBe(booleanType);
      });

      it('should generate correct column comments', () => {
        expect(generator.generateColumnComment('Testing')).toBe(comment);
      });
    },
  );
});

describe('SqlSchemaGenerator creating a table only where it is missing', () => {
  it('should say so in the statement where the engine has the clause', () => {
    const [sql] = new SqlSchemaGenerator(new PostgresDialect()).generateCreateSchema([UsersTable], {
      ifNotExists: true,
    });
    expect(sql).toMatch(/^CREATE TABLE IF NOT EXISTS "users"/);
  });

  // T-SQL has no `IF NOT EXISTS` on a table: without the guard, a second create fails outright.
  it('should guard it with a lookup on SQL Server', () => {
    const [sql] = new SqlSchemaGenerator(new MsSqlDialect()).generateCreateSchema([UsersTable], { ifNotExists: true });
    expect(sql).toMatch(/^IF OBJECT_ID\(N'"users"', N'U'\) IS NULL CREATE TABLE "users"/);
  });
});

describe('generateTriggers', () => {
  @Trigger({ on: 'afterInsert', name: 'audit', run: { postgres: () => raw`PERFORM 1;` } })
  @Entity({ name: 'GenPost' })
  class GenPost {
    @Id({ type: Number }) id?: number;
    @Field({ type: String }) title?: string | null;
  }

  const generator = new SqlSchemaGenerator(new PostgresDialect());

  afterAll(() => removeEntity(GenPost));

  const audit = () => generator.generateTriggers(GenPost).join('\n');
  const auditName = () => /CREATE TRIGGER "([^"]+)"/.exec(audit())?.[1] ?? '';

  it('should install what the entity declares', () => {
    expect(auditName()).toMatch(/^_uql_GenPost__audit_[0-9a-f]{6}$/);
  });

  // What a drift check reads: once installed as declared, there is nothing left to run.
  it('should emit nothing where what is installed is what the entity declares', () => {
    const installed = new Map([[auditName(), ['CREATE TRIGGER ...']]]);
    expect(generator.generateTriggers(GenPost, installed)).toEqual([]);
    expect(generator.generateTriggersDown(GenPost, installed)).toEqual([]);
  });

  // The `_uql` prefix is what says it is ours to drop; anything else on the table is left alone.
  it('should drop an installed trigger the entity no longer declares, with its function', () => {
    const installed = new Map([
      ['_uql_GenPost__gone_000000', []],
      ['handwritten', []],
    ]);
    const sql = generator.generateTriggers(GenPost, installed).join('\n');
    expect(sql).toContain('DROP TRIGGER IF EXISTS "_uql_GenPost__gone_000000" ON "GenPost";');
    expect(sql).toContain('DROP FUNCTION IF EXISTS "_uql_GenPost__gone_000000"();');
    expect(sql).not.toContain('handwritten');
  });

  // Exactly the inverse: what the reconcile created goes, and what it dropped comes back as it stood.
  it('should roll back by dropping what it created and restoring what it dropped', () => {
    const installed = new Map([['_uql_GenPost__gone_000000', ['CREATE TRIGGER gone']]]);
    expect(generator.generateTriggersDown(GenPost, installed)).toEqual([
      `DROP TRIGGER IF EXISTS "${auditName()}" ON "GenPost";`,
      `DROP FUNCTION IF EXISTS "${auditName()}"();`,
      'CREATE TRIGGER gone;',
    ]);
  });

  it('should emit nothing for an entity declaring none', () => {
    expect(generator.generateTriggers(TestUser)).toEqual([]);
    expect(generator.generateTriggersDown(TestUser)).toEqual([]);
  });
});
