import { v7 as uuidv7 } from 'uuid';
import { afterAll, describe, expect, it } from 'vitest';
import { CockroachDialect } from '../cockroachdb/cockroachDialect.js';
import { Entity, Field, getMeta, Id, Index, ManyToOne, removeEntity, Trigger } from '../entity/index.js';
import { MariaDialect } from '../maria/mariaDialect.js';
import { MsSqlDialect } from '../mssql/mssqlDialect.js';
import { MySqlDialect } from '../mysql/mysqlDialect.js';
import { PostgresDialect } from '../postgres/postgresDialect.js';
import { SchemaAST } from '../schema/schemaAST.js';
import type { IndexNode, TableNode, TriggerSchema } from '../schema/types.js';
import { SqliteDialect } from '../sqlite/sqliteDialect.js';
import { assertDefined, mockSqlTableNode, mockTableNode, sqlTypeOf } from '../test/index.js';
import type { ColumnSchema, SchemaDiff } from '../type/index.js';
import { raw } from '../util/index.js';
import type { FullColumnDefinition, TableDefinition } from './builder/types.js';
import { tableDdlFor } from './ddl/index.js';
import { added, alterations, dropped, reverseDiff } from './schemaChange.js';
import { SqlSchemaGenerator } from './schemaGenerator.js';

// Test entities
@Entity()
class TestUser {
  @Id({ type: Number })
  id?: number;

  @Field({ type: String, length: 100 })
  name?: string | null;

  @Field({ type: String, unique: true })
  email?: string | null;

  @Field({ type: String, nullable: false })
  password?: string;

  @Field({ type: Number, onInsert: Date.now })
  createdAt?: number | null;
}

@Entity({ name: 'blog_posts' })
class TestPost {
  @Id({ type: String, onInsert: uuidv7, length: 36 })
  id?: string;

  @Field({ type: String })
  title?: string | null;

  @Field({ type: String, columnType: 'text' })
  content?: string | null;

  @Field({ type: 'jsonb' })
  metadata?: Record<string, unknown> | null;

  @Field({ references: () => TestUser })
  authorId?: number | null;

  @ManyToOne({ entity: () => TestUser, references: (testPost) => testPost.authorId })
  author?: TestUser;
}

@Entity()
class SqliteIndexedEntity {
  @Id({ type: Number }) id?: number;
  @Field({ type: String, index: true })
  slug?: string | null;
}

describe('SqlSchemaGenerator (Postgres)', () => {
  const generator = new SqlSchemaGenerator(new PostgresDialect());

  it('should generate CREATE TABLE for simple entity', () => {
    const sql = generator.generateCreateSchema([TestUser]).join('\n');

    expect(sql).toContain('CREATE TABLE "TestUser"');
    expect(sql).toContain('"id" BIGINT GENERATED BY DEFAULT AS IDENTITY');
    expect(sql).toContain('"name" VARCHAR(100)');
    // A unique column is a unique index, beside the table rather than a constraint inside it.
    expect(sql).toContain('"email" TEXT,');
    expect(sql).toContain('CREATE UNIQUE INDEX "TestUser__email_idx" ON "TestUser" ("email");');
    expect(sql).toContain('"password" TEXT NOT NULL');
    expect(sql).toContain('"createdAt"');
  });

  it('should generate CREATE TABLE with UUID primary key', () => {
    const sql = generator.generateCreateSchema([TestPost]).join('\n');

    expect(sql).toContain('CREATE TABLE "blog_posts"');
    expect(sql).toContain('"id" VARCHAR(36)');
    expect(sql).toContain('"title" TEXT');
    expect(sql).toContain('"content" TEXT');
    expect(sql).toContain('"metadata" JSONB');
    expect(sql).toContain('"authorId" BIGINT');
  });

  it('should generate DROP TABLE statement', () => {
    expect(generator.generateOperation({ type: 'dropTable', tableName: 'TestUser', ifExists: true })).toEqual([
      'DROP TABLE IF EXISTS "TestUser";',
    ]);
  });
  /** An `embeddings` table of an id and an embedding, with the vector indexes given. */
  function buildVectorTableNode(indexes: Partial<IndexNode>[]): TableNode {
    const table = mockTableNode('embeddings', [
      { name: 'id', type: { category: 'integer' }, nullable: false, isPrimaryKey: true, isAutoIncrement: true },
      { name: 'embedding', type: { category: 'vector', length: 1536 }, nullable: false },
    ]);
    table.indexes.push(
      ...indexes.map((idx) => ({
        name: 'vec_idx',
        table,
        entries: [{ column: 'embedding' }],
        unique: false,
        type: 'vector' as const,
        ...idx,
      })),
    );
    return table;
  }

  /**
   * MySQL scores a column by `MATCH` over exactly that column, which only a `FULLTEXT` index of its own
   * serves, so a weighted index declares one per column heavier than its lightest; Postgres needs none.
   */
  it('should declare a fulltext index for each heavier column where the engine scores through one', () => {
    @Entity()
    @Index((doc) => [{ column: doc.title, weight: 3 }, doc.summary, doc.body], { type: 'fulltext' })
    class WeightedDoc {
      @Id({ type: Number }) id?: number;
      @Field({ type: String }) title?: string | null;
      @Field({ type: String }) summary?: string | null;
      @Field({ type: String }) body?: string | null;
    }
    const indexes = (dialect: MySqlDialect | PostgresDialect) =>
      new SqlSchemaGenerator(dialect)
        .buildAST([WeightedDoc])
        .getTable('WeightedDoc')
        ?.indexes.map(({ name, entries, type }) => ({ name, columns: entries.map((entry) => entry.column), type }));

    expect(indexes(new MySqlDialect())).toEqual([
      { name: 'WeightedDoc__title_summary_body_idx', columns: ['title', 'summary', 'body'], type: 'fulltext' },
      { name: 'WeightedDoc__title_score_idx', columns: ['title'], type: 'fulltext' },
    ]);
    expect(indexes(new PostgresDialect())).toEqual([
      { name: 'WeightedDoc__title_summary_body_idx', columns: ['title', 'summary', 'body'], type: 'fulltext' },
    ]);
  });

  /** InnoDB fills a fulltext index added beside another on a loaded table only once the table is optimized. */
  it('should optimize a MySQL-family table a fulltext index is added to, and no other', () => {
    const diff: SchemaDiff = {
      tableName: 'docs',
      type: 'alter',
      indexes: [
        { to: { name: 'docs_title_idx', entries: [{ column: 'title' }], unique: false, type: 'fulltext' } },
        { to: { name: 'docs_slug_idx', entries: [{ column: 'slug' }], unique: false } },
      ],
    };
    expect(new SqlSchemaGenerator(new MySqlDialect()).generateAlterTable(diff)).toEqual([
      'CREATE FULLTEXT INDEX `docs_title_idx` ON `docs` (`title`);',
      'OPTIMIZE TABLE `docs`;',
      'CREATE INDEX `docs_slug_idx` ON `docs` (`slug`);',
    ]);
    expect(new SqlSchemaGenerator(new PostgresDialect()).generateAlterTable(diff)).not.toContain(
      expect.stringContaining('OPTIMIZE'),
    );
  });

  it('should emit CREATE VECTOR INDEX for MariaDB', () => {
    const mariaGenerator = new SqlSchemaGenerator(new MariaDialect());
    const statements = mariaGenerator.generateCreateTableFromNode(buildVectorTableNode([{}]));
    expect(statements.at(-1)).toBe('CREATE VECTOR INDEX `vec_idx` ON `embeddings` (`embedding`) DISTANCE=cosine;');
    expect(statements[0]).not.toContain('VECTOR INDEX');
    expect(statements.join('\n')).not.toContain('CREATE EXTENSION');
  });

  /**
   * Verified against MariaDB 12.3: a nullable column makes the whole statement fail with "All parts of
   * a VECTOR index must be NOT NULL". The entity's schema says so, so drift and a diff agree with it.
   */
  it('should make a MariaDB vector-indexed column NOT NULL, whatever the entity declared', () => {
    @Index((doc) => [doc.embedding], { type: 'vector', distance: 'cosine' })
    @Entity()
    class NullableEmbedding {
      @Id({ type: Number }) id?: number;
      @Field({ type: 'vector', dimensions: 3 }) embedding?: number[] | null;
    }
    const nullable = (dialect: MariaDialect | PostgresDialect) =>
      new SqlSchemaGenerator(dialect)
        .buildAST([NullableEmbedding])
        .getTable('NullableEmbedding')
        ?.columns.get('embedding')?.nullable;

    expect(nullable(new MariaDialect())).toBe(false);
    expect(nullable(new PostgresDialect())).toBe(true);
  });

  it('should emit CREATE VECTOR INDEX with M and DISTANCE for MariaDB', () => {
    const mariaGenerator = new SqlSchemaGenerator(new MariaDialect());
    const sql = mariaGenerator
      .generateCreateTableFromNode(buildVectorTableNode([{ distance: 'cosine', m: 8 }]))
      .join('\n');
    expect(sql).toContain('ON `embeddings` (`embedding`) M=8 DISTANCE=cosine;');
  });

  it('should emit CREATE VECTOR INDEX with l2 as euclidean for MariaDB', () => {
    const mariaGenerator = new SqlSchemaGenerator(new MariaDialect());
    const sql = mariaGenerator.generateCreateTableFromNode(buildVectorTableNode([{ distance: 'l2' }])).join('\n');
    expect(sql).toContain('ON `embeddings` (`embedding`) DISTANCE=euclidean;');
  });

  // pgvector's index types are not access methods MariaDB has, so they are named rather than
  // compiled into a ` USING hnsw` the server can only answer with a syntax error.
  it.each(['hnsw', 'ivfflat'] as const)('should reject a %s index on MariaDB', (type) => {
    const mariaGenerator = new SqlSchemaGenerator(new MariaDialect());
    expect(() => mariaGenerator.generateCreateTableFromNode(buildVectorTableNode([{ type }]))).toThrow(
      `mariadb has no ${type} index (index "vec_idx"); declare type: 'vector' instead`,
    );
  });

  it('should throw for a MariaDB vector index with an unsupported distance metric, not silently default to euclidean', () => {
    const mariaGenerator = new SqlSchemaGenerator(new MariaDialect());
    expect(() => mariaGenerator.generateCreateTableFromNode(buildVectorTableNode([{ distance: 'inner' }]))).toThrow(
      'mariadb does not support vector distance metric: inner',
    );
  });

  it('should not resolve a vector distance keyword via the prototype chain for an unvalidated distance value', () => {
    const mariaGenerator = new SqlSchemaGenerator(new MariaDialect());
    expect(() =>
      // @ts-expect-error: an inherited property, which a plain lookup would take for a metric
      mariaGenerator.generateCreateTableFromNode(buildVectorTableNode([{ distance: 'toString' }])),
    ).toThrow('mariadb does not support vector distance metric: toString');
  });

  it('should prepend CREATE EXTENSION for Postgres tables with vector columns', () => {
    const sql = generator.generateCreateTableFromNode(buildVectorTableNode([])).join('\n');
    expect(sql).toMatch(/^CREATE EXTENSION IF NOT EXISTS vector;/);
    expect(sql).toContain('CREATE TABLE');
  });

  it('should generate CREATE TABLE with IF NOT EXISTS', () => {
    const sql = generator.generateCreateSchema([TestUser], { ifNotExists: true }).join('\n');
    expect(sql).toContain('CREATE TABLE IF NOT EXISTS "TestUser"');
  });

  /** A table created only if missing creates its indexes the same way, or re-creating a schema fails on the first. */
  it('should create a table indexes IF NOT EXISTS along with the table', () => {
    const guarded = generator.generateCreateSchema([TestUser, TestPost], { ifNotExists: true }).join('\n');
    const plain = generator.generateCreateSchema([TestUser, TestPost]).join('\n');

    expect(guarded).toContain('CREATE INDEX IF NOT EXISTS "blog_posts__authorId_idx" ON "blog_posts" ("authorId");');
    expect(plain).toContain('CREATE INDEX "blog_posts__authorId_idx" ON "blog_posts" ("authorId");');
  });

  it('should handle already-typed column schemas', () => {
    const sql = generator.generateAlterTable({
      tableName: 'users',
      type: 'alter',
      columns: [
        {
          to: {
            name: 'profile_data',
            type: 'JSONB',
            nullable: true,
            isPrimaryKey: false,
            isAutoIncrement: false,
            isUnique: false,
          },
        },
      ],
    });
    // Should NOT be JSONB(JSONB)
    expect(sql[0]).toContain('ADD COLUMN "profile_data" JSONB');
    expect(sql[0]).not.toContain('JSONB(');
  });

  it('should generate ALTER TABLE DOWN statements for column additions', () => {
    const sql = generator.generateAlterTable(
      reverseDiff({
        tableName: 'users',
        type: 'alter',
        columns: [
          {
            to: {
              name: 'profile_data',
              type: 'JSONB',
              nullable: true,
              isPrimaryKey: false,
              isAutoIncrement: false,
              isUnique: false,
            },
          },
        ],
      }),
    );
    expect(sql[0]).toBe('ALTER TABLE "users" DROP COLUMN "profile_data";');
  });

  it('should generate ALTER TABLE DOWN statements for column alterations', () => {
    const sql = generator.generateAlterTable(
      reverseDiff({
        tableName: 'users',
        type: 'alter',
        columns: [
          {
            from: {
              name: 'age',
              type: 'INTEGER',
              nullable: true,
              isPrimaryKey: false,
              isAutoIncrement: false,
              isUnique: false,
            },
            to: {
              name: 'age',
              type: 'BIGINT',
              nullable: false,
              isPrimaryKey: false,
              isAutoIncrement: false,
              isUnique: false,
            },
          },
        ],
      }),
    );
    expect(sql.length).toBeGreaterThan(0);
    expect(sql[0]).toContain('ALTER TABLE');
    expect(sql[0]).toContain('"age"');
    expect(sql[0]).toContain('INTEGER');
  });

  it('should generate ALTER TABLE DOWN statements for index additions', () => {
    const sql = generator.generateAlterTable(
      reverseDiff({
        tableName: 'users',
        type: 'alter',
        indexes: [{ to: { name: 'users__email_idx', entries: [{ column: 'email' }], unique: true } }],
      }),
    );
    expect(sql[0]).toBe('DROP INDEX IF EXISTS "users__email_idx";');
  });

  /** A drop keeps the whole column, so its rollback adds it back, empty. */
  it('should restore a dropped column on the way down', () => {
    const diff: SchemaDiff = { tableName: 'users', type: 'alter', columns: [{ from: namedColumn('old_column') }] };
    expect(generator.generateAlterTable(reverseDiff(diff))).toEqual([
      'ALTER TABLE "users" ADD COLUMN "old_column" TEXT;',
    ]);
  });

  it('should drop an index before recreating one under its name, and reverse both on the way down', () => {
    const diff: SchemaDiff = {
      tableName: 'users',
      type: 'alter',
      indexes: [
        { from: { name: 'lookup', entries: [{ column: 'name' }], unique: false } },
        { to: { name: 'lookup', entries: [{ column: 'name' }, { column: 'email' }], unique: false } },
      ],
    };

    expect(generator.generateAlterTable(diff)).toEqual([
      'DROP INDEX IF EXISTS "lookup";',
      'CREATE INDEX IF NOT EXISTS "lookup" ON "users" ("name", "email");',
    ]);
    expect(generator.generateAlterTable(reverseDiff(diff))).toEqual([
      'DROP INDEX IF EXISTS "lookup";',
      'CREATE INDEX IF NOT EXISTS "lookup" ON "users" ("name");',
    ]);
  });

  /** A rename runs before the adds both ways, so what the way down puts back names the column under its old name. */
  it('should restore a key, index and foreign key over a renamed column under its old name', () => {
    const diff: SchemaDiff = {
      tableName: 'users',
      type: 'alter',
      renamedColumns: [{ from: 'name', to: 'handle' }],
      primaryKey: {
        from: { columns: ['id', 'handle'], name: 'users_pkey' },
        to: { columns: ['handle', 'id'], name: 'users__handle_id_pk' },
      },
      indexes: [
        { from: { name: 'users__name_idx', entries: [{ column: 'handle' }], unique: false } },
        { to: { name: 'users__handle_idx', entries: [{ column: 'handle' }], unique: true } },
      ],
      foreignKeys: [
        { from: { name: 'users__name_fk', columns: ['handle'], references: { table: 'people', columns: ['name'] } } },
      ],
    };

    expect(generator.generateAlterTable(reverseDiff(diff))).toEqual([
      'ALTER TABLE "users" DROP CONSTRAINT "users__handle_id_pk";',
      'DROP INDEX IF EXISTS "users__handle_idx";',
      'ALTER TABLE "users" RENAME COLUMN "handle" TO "name";',
      'ALTER TABLE "users" ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id", "name");',
      'CREATE INDEX IF NOT EXISTS "users__name_idx" ON "users" ("name");',
      'ALTER TABLE "users" ADD CONSTRAINT "users__name_fk" FOREIGN KEY ("name") REFERENCES "people" ("name") ON DELETE NO ACTION ON UPDATE NO ACTION;',
    ]);
  });

  it('should generate ALTER TABLE statements for dropping columns and indexes', () => {
    const sql = generator.generateAlterTable({
      tableName: 'users',
      type: 'alter',
      columns: [{ from: namedColumn('old_col') }],
      indexes: [
        { from: { name: 'old_idx', entries: [{ column: 'old_col' }], unique: false } },
        { to: { name: 'new_idx', entries: [{ column: 'name' }], unique: false } },
      ],
    });
    expect(sql).toEqual([
      'DROP INDEX IF EXISTS "old_idx";',
      'ALTER TABLE "users" DROP COLUMN "old_col";',
      'CREATE INDEX IF NOT EXISTS "new_idx" ON "users" ("name");',
    ]);
  });
});

describe('SqlSchemaGenerator (MySQL)', () => {
  const generator = new SqlSchemaGenerator(new MySqlDialect());

  /** MySQL's `CREATE INDEX` takes no `IF NOT EXISTS`, so a guarded table's indexes stay plain there. */
  it('should leave a table indexes unguarded where the engine cannot guard one', () => {
    const sql = generator.generateCreateSchema([TestUser, TestPost], { ifNotExists: true }).join('\n');

    expect(sql).toContain('CREATE TABLE IF NOT EXISTS `blog_posts`');
    expect(sql).not.toContain('INDEX IF NOT EXISTS');
  });

  it('should generate CREATE TABLE for simple entity', () => {
    const sql = generator.generateCreateSchema([TestUser]).join('\n');

    expect(sql).toContain('CREATE TABLE `TestUser`');
    expect(sql).toContain('`id` BIGINT AUTO_INCREMENT');
    expect(sql).toContain('`name` VARCHAR(100)');
    expect(sql).toContain('`email` VARCHAR(255),');
    expect(sql).toContain('CREATE UNIQUE INDEX `TestUser__email_idx` ON `TestUser` (`email`);');
    expect(sql).toContain('ENGINE=InnoDB');
  });

  it('should generate boolean as TINYINT(1)', () => {
    const boolType = sqlTypeOf(new MySqlDialect(), { type: Boolean });
    expect(boolType).toBe('TINYINT(1)');
  });

  it('should generate DROP INDEX with ON table', () => {
    expect(generator.generateOperation({ type: 'dropIndex', tableName: 'users', indexName: 'email_idx' })).toEqual([
      'DROP INDEX `email_idx` ON `users`;',
    ]);
  });
});

describe('SqlSchemaGenerator (SQLite)', () => {
  const generator = new SqlSchemaGenerator(new SqliteDialect());

  it('should generate CREATE TABLE for simple entity', () => {
    const sql = generator.generateCreateSchema([TestUser]).join('\n');

    expect(sql).toContain('CREATE TABLE `TestUser`');
    expect(sql).toContain('`id` INTEGER PRIMARY KEY AUTOINCREMENT');
    expect(sql).toContain('`name` TEXT');
    expect(sql).toContain('`email` TEXT,');
    expect(sql).toContain('CREATE UNIQUE INDEX `TestUser__email_idx` ON `TestUser` (`email`);');
  });

  it('should use TEXT for most types (SQLite dynamic typing)', () => {
    expect(sqlTypeOf(new SqliteDialect(), { columnType: 'varchar' })).toBe('TEXT');
    expect(sqlTypeOf(new SqliteDialect(), { columnType: 'json' })).toBe('TEXT');
    expect(sqlTypeOf(new SqliteDialect(), { columnType: 'uuid' })).toBe('TEXT');
  });

  it('should use INTEGER for numeric types', () => {
    expect(sqlTypeOf(new SqliteDialect(), { columnType: 'int' })).toBe('INTEGER');
    expect(sqlTypeOf(new SqliteDialect(), { columnType: 'bigint' })).toBe('INTEGER');
    expect(sqlTypeOf(new SqliteDialect(), { type: Boolean })).toBe('INTEGER');
  });

  it('should split non-inline indexes into statements of their own', () => {
    const stmts = generator.generateCreateSchema([SqliteIndexedEntity]);
    expect(stmts).toHaveLength(2);
    expect(stmts[0]).toMatch(/^CREATE TABLE `SqliteIndexedEntity`/);
    expect(stmts[1]).toMatch(/^CREATE INDEX `SqliteIndexedEntity__slug_idx`/);
  });
});

describe('SqlSchemaGenerator Integration', () => {
  const generator = new SqlSchemaGenerator(new PostgresDialect());

  it('should generate CREATE TABLE from TableNode', () => {
    const table = mockTableNode('users', [
      {
        name: 'id',
        type: { category: 'integer', size: 'big' },
        isPrimaryKey: true,
        isAutoIncrement: true,
        nullable: false,
      },
      { name: 'name', type: { category: 'string', length: 100 } },
    ]);

    const sql = generator.generateCreateTableFromNode(table).join('\n');
    expect(sql).toContain('CREATE TABLE "users"');
    expect(sql).toContain('"id" BIGINT GENERATED BY DEFAULT AS IDENTITY');
    expect(sql).toContain('"name" VARCHAR(100)');
  });

  it('should generate CREATE INDEX from IndexNode', () => {
    const table = mockTableNode('users', [{ name: 'name' }]);
    const index: IndexNode = {
      name: 'name_idx',
      table,
      entries: [{ column: 'name' }],
      unique: true,
    };
    const sql = generator.generateCreateTableFromNode({ ...table, indexes: [index] }).at(-1);
    expect(sql).toBe('CREATE UNIQUE INDEX "name_idx" ON "users" ("name");');
  });

  // The predicate reaches the index, so the soft-delete pattern stays unique among live rows only.
  it('should carry a partial index predicate from IndexNode', () => {
    const table = mockTableNode('users', [{ name: 'email' }]);
    const index: IndexNode = {
      name: 'live_email_idx',
      table,
      entries: [{ column: 'email' }],
      unique: true,
      where: '"deletedAt" IS NULL',
    };
    const sql = generator.generateCreateTableFromNode({ ...table, indexes: [index] }).at(-1);
    expect(sql).toBe('CREATE UNIQUE INDEX "live_email_idx" ON "users" ("email") WHERE "deletedAt" IS NULL;');
  });

  it('should generate DROP TABLE without IF EXISTS by default', () => {
    expect(generator.generateOperation({ type: 'dropTable', tableName: 'users' })).toEqual(['DROP TABLE "users";']);
  });
});

/**
 * `ColumnSchema` is the shape a diff carries, so these are the columns an `ALTER TABLE ... ADD
 * COLUMN` emits - the qualifiers have to survive the round trip from the diff to the DDL.
 */
describe('SqlSchemaGenerator column definitions from ColumnSchema', () => {
  const generator = new SqlSchemaGenerator(new PostgresDialect());

  /** ADD COLUMN for a single `ColumnSchema`, with only the qualifiers under test overridden. */
  function addColumn(column: Partial<ColumnSchema>, gen = generator): string {
    return gen.generateAlterTable({
      tableName: 'users',
      type: 'alter',
      columns: [
        {
          to: {
            name: 'col',
            type: 'INTEGER',
            nullable: true,
            isPrimaryKey: false,
            isAutoIncrement: false,
            isUnique: false,
            ...column,
          },
        },
      ],
    })[0];
  }

  it('should emit NOT NULL for a non-nullable column', () => {
    expect(addColumn({ nullable: false })).toBe('ALTER TABLE "users" ADD COLUMN "col" INTEGER NOT NULL;');
  });

  /** A unique column is a unique index, which the table creates beside it. */
  it("should leave a unique column's uniqueness to its index", () => {
    expect(addColumn({ isUnique: true })).toBe('ALTER TABLE "users" ADD COLUMN "col" INTEGER;');
  });

  /** `UNIQUE` is the key's, which the table declares as its own constraint; `NOT NULL` is not left to it. */
  it('should emit a key column NOT NULL, leaving the key to the table', () => {
    expect(addColumn({ nullable: false, isUnique: true, isPrimaryKey: true })).toBe(
      'ALTER TABLE "users" ADD COLUMN "col" INTEGER NOT NULL;',
    );
  });

  it('should quote a string default and escape its quotes', () => {
    expect(addColumn({ type: 'TEXT', defaultValue: "it's" })).toBe(
      `ALTER TABLE "users" ADD COLUMN "col" TEXT DEFAULT 'it''s';`,
    );
  });

  it('should emit a NULL default distinctly from no default', () => {
    expect(addColumn({ defaultValue: null })).toBe('ALTER TABLE "users" ADD COLUMN "col" INTEGER DEFAULT NULL;');
  });

  it('should emit a native boolean default on Postgres', () => {
    expect(addColumn({ type: 'BOOLEAN', defaultValue: false })).toBe(
      'ALTER TABLE "users" ADD COLUMN "col" BOOLEAN DEFAULT FALSE;',
    );
  });

  /** SQLite/MySQL have no boolean literal, so the default has to bind as 0/1. */
  it('should emit an integer boolean default where booleans are integers', () => {
    const sqliteGenerator = new SqlSchemaGenerator(new SqliteDialect());
    expect(addColumn({ type: 'INTEGER', defaultValue: true }, sqliteGenerator)).toBe(
      'ALTER TABLE `users` ADD COLUMN `col` INTEGER DEFAULT 1;',
    );
    expect(addColumn({ type: 'INTEGER', defaultValue: false }, sqliteGenerator)).toBe(
      'ALTER TABLE `users` ADD COLUMN `col` INTEGER DEFAULT 0;',
    );
  });

  it('should emit a column comment where the dialect supports one', () => {
    const mysqlGenerator = new SqlSchemaGenerator(new MySqlDialect());
    expect(addColumn({ comment: "the user's age", nullable: false, defaultValue: 0 }, mysqlGenerator)).toBe(
      "ALTER TABLE `users` ADD COLUMN `col` INTEGER NOT NULL DEFAULT 0 COMMENT 'the user\\'s age';",
    );
  });

  it('should drop a column comment where the dialect has none', () => {
    expect(addColumn({ comment: 'the age' })).toBe('ALTER TABLE "users" ADD COLUMN "col" INTEGER;');
  });

  /**
   * The reverse of an alteration restores the previous column, and re-declaring its PRIMARY KEY
   * there would be rejected as a duplicate constraint.
   */
  it('should strip PRIMARY KEY when restoring a column in the down direction', () => {
    const sql = new SqlSchemaGenerator(new MySqlDialect()).generateAlterTable(
      reverseDiff({
        tableName: 'users',
        type: 'alter',
        columns: [
          {
            from: {
              name: 'id',
              type: 'BIGINT UNSIGNED AUTO_INCREMENT',
              nullable: false,
              isPrimaryKey: true,
              isAutoIncrement: true,
              isUnique: false,
            },
            to: {
              name: 'id',
              type: 'BIGINT UNSIGNED',
              nullable: false,
              isPrimaryKey: false,
              isAutoIncrement: false,
              isUnique: false,
            },
          },
        ],
      }),
    );
    expect(sql).toEqual(['ALTER TABLE `users` MODIFY COLUMN `id` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL;']);
  });
});

describe('SqlSchemaGenerator table definitions from the migration builder', () => {
  const generator = new SqlSchemaGenerator(new PostgresDialect());

  /** A `TableDefinition` for two columns, with the parts under test overridden. */
  function tableDefinition(overrides: Partial<TableDefinition> = {}): TableDefinition {
    return {
      name: 'memberships',
      columns: [
        column({ name: 'userId' }),
        column({
          name: 'groupId',
          foreignKey: { references: { table: 'groups', columns: ['id'] }, onDelete: 'CASCADE', onUpdate: 'NO ACTION' },
        }),
      ],
      indexes: [],
      foreignKeys: [],
      ...overrides,
    };
  }

  function column(overrides: Partial<FullColumnDefinition>): FullColumnDefinition {
    return {
      name: 'col',
      type: { category: 'integer' },
      nullable: false,
      isPrimaryKey: false,
      isAutoIncrement: false,
      isUnique: false,
      ...overrides,
    };
  }

  it('should generate a composite PRIMARY KEY from the declared key columns', () => {
    const sql = generator
      .generateCreateTableFromDefinition(tableDefinition({ primaryKey: ['userId', 'groupId'] }))
      .join('\n');
    expect(sql).toContain('PRIMARY KEY ("userId", "groupId")');
  });

  /** A table's comment is its own statement where the engine takes one, and part of the CREATE where it does not. */
  it('should comment the table the way its engine spells a comment', () => {
    const definition = tableDefinition({ comment: 'Who belongs where' });

    expect(generator.generateCreateTableFromDefinition(definition)).toContain(
      `COMMENT ON TABLE "memberships" IS 'Who belongs where';`,
    );

    const [createSql] = new SqlSchemaGenerator(new MySqlDialect()).generateCreateTableFromDefinition(definition);
    expect(createSql).toMatch(/\) .*COMMENT='Who belongs where';$/);
  });

  /** A table in a schema: qualified where the statement names it, bare in every name derived from it. */
  it('should create a table in a schema, referencing one in another', () => {
    const sql = generator
      .generateCreateTableFromDefinition(
        tableDefinition({
          name: 'sales.orders',
          primaryKey: ['userId'],
          foreignKeys: [{ columns: ['groupId'], references: { table: 'auth.users', columns: ['id'] } }],
        }),
      )
      .join('\n');

    expect(sql).toContain('CREATE TABLE "sales"."orders"');
    expect(sql).toContain('CONSTRAINT "orders__userId_pk" PRIMARY KEY ("userId")');
    expect(sql).toContain('REFERENCES "auth"."users" ("id")');
  });

  it('should ignore a declared key column that no column definition matches', () => {
    const sql = generator
      .generateCreateTableFromDefinition(tableDefinition({ primaryKey: ['userId', 'nope', 'groupId'] }))
      .join('\n');
    expect(sql).toContain('PRIMARY KEY ("userId", "groupId")');
    expect(sql).not.toContain('nope');
  });

  it('should fall back to the columns flagged as primary when no key is declared', () => {
    const definition = tableDefinition();
    definition.columns[0] = column({ name: 'userId', isPrimaryKey: true, isAutoIncrement: true });
    const sql = generator.generateCreateTableFromDefinition(definition).join('\n');
    // The column declares a plain integer, and the key is spelled from it, so a foreign key can match it.
    expect(sql).toContain('"userId" INTEGER GENERATED BY DEFAULT AS IDENTITY');
  });

  it('should generate the declared indexes as separate statements', () => {
    const statements = generator.generateCreateTableFromDefinition(
      tableDefinition({
        indexes: [
          { name: 'memberships_userId_idx', entries: [{ column: 'userId' }], unique: false },
          {
            name: 'memberships_pair_uk',
            entries: [{ column: 'userId' }, { column: 'groupId' }],
            unique: true,
          },
        ],
      }),
    );
    expect(statements).toHaveLength(3);
    expect(statements[1]).toBe('CREATE INDEX "memberships_userId_idx" ON "memberships" ("userId");');
    expect(statements[2]).toBe('CREATE UNIQUE INDEX "memberships_pair_uk" ON "memberships" ("userId", "groupId");');
  });

  it('should render the SQL of a builder index for its engine', () => {
    expect(
      generator.generateOperation({
        type: 'createIndex',
        tableName: 'memberships',
        index: {
          name: 'memberships_email_uk',
          entries: [{ column: raw`lower("email")` }],
          unique: true,
          where: raw`"deletedAt" IS NULL`,
        },
      }),
    ).toEqual([
      'CREATE UNIQUE INDEX IF NOT EXISTS "memberships_email_uk" ON "memberships" ((lower("email"))) WHERE "deletedAt" IS NULL;',
    ]);
  });

  it('should keep the index options a definition declares, not just its columns', () => {
    const statements = generator.generateCreateTableFromDefinition(
      tableDefinition({
        indexes: [
          {
            name: 'memberships_active_idx',
            entries: [{ column: 'userId', order: 'desc' }, { column: raw`lower("groupId")` }],
            unique: true,
            where: raw`"deletedAt" IS NULL`,
            include: ['groupId'],
          },
        ],
      }),
    );
    expect(statements[1]).toBe(
      'CREATE UNIQUE INDEX "memberships_active_idx" ON "memberships" ("userId" DESC, (lower("groupId"))) ' +
        'INCLUDE ("groupId") WHERE "deletedAt" IS NULL;',
    );
  });

  it('should generate a table-level FOREIGN KEY with its declared actions', () => {
    const sql = generator
      .generateCreateTableFromDefinition(
        tableDefinition({
          foreignKeys: [
            {
              name: 'memberships_user_fk',
              columns: ['userId'],
              references: { table: 'users', columns: ['id'] },
              onDelete: 'CASCADE',
              onUpdate: 'NO ACTION',
            },
          ],
        }),
      )
      .join('\n');
    expect(sql).toContain(
      'CONSTRAINT "memberships_user_fk" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION',
    );
  });

  it('should name an unnamed table-level FOREIGN KEY after its table and columns', () => {
    const sql = generator
      .generateCreateTableFromDefinition(
        tableDefinition({
          foreignKeys: [
            {
              columns: ['userId'],
              references: { table: 'users', columns: ['id'] },
              onDelete: 'NO ACTION',
              onUpdate: 'NO ACTION',
            },
          ],
        }),
      )
      .join('\n');
    expect(sql).toContain('CONSTRAINT "memberships__userId_fk" FOREIGN KEY ("userId")');
  });

  it('should generate ADD CONSTRAINT for a foreign key added to an existing table', () => {
    const sql = generator.generateOperation({
      type: 'addForeignKey',
      tableName: 'memberships',
      foreignKey: {
        columns: ['groupId'],
        references: { table: 'groups', columns: ['id'] },
        onDelete: 'SET NULL',
        onUpdate: 'CASCADE',
      },
    });
    expect(sql).toEqual([
      'ALTER TABLE "memberships" ADD CONSTRAINT "memberships__groupId_fk" ' +
        'FOREIGN KEY ("groupId") REFERENCES "groups" ("id") ON DELETE SET NULL ON UPDATE CASCADE;',
    ]);
  });

  /** SQLite cannot add a constraint to an existing table, so this has to fail rather than emit invalid DDL. */
  it('should reject adding a foreign key where the dialect cannot alter constraints', () => {
    const sqliteGenerator = new SqlSchemaGenerator(new SqliteDialect());
    expect(() =>
      sqliteGenerator.generateOperation({
        type: 'addForeignKey',
        tableName: 'memberships',
        foreignKey: {
          columns: ['groupId'],
          references: { table: 'groups', columns: ['id'] },
          onDelete: 'NO ACTION',
          onUpdate: 'NO ACTION',
        },
      }),
    ).toThrow('rebuilds the table');
  });

  it('should reject altering a column in place where the dialect rebuilds the table instead', () => {
    const column = namedColumn('label');
    expect(() =>
      new SqlSchemaGenerator(new SqliteDialect()).generateAlterTable({
        type: 'alter',
        tableName: 'memberships',
        columns: [{ from: column, to: { ...column, nullable: false } }],
      }),
    ).toThrow('sqlite: Altering the column "label" rebuilds the table');
  });

  it('should rename a table with ALTER TABLE, which MySQL takes too', () => {
    const rename = { type: 'renameTable', oldName: 'old', newName: 'new' } as const;
    expect(generator.generateOperation(rename)).toEqual(['ALTER TABLE "old" RENAME TO "new";']);
    expect(new SqlSchemaGenerator(new MySqlDialect()).generateOperation(rename)).toEqual([
      'ALTER TABLE `old` RENAME TO `new`;',
    ]);
  });
  describe('generateCreateSchema', () => {
    it('should emit cross-entity foreign keys, which the per-entity path dropped', () => {
      const generator = new SqlSchemaGenerator(new PostgresDialect());
      const sql = generator.generateCreateSchema([TestUser, TestPost]);

      const creates = sql.filter((s) => s.startsWith('CREATE TABLE'));
      const fks = sql.filter((s) => s.includes('ADD CONSTRAINT'));

      expect(creates).toHaveLength(2);
      // Constraints come after every table, so a cyclic relation graph is creatable at all.
      expect(creates.every((s) => !s.includes('FOREIGN KEY'))).toBe(true);
      expect(fks.some((s) => s.includes('ALTER TABLE "blog_posts"') && s.includes('"TestUser"'))).toBe(true);
    });

    it('should keep constraints inline on SQLite, which cannot ALTER one in', () => {
      const generator = new SqlSchemaGenerator(new SqliteDialect());
      const sql = generator.generateCreateSchema([TestUser, TestPost]);

      // SQLite resolves a foreign key target lazily, so a forward reference is fine and no ALTER is
      // needed. `features.rebuildsTables` is what selects this shape.
      expect(sql.some((s) => s.includes('ADD CONSTRAINT'))).toBe(false);
      expect(sql.some((s) => s.startsWith('CREATE TABLE') && s.includes('FOREIGN KEY'))).toBe(true);
    });

    it('should narrow creation with `only` while still resolving constraints against the full graph', () => {
      const generator = new SqlSchemaGenerator(new PostgresDialect());
      const sql = generator.generateCreateSchema([TestUser, TestPost], { only: ['blog_posts'] });

      expect(sql.filter((s) => s.startsWith('CREATE TABLE'))).toHaveLength(1);
      expect(sql.some((s) => s.includes('ALTER TABLE "blog_posts"') && s.includes('"TestUser"'))).toBe(true);
    });
  });

  describe('generateDropSchema', () => {
    it('should drop dependents before the tables they reference', () => {
      const generator = new SqlSchemaGenerator(new PostgresDialect());
      const sql = generator.generateDropSchema([TestUser, TestPost]);

      // Declaration order puts `TestUser` first, so a reverse-of-declaration drop would emit it last and
      // be rejected: `blog_posts` still references it.
      expect(sql).toEqual(['DROP TABLE "blog_posts";', 'DROP TABLE "TestUser";']);
    });

    /** A cycle has no drop order, so the foreign keys the database holds come off first, another schema's included. */
    it('should drop the existing foreign keys first where no CASCADE takes them', () => {
      const posts = mockTableNode('blog_posts', [{ name: 'authorId' }]);
      posts.externalForeignKeys.push({
        name: 'blog_posts_editor_fk',
        columns: ['editorId'],
        references: { table: 'crm.editor', columns: ['id'] },
      });
      const existing = new SchemaAST();
      existing.addTable(posts);
      const options = { ifExists: true, cascade: true, existing };

      expect(new SqlSchemaGenerator(new MySqlDialect()).generateDropSchema([TestUser, TestPost], options)).toEqual([
        'ALTER TABLE `blog_posts` DROP FOREIGN KEY `blog_posts_editor_fk`;',
        'DROP TABLE IF EXISTS `blog_posts`;',
        'DROP TABLE IF EXISTS `TestUser`;',
      ]);
      expect(new SqlSchemaGenerator(new PostgresDialect()).generateDropSchema([TestUser, TestPost], options)).toEqual([
        'DROP TABLE IF EXISTS "blog_posts" CASCADE;',
        'DROP TABLE IF EXISTS "TestUser" CASCADE;',
      ]);
    });

    it('should add CASCADE only where the dialect has it, since a cycle has no valid order', () => {
      const options = { ifExists: true, cascade: true };

      expect(new SqlSchemaGenerator(new PostgresDialect()).generateDropSchema([TestUser], options)).toEqual([
        'DROP TABLE IF EXISTS "TestUser" CASCADE;',
      ]);
      expect(new SqlSchemaGenerator(new MySqlDialect()).generateDropSchema([TestUser], options)).toEqual([
        'DROP TABLE IF EXISTS `TestUser`;',
      ]);
    });
  });
});

@Entity()
class DiffUser {
  @Id({ type: Number }) id?: number;
  @Field({ type: String, columnType: 'varchar', length: 255 }) name?: string | null;
  @Field({ type: String, columnType: 'varchar', length: 100 }) email?: string | null;
  @Field({ type: String, columnType: 'varchar', length: 255, index: true }) status?: string | null;
}

@Entity()
class DefaultsEntity {
  @Id({ type: Number }) id?: number;
  @Field({ type: String, columnType: 'varchar', length: 20, defaultValue: 'active' }) status?: string | null;
  @Field({ type: Number, columnType: 'int', defaultValue: 0 }) attempts?: number | null;
}

@Entity()
class ComputedEntity {
  @Id({ type: Number }) id?: number;
  @Field({ type: Number, computed: raw`1 + 1` }) total?: number | null;
}

describe('SqlSchemaGenerator diffs (Postgres)', () => {
  const generator = new SqlSchemaGenerator(new PostgresDialect());

  it('should refuse to drop a key whose constraint introspection did not name', () => {
    const diff: SchemaDiff = { tableName: 'users', type: 'alter', primaryKey: { from: { columns: ['id'] } } };
    expect(() => generator.generateAlterTable(diff)).toThrow(
      'Cannot drop the primary key of "users": postgres names the constraint',
    );
  });

  it('should type a foreign key as the key it points at', () => {
    @Entity()
    class RefTarget {
      @Id({ type: String, columnType: 'uuid' }) id?: string;
    }
    @Entity()
    class RefSource {
      @Id({ type: Number }) id?: number;
      @Field({ references: () => RefTarget }) ownerId?: string | null;
    }
    const { ownerId } = getMeta(RefSource).fields;
    assertDefined(ownerId);
    expect(sqlTypeOf(new PostgresDialect(), ownerId)).toBe('UUID');
  });

  /** One resolution for the column a table gets and the type this reports, so the two cannot disagree. */
  it('should type a foreign key as its create statement does, its own columnType first, and a shared key never serial', () => {
    @Entity()
    class Account {
      @Id({ type: Number }) id?: number;
    }
    @Entity()
    class AccountProfile {
      @Id({ type: Number, references: () => Account }) id?: number;
      @Field({ references: () => Account, columnType: 'int' }) backupId?: number | null;
    }
    const { id, backupId } = getMeta(AccountProfile).fields;
    assertDefined(id);
    assertDefined(backupId);
    const ddl = generator.generateCreateSchema([Account, AccountProfile]).join('\n');

    expect(ddl).toContain('CREATE TABLE "AccountProfile" (\n  "id" BIGINT NOT NULL,\n  "backupId" INTEGER,');
  });

  it('should comment a column of a table that has no comment of its own', () => {
    @Entity()
    class Commented {
      @Id({ type: Number }) id?: number;
      @Field({ type: String, comment: 'Shown to users' }) label?: string | null;
    }
    const statements = generator.generateCreateSchema([Commented]);
    expect(statements).toContainEqual(expect.stringContaining('COMMENT ON COLUMN'));
    expect(statements.filter((statement) => statement.startsWith('COMMENT ON TABLE'))).toEqual([]);
  });

  /** Reversing a key change restores only the side that had one: a key added from none drops, one removed adds back. */
  it('should reverse a primary key change that added a key, or removed one', () => {
    const added = generator.generateAlterTable(
      reverseDiff({
        tableName: 'users',
        type: 'alter',
        primaryKey: { to: { columns: ['id'], name: 'users__id_pk' } },
      }),
    );
    expect(added).toEqual([expect.stringContaining('DROP CONSTRAINT')]);

    const removed = generator.generateAlterTable(
      reverseDiff({
        tableName: 'users',
        type: 'alter',
        primaryKey: { from: { columns: ['id'], name: 'users_pkey' } },
      }),
    );
    expect(removed).toEqual([expect.stringContaining('ADD CONSTRAINT')]);
  });

  /** A key nothing named gets the name this generator derives, the one a rollback then drops it by. */
  it('should add a key under the derived name where the change names none', () => {
    const diff: SchemaDiff = { tableName: 'users', type: 'alter', primaryKey: { to: { columns: ['id'] } } };
    expect(generator.generateAlterTable(diff)).toEqual([
      'ALTER TABLE "users" ADD CONSTRAINT "users__id_pk" PRIMARY KEY ("id");',
    ]);
  });

  /** A `schema_locked` table, CockroachDB's default, drops its key only beside the key replacing it. */
  it('should replace a key in one statement on CockroachDB', () => {
    const diff: SchemaDiff = {
      tableName: 'users',
      type: 'alter',
      primaryKey: {
        from: { columns: ['id'], name: 'users_pkey' },
        to: { columns: ['id', 'org'], name: 'users__id_org_pk' },
      },
    };
    expect(new SqlSchemaGenerator(new CockroachDialect()).generateAlterTable(diff)).toEqual([
      'ALTER TABLE "users" DROP CONSTRAINT "users_pkey", ADD CONSTRAINT "users__id_org_pk" PRIMARY KEY ("id", "org");',
    ]);
  });

  /** Before the column it no longer holds is dropped, which CockroachDB refuses while the key holds it. */
  it('should replace a key before dropping a column it held', () => {
    const org = {
      name: 'org',
      type: 'BIGINT',
      nullable: false,
      isPrimaryKey: true,
      isAutoIncrement: false,
      isUnique: false,
    };
    const diff: SchemaDiff = {
      tableName: 'users',
      type: 'alter',
      columns: [{ from: org }],
      primaryKey: {
        from: { columns: ['id', 'org'], name: 'users__id_org_pk' },
        to: { columns: ['id'], name: 'users__id_pk' },
      },
    };
    expect(new SqlSchemaGenerator(new CockroachDialect()).generateAlterTable(diff)).toEqual([
      'ALTER TABLE "users" DROP CONSTRAINT "users__id_org_pk", ADD CONSTRAINT "users__id_pk" PRIMARY KEY ("id");',
      'ALTER TABLE "users" DROP COLUMN "org";',
    ]);
  });

  it('should diff nothing where the desired schema has no table for the entity', () => {
    const current = generator.buildAST([DiffUser]).getTable('DiffUser');
    expect(generator.diffSchema(DiffUser, current, new SchemaAST())).toBeUndefined();
  });

  it('should detect new columns', () => {
    const currentSchema = mockSqlTableNode('DiffUser', [
      { name: 'id', sql: 'INTEGER', isPrimaryKey: true, isAutoIncrement: true },
      { name: 'name', sql: 'VARCHAR', length: 255 },
    ]);

    const diff = generator.diffSchema(DiffUser, currentSchema);

    expect(diff).toBeDefined();
    expect(diff?.type).toBe('alter');
    expect(added(diff?.columns)).toHaveLength(2);
    expect(added(diff?.columns)[0].name).toBe('email');
    expect(added(diff?.columns)[1].name).toBe('status');
  });

  it('should detect a column whose type changed', () => {
    const currentSchema = mockSqlTableNode('DiffUser', [
      { name: 'id', sql: 'BIGINT', isPrimaryKey: true, isAutoIncrement: true },
      { name: 'name', sql: 'TEXT' },
      { name: 'email', sql: 'VARCHAR', length: 50 },
      { name: 'status', sql: 'VARCHAR', length: 255 },
    ]);

    const diff = generator.diffSchema(DiffUser, currentSchema);

    expect(diff).toBeDefined();
    expect(diff?.type).toBe('alter');
    expect(alterations(diff?.columns)).toHaveLength(2);
    expect(alterations(diff?.columns).map((c) => c.to.name)).toContain('name');
    expect(alterations(diff?.columns).map((c) => c.to.name)).toContain('email');
  });

  it('should detect columns to drop', () => {
    const currentSchema = mockSqlTableNode('DiffUser', [
      { name: 'id', sql: 'INTEGER', isPrimaryKey: true, isAutoIncrement: true },
      { name: 'name', sql: 'VARCHAR', length: 255 },
      { name: 'email', sql: 'VARCHAR', length: 100 },
      { name: 'status', sql: 'VARCHAR', length: 255 },
      { name: 'old_col', sql: 'VARCHAR' },
    ]);

    const diff = generator.diffSchema(DiffUser, currentSchema);

    expect(diff).toBeDefined();
    expect(diff?.type).toBe('alter');
    expect(dropped(diff?.columns).map((column) => column.name)).toEqual(['old_col']);
  });

  it('should add an index the entity declares and the table has not got', () => {
    const currentSchema = mockSqlTableNode('DiffUser', [
      { name: 'id', sql: 'INTEGER', isPrimaryKey: true, isAutoIncrement: true },
      { name: 'name', sql: 'VARCHAR', length: 255 },
      { name: 'email', sql: 'VARCHAR', length: 100 },
      { name: 'status', sql: 'VARCHAR', length: 255 },
    ]);

    const diff = generator.diffSchema(DiffUser, currentSchema);

    expect(added(diff?.columns)).toEqual([]);
    expect(added(diff?.indexes).map((index) => index.name)).toEqual(['DiffUser__status_idx']);
  });

  it('should leave alone an index the entity never declared', () => {
    const currentSchema = mockSqlTableNode('DiffUser', [
      { name: 'id', sql: 'INTEGER', isPrimaryKey: true, isAutoIncrement: true },
      { name: 'name', sql: 'VARCHAR', length: 255 },
      { name: 'email', sql: 'VARCHAR', length: 100 },
      { name: 'status', sql: 'VARCHAR', length: 255 },
    ]);
    // With their real entries, as an introspector reports them: an index is recognised by the
    // columns it covers, so the one the entity declares is already present under any name.
    currentSchema.indexes.push(
      { name: 'DiffUser__status_idx', table: currentSchema, entries: [{ column: 'status' }], unique: false },
      { name: 'made_by_a_dba_idx', table: currentSchema, entries: [{ column: 'email' }], unique: false },
    );

    expect(generator.diffSchema(DiffUser, currentSchema)).toBeUndefined();
  });

  /**
   * The reason an index is recognised by its shape. Renaming the convention, an engine truncating a
   * name past its identifier limit, and SQLite reporting a name it made up all produce the same
   * thing: an index that is already there under a name we did not choose. Keying on the name
   * re-created it on every migration, forever.
   */
  it('should leave alone an index it would have named differently', () => {
    const currentSchema = mockSqlTableNode('DiffUser', [
      { name: 'id', sql: 'INTEGER', isPrimaryKey: true, isAutoIncrement: true },
      { name: 'name', sql: 'VARCHAR', length: 255 },
      { name: 'email', sql: 'VARCHAR', length: 100 },
      { name: 'status', sql: 'VARCHAR', length: 255 },
    ]);
    currentSchema.indexes.push({
      name: 'whatever_the_dba_called_it',
      table: currentSchema,
      entries: [{ column: 'status' }],
      unique: false,
    });

    expect(generator.diffSchema(DiffUser, currentSchema)).toBeUndefined();
  });

  /** Same columns, different uniqueness: a different index, which no engine can alter into the other. */
  it('should rebuild an index whose uniqueness differs', () => {
    const currentSchema = mockSqlTableNode('DiffUser', [
      { name: 'id', sql: 'INTEGER', isPrimaryKey: true, isAutoIncrement: true },
      { name: 'name', sql: 'VARCHAR', length: 255 },
      { name: 'email', sql: 'VARCHAR', length: 100 },
      { name: 'status', sql: 'VARCHAR', length: 255 },
    ]);
    currentSchema.indexes.push({
      name: 'DiffUser__status_idx',
      table: currentSchema,
      entries: [{ column: 'status' }],
      unique: true,
    });

    const diff = generator.diffSchema(DiffUser, currentSchema);
    assertDefined(diff);

    expect(added(diff.indexes)).toEqual([]);
    expect(generator.generateAlterTable(diff)).toEqual([
      'DROP INDEX IF EXISTS "DiffUser__status_idx";',
      'CREATE INDEX IF NOT EXISTS "DiffUser__status_idx" ON "DiffUser" ("status");',
    ]);
    expect(generator.generateAlterTable(reverseDiff(diff))).toEqual([
      'DROP INDEX IF EXISTS "DiffUser__status_idx";',
      'CREATE UNIQUE INDEX IF NOT EXISTS "DiffUser__status_idx" ON "DiffUser" ("status");',
    ]);
  });

  /**
   * Engines disagree on how they report "no default": MariaDB says `null` where MySQL says nothing at
   * all. Read as different values, that asked to `MODIFY` every nullable column on every sync.
   */
  it('should read a reported null default and an absent one as the same', () => {
    expect(generator.defaultsEqual(undefined, null)).toBe(true);
    expect(generator.defaultsEqual(null, undefined)).toBe(true);
    expect(generator.defaultsEqual(null, null)).toBe(true);
    expect(generator.defaultsEqual('active', null)).toBe(false);
    expect(generator.defaultsEqual(0, undefined)).toBe(false);
  });

  it('should detect a genuinely changed default', () => {
    const currentSchema = defaultsTableNode('inactive');

    const diff = generator.diffSchema(DefaultsEntity, currentSchema);

    expect(alterations(diff?.columns)).toHaveLength(1);
    expect(alterations(diff?.columns)[0].from.defaultValue).toBe('inactive');
    expect(alterations(diff?.columns)[0].to.defaultValue).toBe('active');
  });

  it('should detect a default replacing an existing NULL default', () => {
    const currentSchema = defaultsTableNode(null);

    const diff = generator.diffSchema(DefaultsEntity, currentSchema);

    expect(alterations(diff?.columns)).toHaveLength(1);
    expect(alterations(diff?.columns)[0].to.defaultValue).toBe('active');
  });

  it('should detect a default added to a column that had none', () => {
    const currentSchema = defaultsTableNode(undefined);

    const diff = generator.diffSchema(DefaultsEntity, currentSchema);

    expect(alterations(diff?.columns)).toHaveLength(1);
    expect(alterations(diff?.columns)[0].to.defaultValue).toBe('active');
  });

  /** An inlined computed field is a query-time expression, never a column, so it must not show up as a diff. */
  it('should skip inlined computed fields', () => {
    const currentSchema = mockSqlTableNode('ComputedEntity', [
      { name: 'id', sql: 'INTEGER', isPrimaryKey: true, isAutoIncrement: true },
    ]);

    expect(generator.diffSchema(ComputedEntity, currentSchema)).toBeUndefined();
  });

  /** `DefaultsEntity` as it stands in the database, with `status`'s stored default under test. */
  function defaultsTableNode(statusDefault: unknown) {
    return mockSqlTableNode('DefaultsEntity', [
      { name: 'id', sql: 'INTEGER', isPrimaryKey: true, isAutoIncrement: true },
      { name: 'status', sql: 'VARCHAR', length: 20, defaultValue: statusDefault },
      { name: 'attempts', sql: 'INTEGER', defaultValue: '0' },
    ]);
  }

  it('should produce the SQL of an alter', () => {
    const sql = generator.generateAlterTable({
      tableName: 'users',
      type: 'alter',
      columns: [
        {
          to: {
            name: 'age',
            type: 'INTEGER',
            nullable: true,
            isPrimaryKey: false,
            isAutoIncrement: false,
            isUnique: false,
          },
        },
        { from: namedColumn('old_name') },
      ],
      indexes: [
        { to: { name: 'age_idx', entries: [{ column: 'age' }], unique: false } },
        { from: { name: 'old_idx', entries: [{ column: 'old_name' }], unique: false } },
      ],
    });

    expect(sql).toContain('ALTER TABLE "users" ADD COLUMN "age" INTEGER;');
    expect(sql).toContain('ALTER TABLE "users" DROP COLUMN "old_name";');
    expect(sql).toContain('CREATE INDEX IF NOT EXISTS "age_idx" ON "users" ("age");');
    expect(sql).toContain('DROP INDEX IF EXISTS "old_idx";');
  });
});

@Entity({ name: 'users' })
class UsersTable {
  @Id({ type: Number }) id?: number;
  @Field({ type: String }) name?: string | null;
}

/** A row per dialect, so a new dialect is a row rather than a branch in each test. */
const everyDialect = [
  {
    dialect: new PostgresDialect(),
    serialId: 'BIGINT GENERATED BY DEFAULT AS IDENTITY',
    tableOptions: '',
    booleanType: 'BOOLEAN',
    comment: '',
  },
  {
    dialect: new CockroachDialect(),
    serialId: 'BIGINT GENERATED BY DEFAULT AS IDENTITY',
    tableOptions: '',
    booleanType: 'BOOLEAN',
    comment: '',
  },
  {
    dialect: new MySqlDialect(),
    serialId: 'BIGINT AUTO_INCREMENT',
    tableOptions: 'ENGINE=InnoDB',
    booleanType: 'TINYINT(1)',
    comment: " COMMENT 'Testing'",
  },
  {
    dialect: new MariaDialect(),
    serialId: 'BIGINT AUTO_INCREMENT',
    tableOptions: 'ENGINE=InnoDB',
    booleanType: 'TINYINT(1)',
    comment: " COMMENT 'Testing'",
  },
  {
    dialect: new SqliteDialect(),
    serialId: 'INTEGER PRIMARY KEY AUTOINCREMENT',
    tableOptions: '',
    booleanType: 'INTEGER',
    comment: '',
  },
];

describe('SqlSchemaGenerator on every dialect', () => {
  describe.each(everyDialect)(
    'Dialect: $dialect.dialectName',
    ({ dialect, serialId, tableOptions, booleanType, comment }) => {
      const generator = new SqlSchemaGenerator(dialect);

      it('should generate correct CREATE TABLE SQL', () => {
        const sql = generator.generateCreateSchema([UsersTable]).join('\n');

        expect(sql).toContain('CREATE TABLE');
        expect(sql).toContain('users');
        expect(sql).toContain('name');
        expect(sql).toContain(serialId);
        expect(sql).toContain(tableOptions);
      });

      it('should generate correct DROP TABLE SQL', () => {
        expect(generator.generateOperation({ type: 'dropTable', tableName: 'users', ifExists: true })).toEqual([
          `DROP TABLE IF EXISTS ${dialect.escapeId('users')};`,
        ]);
      });

      it('should generate correct SQL type for Boolean', () => {
        expect(sqlTypeOf(dialect, { type: Boolean })).toBe(booleanType);
      });

      it('should comment a column inline only where the engine keeps one there', () => {
        const column = {
          name: 'c',
          type: 'INT',
          nullable: true,
          isPrimaryKey: false,
          isAutoIncrement: false,
          isUnique: false,
        };

        expect(tableDdlFor(dialect).columnDefinition({ ...column, comment: 'Testing' })).toBe(
          `${dialect.escapeId('c')} INT${comment}`,
        );
      });
    },
  );
});

describe('SqlSchemaGenerator creating a table only where it is missing', () => {
  it('should say so in the statement where the engine has the clause', () => {
    const [sql] = new SqlSchemaGenerator(new PostgresDialect()).generateCreateSchema([UsersTable], {
      ifNotExists: true,
    });
    expect(sql).toMatch(/^CREATE TABLE IF NOT EXISTS "users"/);
  });

  // T-SQL has no `IF NOT EXISTS` on a table: without the guard, a second create fails outright.
  it('should guard it with a lookup on SQL Server', () => {
    const [sql] = new SqlSchemaGenerator(new MsSqlDialect()).generateCreateSchema([UsersTable], { ifNotExists: true });
    expect(sql).toMatch(/^IF OBJECT_ID\(N'"users"', N'U'\) IS NULL CREATE TABLE "users"/);
  });
});

describe('triggers', () => {
  @Trigger({ on: 'afterInsert', name: 'audit', run: { postgres: () => raw`PERFORM 1;` } })
  @Entity({ name: 'GenPost' })
  class GenPost {
    @Id({ type: Number }) id?: number;
    @Field({ type: String }) title?: string | null;
  }

  const generator = new SqlSchemaGenerator(new PostgresDialect());

  afterAll(() => removeEntity(GenPost));

  // A table's drop takes its triggers along, but not the function the Postgres family keeps each body in.
  it('should drop the function of each trigger after its table', () => {
    const [audit] = generator.buildAST([GenPost]).getTable('GenPost')?.triggers ?? [];
    assertDefined(audit);
    expect(generator.generateDropSchema([GenPost], { ifExists: true })).toEqual([
      'DROP TABLE IF EXISTS "GenPost";',
      `DROP FUNCTION IF EXISTS "${audit.name}"();`,
    ]);
  });

  /** A table the catalogue says is absent left no function, and CockroachDB refuses one named in a schema not made yet. */
  it('should drop no function for a table the database does not have', () => {
    expect(generator.generateDropSchema([GenPost], { ifExists: true, existing: new SchemaAST() })).toEqual([
      'DROP TABLE IF EXISTS "GenPost";',
    ]);
  });

  /** The table as declared, with `installed` standing for what the catalogue reports. */
  const installedAs = (...installed: TriggerSchema[]) => {
    const table = generator.buildAST([GenPost]).getTable('GenPost');
    assertDefined(table);
    const declared = [...table.triggers];
    table.triggers.splice(0, table.triggers.length, ...installed);
    return { table, declared };
  };
  const alter = (table: TableNode) => {
    const diff = generator.diffSchema(GenPost, table);
    assertDefined(diff);
    return diff;
  };

  it('should install what the entity declares with its table', () => {
    expect(generator.generateCreateSchema([GenPost]).join('\n')).toMatch(
      /CREATE TRIGGER "_uql_GenPost__audit_[0-9a-f]{6}"/,
    );
  });

  // What a drift check reads: once installed as declared, there is nothing left to run.
  it('should report no change where what is installed is what the entity declares', () => {
    const { table, declared } = installedAs();
    table.triggers.push(...declared);
    expect(generator.diffSchema(GenPost, table)).toBeUndefined();
  });

  // The `_uql` prefix is what says it is ours to drop; anything else on the table is left alone.
  it('should drop an installed trigger the entity no longer declares, with its function', () => {
    const { table } = installedAs(
      { name: '_uql_GenPost__gone_000000', statements: [] },
      { name: 'handwritten', statements: [] },
    );
    const sql = generator.generateAlterTable(alter(table)).join('\n');
    expect(sql).toContain('DROP TRIGGER IF EXISTS "_uql_GenPost__gone_000000" ON "GenPost";');
    expect(sql).toContain('DROP FUNCTION IF EXISTS "_uql_GenPost__gone_000000"();');
    expect(sql).not.toContain('handwritten');
  });

  // Exactly the inverse: what the change created goes, and what it dropped comes back as it stood.
  it('should roll back by dropping what it created and restoring what it dropped', () => {
    const { table, declared } = installedAs({ name: '_uql_GenPost__gone_000000', statements: ['CREATE TRIGGER gone'] });
    const [audit] = declared;
    assertDefined(audit);
    expect(generator.generateAlterTable(reverseDiff(alter(table)))).toEqual([
      `DROP TRIGGER IF EXISTS "${audit.name}" ON "GenPost";`,
      `DROP FUNCTION IF EXISTS "${audit.name}"();`,
      'CREATE TRIGGER gone;',
    ]);
  });

  // Postgres refuses to alter a column a trigger names, so a kept trigger comes off and goes back on.
  it('should take a kept trigger off around a column it changes', () => {
    const { table, declared } = installedAs();
    table.triggers.push(...declared);
    const title = table.columns.get('title');
    assertDefined(title);
    table.columns.set('title', { ...title, nullable: false });
    const [audit] = declared;
    assertDefined(audit);
    const sql = generator.generateAlterTable(alter(table));
    expect(sql[0]).toBe(`DROP TRIGGER IF EXISTS "${audit.name}" ON "GenPost";`);
    expect(sql.at(-1)).toMatch(/^CREATE TRIGGER/);
  });
});

/** A plain nullable text column named `name`, the whole column a dropped one keeps. */
function namedColumn(name: string): ColumnSchema {
  return { name, type: 'TEXT', nullable: true, isPrimaryKey: false, isAutoIncrement: false, isUnique: false };
}
