import { getMeta } from '../entity/index.js';
import type {
  DialectFeatures,
  DialectName,
  EntityMeta,
  ExtraOptions,
  FieldOptions,
  InsertIdSource,
  NamingStrategy,
  Query,
  QueryOptions,
  QueryWhere,
  Type,
} from '../type/index.js';
import { parseQueryLock } from '../type/index.js';
import { QueryRaw } from '../type/queryRaw.js';
import { applyFilters, assertWhere } from '../util/dialect.util.js';
import { aggregateOf, definedEntries, entityName, someKey } from '../util/index.js';
import { qualifyName } from '../util/sql.util.js';
import { UqlUsageError } from '../util/uqlError.js';
import { groupClauses, isGroupOp } from './operators.js';

/**
 * Options for initializing a dialect.
 */
export interface DialectOptions {
  readonly namingStrategy?: NamingStrategy;
  /** Default schema for entities naming none; unset leaves them unqualified. See {@link AbstractDialect.resolveSchema}. */
  readonly schema?: string;
}

/**
 * The dialect's share of a pool's {@link ExtraOptions}: what changes the SQL rather than the
 * connection. Every pool builds its dialect through this, so a new option lands here instead of in
 * each pool's constructor.
 */
export function dialectOptionsFrom(extra: ExtraOptions | undefined): DialectOptions {
  return { namingStrategy: extra?.namingStrategy, schema: extra?.schema };
}

/** A name a score can be projected under: what every engine takes as a key, with nothing to escape. */
const PLAIN_NAME = /^[A-Za-z_][A-Za-z0-9_]*$/;

/**
 * Base abstract class for all database dialects (SQL and NoSQL).
 */
export abstract class AbstractDialect {
  abstract readonly dialectName: DialectName;

  /** How this dialect surfaces the IDs generated by an INSERT (see {@link InsertIdSource}). */
  abstract readonly insertIdSource: InsertIdSource;

  /** What the engine has. Each concrete dialect declares its own. */
  abstract readonly features: DialectFeatures;

  readonly namingStrategy: NamingStrategy | undefined;

  constructor(protected readonly options: DialectOptions = {}) {
    this.namingStrategy = options.namingStrategy;
  }

  /**
   * The table's own name, unqualified, applying naming strategy if necessary. Also the alias the
   * root table gets once {@link resolveTableName} qualifies it, so it has to stay a single
   * identifier: columns are prefixed with it, and a dotted prefix escapes as one identifier that
   * nothing declared.
   */
  resolveTableAlias<E>(meta: EntityMeta<E>): string {
    // A name the author wrote is the table, verbatim: there is nothing to derive. Only a name that
    // stood in for one is a derivation, which is what a naming strategy exists to make.
    const name = entityName(meta);
    return meta.derivedName && this.namingStrategy ? this.namingStrategy.tableName(name) : name;
  }

  /**
   * Where the table lives: {@link resolveTableAlias} behind its schema, when one applies. The schema
   * skips the naming strategy - it names an object the author wrote out, and snake_casing `myCrm`
   * would point at one that does not exist.
   */
  resolveTableName<E>(meta: EntityMeta<E>): string {
    return qualifyName(this.resolveTableAlias(meta), this.resolveSchema(meta));
  }

  /**
   * Which schema an entity is read from: its own wins over the pool's default, the way its `name`
   * wins over the naming strategy. `undefined` is an answer, not a gap - the table stays unqualified
   * and resolves through the connection's `search_path`, which is what every deployment predating
   * this option relies on.
   */
  resolveSchema<E>(meta: EntityMeta<E>): string | undefined {
    return this.features.schemas ? (meta.schema ?? this.options.schema) : undefined;
  }

  /**
   * Refuses a `$lock` the engine cannot take, so a caller never believes rows are held that are not.
   * The SQLite family locks the database rather than its rows and MongoDB has no row lock at all;
   * {@link AbstractSqlDialect} adds what a lock over a join needs on top.
   */
  assertLockSupported<E>(_entity: Type<E>, q: Query<E>): void {
    if (parseQueryLock(q.$lock) && !this.features.rowLocks) {
      throw new UqlUsageError(`${this.dialectName} does not support row-level locking ($lock)`);
    }
  }

  /**
   * Resolve the column/field name for a property, applying naming strategy if necessary.
   */
  resolveColumnName(key: string, field: FieldOptions | undefined): string {
    if (!field || field.name !== key || !this.namingStrategy) {
      return field?.name ?? key;
    }
    return this.namingStrategy.columnName(field.name);
  }

  /**
   * {@link resolveColumnName} for a field key of `meta` - the form query builders need, so reading a
   * column never depends on looking the field up by hand first. `MongoDialect` overrides it to map the
   * primary key to `_id`.
   */
  columnOf<E>(meta: EntityMeta<E>, key: string): string {
    return this.resolveColumnName(key, meta.fields[key]);
  }

  /**
   * Refuses a name a `$sort` projects a score under that a row already has - a field, the column it is
   * stored under, a relation - or that MongoDB or UQL reserves, or that is no plain name: it is a key of
   * every row it comes back in, and MongoDB would read `$` or `.` in one as an operator or a path.
   */
  assertProjectable<E>(meta: EntityMeta<E>, alias: string): void {
    if (!PLAIN_NAME.test(alias)) {
      throw new UqlUsageError(`$project '${alias}' is no plain name: letters, digits and '_', not led by a digit`);
    }
    if (alias === '_id' || alias.startsWith('_uql')) {
      throw new UqlUsageError(`$project '${alias}' is a name MongoDB or UQL reserves`);
    }
    if (
      definedEntries(meta.fields).some(([key, field]) => key === alias || this.resolveColumnName(key, field) === alias)
    ) {
      throw new UqlUsageError(`$project '${alias}' collides with a field of '${entityName(meta)}'`);
    }
    if (alias in meta.relations) {
      throw new UqlUsageError(`$project '${alias}' collides with a relation of '${entityName(meta)}'`);
    }
  }

  /**
   * A `$where` with the entity's active filters merged in - the only way any dialect should enter a
   * new query scope, so a scope cannot be rendered with its `security: true` filters skipped.
   * Recursion within one scope renders the returned map directly instead.
   */
  protected scopedWhere<E>(meta: EntityMeta<E>, where: QueryWhere<E> = {}, opts?: QueryOptions): QueryWhere<E> {
    assertWhere(meta, where);
    return applyFilters(meta, where, opts);
  }

  /**
   * Whether a `$where` reads a relation at any depth: filters by one, or by a relation aggregate. What
   * cannot host that read - a MongoDB filter, a write without {@link DialectFeatures.correlatedWrites} -
   * has the rows it names read first.
   */
  constrainsRelations<E>(entity: Type<E>, where: QueryWhere<E> | undefined): boolean {
    if (!where) {
      return false;
    }
    const meta = getMeta(entity);
    return someKey(where, (key) =>
      isGroupOp(key)
        ? groupClauses(key, where[key]).some((it) => !(it instanceof QueryRaw) && this.constrainsRelations(entity, it))
        : !!meta.relations[key] || aggregateOf(meta.fields[key]) !== undefined,
    );
  }
}
