import type { IndexType } from '../schema/types.js';
import {
  type DriverCapabilities,
  type EntityMeta,
  type FieldOptions,
  type JsonColumnType,
  type Query,
  type QueryContext,
  QueryRaw,
  type QueryTextSearchOptions,
  type SqlDialectFeatures,
  type Type,
  type VectorDistance,
  type VectorMetric,
} from '../type/index.js';
import { fulltextConfig, fulltextIndexOver, hasVectorNear, textSearchFields } from '../util/dialect.util.js';
import { escapeSingleQuotes } from '../util/sqlLiteral.js';
import type { DialectOptions } from './abstractDialect.js';
import { AbstractSqlDialect, type CarriedFields, type RelationRows } from './abstractSqlDialect.js';
import { JSON_PULL_ALIAS, RELATION_ROW_ALIAS } from './aliases.js';
import { BYTES_PREFIX } from './hydrateColumn.js';
import { type JsonAccessMode, type JsonSlot, jsonSetTarget } from './jsonSql.js';
import { resolveVectorCast, toSparsevecLiteral } from './vectorCast.js';

/** A Postgres-wire dialect's options: the base's, and how its driver binds a parameter. */
export type PgLikeDialectOptions = DialectOptions & {
  readonly driverCapabilities?: Partial<DriverCapabilities>;
};

/** Each metric's pgvector distance operator, and the infix of the operator class its index is built with. */
export const PG_VECTOR_METRICS: ReadonlyMap<VectorDistance, VectorMetric> = new Map([
  ['cosine', { op: '<=>', index: 'cosine' }],
  ['l2', { op: '<->', index: 'l2' }],
  ['inner', { op: '<#>', index: 'ip' }],
  ['l1', { op: '<+>', index: 'l1' }],
]);

/** pgvector's HNSW candidate list, the one setting an iterative scan goes with. */
const HNSW_EF_SEARCH = 'hnsw.ef_search';

/** What the Postgres-wire engines have. */
export const PG_FEATURES: SqlDialectFeatures = {
  ifNotExists: true,
  indexIfNotExists: true,
  schemas: true,
  dropTableCascade: true,
  foreignKeyAlter: true,
  primaryKeyAlter: true,
  generatedColumnAdd: true,
  commentSyntax: 'statement',
  vectorIndexRequiresNotNull: false,
  vectorSupportsLength: true,
  vectorBytes: false,
  supportsTimestamptz: true,
  stringSizing: 'bounded-text',
  supportsUnsigned: false,
  serverSideCursors: true,
  correlatedWrites: true,
  rowLocks: true,
  rowLockWithWindow: false,
  rowLockOf: true,
  orderedUpsertReturning: true,
  orderedJsonAggregates: true,
  narrowVectorTypes: false,
  vectorTuningNeedsTransaction: true,
  serialDeclaresPrimaryKey: false,
};

/** What Postgres and CockroachDB share: JSONB, full-text search, pgvector's operators, and the upsert. */
export abstract class PgLikeSqlDialect extends AbstractSqlDialect {
  /** How the driver binds a parameter: node-`pg`'s, unless the pool states its own. */
  readonly driverCapabilities: DriverCapabilities;

  constructor(options: PgLikeDialectOptions = {}) {
    super(options);
    this.driverCapabilities = { nativeArrays: true, explicitJsonCast: false, ...options.driverCapabilities };
  }

  override readonly features: SqlDialectFeatures = PG_FEATURES;

  override readonly escapeIdChar = '"';
  // Shared default for both dialects. CockroachDB docs flag sequential PKs as a hotspotting risk
  // under heavy concurrent insert load (writes concentrate on one range); this default still beats
  // `SERIAL` (CockroachDB's `unique_rowid()`, a ~64-bit value that overflows JS's safe-integer
  // range). High-throughput CockroachDB users should override this per-entity with a UUID PK.
  override readonly autoIncrementSuffix: string = 'GENERATED BY DEFAULT AS IDENTITY';
  override readonly tableOptions = '';
  override readonly beginTransactionCommand = 'BEGIN';
  override readonly commitTransactionCommand = 'COMMIT';
  override readonly rollbackTransactionCommand = 'ROLLBACK';
  override readonly alterColumnStrategy = 'separate-clauses';

  /**
   * `JSON_AGG` of each row whole, read through a LATERAL projection of the columns it answers under:
   * the sort terms carried out beside them order it without joining the object, and no function call
   * builds it, so a wide row meets no argument limit. `json` has no equality, so under a parent's
   * `DISTINCT` the array is compared as `jsonb`.
   */
  protected override appendRelationArray(ctx: QueryContext, rows: RelationRows): void {
    const { from, pairs, order } = this.derivedRelation(ctx, rows);
    const row = this.escapeId(RELATION_ROW_ALIAS, true);
    const columns = pairs.map(([, column]) => column).join(', ');
    const array = /*sql*/ `(SELECT COALESCE(JSON_AGG(${row}${order ? ` ORDER BY ${order}` : ''}), '[]'::json) FROM ${from} CROSS JOIN LATERAL (SELECT ${columns}) ${row})`;
    ctx.append(rows.distinct ? `${array}::jsonb` : array);
  }

  /**
   * What JSON would round or cannot spell crosses it as text, for the field's own decode to read back:
   * a column declared numeric, whatever it decodes as, a vector, and bytes as hex.
   */
  protected override readonly carriedFields = {
    numeric: (expr) => `${expr}::text`,
    vector: (expr) => `${expr}::text`,
    blob: (expr) => `${this.escape(BYTES_PREFIX)} || ENCODE(${expr}, 'hex')`,
  } satisfies CarriedFields;

  /** `$N` placeholders carry their own index, so the upsert's assignments need no scratch context. */
  protected override readonly upsertUpdateBindsInPlace = true;
  override readonly insertIdSource = 'returning';
  override readonly maxBindValues: number = 65535;

  override readonly vectorMetrics = PG_VECTOR_METRICS;

  /**
   * The setting each vector index type reads for "how much of the index to explore". They are not the
   * same quantity - `ef_search` is a candidate-list size, `probes` a count of lists - which is why
   * `$candidates` is documented in the index's own units rather than as a portable number.
   */
  protected readonly annSettings: ReadonlyMap<IndexType, string> = new Map<IndexType, string>([
    ['hnsw', HNSW_EF_SEARCH],
    ['ivfflat', 'ivfflat.probes'],
  ]);

  /**
   * `SET LOCAL hnsw.ef_search = N`, plus `hnsw.iterative_scan = strict_order` where the query also filters
   * by distance, which would otherwise drop rows the candidate list missed.
   */
  override vectorTuningStatements<E>(meta: EntityMeta<E>, q: Query<E>): readonly string[] {
    const indexType = this.tunedVectorIndex(meta, q)?.type;
    const setting = indexType ? this.annSettings.get(indexType) : undefined;
    if (!setting) {
      return [];
    }
    const statements = [`SET LOCAL ${setting} = ${q.$candidates}`];
    if (setting === HNSW_EF_SEARCH && hasVectorNear(q.$where)) {
      statements.push('SET LOCAL hnsw.iterative_scan = strict_order');
    }
    return statements;
  }

  override normalizeValue(value: unknown): unknown {
    if (value != null && typeof value === 'object' && Array.isArray(value)) {
      return this.driverCapabilities.nativeArrays ? value : toPgArray(value);
    }
    return super.normalizeValue(value);
  }

  override placeholder(index: number): string {
    return `$${index}`;
  }

  /**
   * `<document> @@ WEBSEARCH_TO_TSQUERY(...)`, under the `$config` asked for, else that of the fulltext
   * index over these fields, which the planner serves it from. `WEBSEARCH_TO_TSQUERY` takes free-form
   * input (quoted phrases, `or`, `-negation`) and never raises a syntax error, unlike `TO_TSQUERY`.
   */
  protected override appendTextSearch<E>(
    ctx: QueryContext,
    _entity: Type<E>,
    meta: EntityMeta<E>,
    search: QueryTextSearchOptions<E>,
  ): void {
    const keys = textSearchFields(meta, search);
    const index = fulltextIndexOver(meta, keys);
    const config = search.$config ?? (index && fulltextConfig(index));
    const columns = keys.map((key) => this.escapeId(this.resolveColumnName(key, meta.fields[key])));
    ctx.append(`${this.textSearchTarget(columns, config)} @@ ${this.textQueryFn}(${this.textConfigArg(config)}`);
    ctx.addValue(search.$value);
    ctx.append(')');
  }

  /**
   * The document, `TO_TSVECTOR('english'::regconfig, COALESCE("a", '') || ' ' || COALESCE("b", ''))`, a
   * `NULL` column read as empty rather than emptying it all. The config is a literal: an index is built
   * over one, and a bound one reaches it only where the driver leaves the parameter untyped.
   */
  override textSearchTarget(columns: readonly string[], config?: string): string {
    const document = columns.map((column) => `COALESCE(${column}, '')`).join(` || ' ' || `);
    return `TO_TSVECTOR(${this.textConfigArg(config)}${document})`;
  }

  /** A config as the text-search functions' first argument, or nothing, for the server's default. */
  private textConfigArg(config: string | undefined): string {
    return config === undefined ? '' : `${this.escape(config)}${this.textConfigCast}, `;
  }

  /** How a config literal is typed, and the function reading a search's text: CockroachDB lacks both of these. */
  protected readonly textConfigCast: string = '::regconfig';
  protected readonly textQueryFn: string = 'WEBSEARCH_TO_TSQUERY';

  protected override jsonContains(ctx: QueryContext, slot: JsonSlot, values: readonly unknown[]): string {
    return `${this.jsonValue(slot)} @> ${this.jsonVal(ctx, values)}`;
  }

  protected override jsonLength(slot: JsonSlot): string {
    return `JSONB_ARRAY_LENGTH(${this.jsonArray(slot)})`;
  }

  /** Each element stays `jsonb`, so it is read as any path is: `->` for the value, `->>` for its text. */
  protected override jsonElemFrom(slot: JsonSlot, alias: string): string {
    return `JSONB_ARRAY_ELEMENTS(${this.jsonArray(slot)}) AS ${alias}`;
  }

  protected override jsonIsArray(slot: JsonSlot): string {
    return `JSONB_TYPEOF(${this.jsonValue(slot)}) = 'array'`;
  }

  /** The array at `slot`, NULL where the value there is none: the array functions fail the whole read on one. */
  private jsonArray(slot: JsonSlot): string {
    return `CASE WHEN ${this.jsonIsArray(slot)} THEN ${this.jsonValue(slot)} END`;
  }

  protected override jsonElemDoc(alias: string): string {
    return alias;
  }

  /** `->` down the path and `->>` for its text, the document's own text being `#>> '{}'`. */
  protected override jsonPathReading(escapedColumn: string, path: string, mode: 'json' | 'text'): string {
    if (!path) {
      return mode === 'json' ? escapedColumn : `(${escapedColumn} #>> '{}')`;
    }
    const segments = path.split('.');
    return segments.reduce((expr, segment, index) => {
      const op = mode === 'text' && index === segments.length - 1 ? '->>' : '->';
      return `(${expr}${op}'${escapeSingleQuotes(segment)}')`;
    }, escapedColumn);
  }

  /** A number only where the value is one: the cast throws on any other text, failing the whole read. */
  override jsonPathExpr(escapedColumn: string, path: string, mode: JsonAccessMode): string {
    const read = super.jsonPathExpr(escapedColumn, path, mode);
    if (mode !== 'numeric') {
      return read;
    }
    return `CASE WHEN JSONB_TYPEOF(${this.jsonValue({ base: escapedColumn, path })}) = 'number' THEN ${read} END`;
  }

  protected override get regexpOp(): string {
    return '~';
  }

  protected override readonly caseInsensitiveMatch = 'ilike';

  protected override get neOp(): string {
    return 'IS DISTINCT FROM';
  }

  /**
   * One array parameter, which a context that inlines values has none of: it lists them instead. The
   * array takes its type from `operand`, so it needs none of the casts `bind` would give each value.
   */
  protected override formatIn(
    ctx: QueryContext,
    operand: string,
    values: unknown[],
    negate: boolean,
    bind: (value: unknown) => string,
  ): string {
    if (!values.length || ctx.inlineValues) {
      return super.formatIn(ctx, operand, values, negate, bind);
    }
    const ph = this.addValue(ctx, values);
    return negate ? `${operand} <> ALL(${ph})` : `${operand} = ANY(${ph})`;
  }

  protected override numericCast(expr: string): string {
    return `(${expr})::numeric`;
  }

  protected override appendJsonValue(ctx: QueryContext, value: unknown, type: JsonColumnType): void {
    ctx.append(this.jsonVal(ctx, value, type));
  }

  /**
   * pgvector needs the cast to pick the right type, and `sparsevec` needs its own literal: the dense
   * `[1,0,2]` every other type takes is rejected as "invalid input syntax for type sparsevec".
   */
  protected override appendVectorValue(ctx: QueryContext, value: readonly unknown[], field?: FieldOptions): void {
    const vectorType = this.supportedVectorType(resolveVectorCast(field));
    ctx.addValue(vectorType === 'sparsevec' ? toSparsevecLiteral(value) : `[${value.join(',')}]`);
    ctx.append(`::${vectorType}`);
  }

  /**
   * `create_if_missing => false` keeps an absent key (and a NULL column) untouched, and a value that is no
   * array is set back as it is; `WITH ORDINALITY` keeps the surviving elements in their original order.
   */
  protected override jsonPullKey(
    ctx: QueryContext,
    expr: string,
    escapedCol: string,
    key: string,
    value: unknown,
  ): string {
    const slot = { base: escapedCol, path: key };
    const kept = `SELECT JSONB_AGG(${JSON_PULL_ALIAS}.val ORDER BY ${JSON_PULL_ALIAS}.ord) FROM JSONB_ARRAY_ELEMENTS(${this.jsonValue(slot)}) WITH ORDINALITY AS ${JSON_PULL_ALIAS}(val, ord) WHERE ${JSON_PULL_ALIAS}.val <> ${this.jsonVal(ctx, value)}`;
    const pulled = `CASE WHEN ${this.jsonIsArray(slot)} THEN COALESCE((${kept}), '[]'::jsonb) ELSE COALESCE(${this.jsonValue(slot)}, 'null') END`;
    return `JSONB_SET(${expr}, '{${escapeSingleQuotes(key)}}', ${pulled}, false)`;
  }

  /**
   * The plain values merge as one bound object; a `raw()` one is an SQL expression rather than JSON,
   * so it merges through `JSONB_BUILD_OBJECT` and is evaluated in place - stringified with the rest,
   * it would land as `{}`.
   */
  protected override jsonSet(
    ctx: QueryContext,
    expr: string,
    set: Record<string, unknown>,
    field?: FieldOptions,
  ): string {
    const entries = Object.entries(set);
    const merged = this.jsonVal(ctx, Object.fromEntries(entries.filter(([, value]) => !(value instanceof QueryRaw))));
    const raws = entries.flatMap(([key, value]) =>
      value instanceof QueryRaw
        ? [` || JSONB_BUILD_OBJECT('${escapeSingleQuotes(key)}', ${this.rawFragment(ctx, value)})`]
        : [],
    );
    return `${jsonSetTarget(expr, field, `'{}'::jsonb`)} || ${merged}${raws.join('')}`;
  }

  /** The only fragment that references `expr` twice - safe here because placeholders are numbered. */
  protected override jsonPush(ctx: QueryContext, expr: string, push: Record<string, unknown>): string {
    return Object.entries(push).reduce((acc, [key, value]) => {
      const escapedKey = escapeSingleQuotes(key);
      const ph = this.jsonVal(ctx, value);
      return `JSONB_SET(${acc}, '{${escapedKey}}', COALESCE((${acc})->'${escapedKey}', '[]'::jsonb) || JSONB_BUILD_ARRAY(${ph}))`;
    }, expr);
  }

  protected override jsonUnset(ctx: QueryContext, expr: string, unset: readonly string[]): string {
    return `(${expr}) - ${this.addValue(ctx, [...unset])}::text[]`;
  }

  /** Postgres binds JSON with a numbered placeholder and an explicit cast, per driver capability. */
  protected override jsonScalarParam(ctx: QueryContext, value: unknown): string {
    return this.jsonVal(ctx, value);
  }

  /**
   * Helper to add a JSON value to context with appropriate stringification and cast.
   */
  private jsonVal(ctx: QueryContext, value: unknown, type: JsonColumnType = 'jsonb'): string {
    if (value instanceof QueryRaw) return this.rawFragment(ctx, value);
    if (value == null) return `${this.addValue(ctx, null)}::${type}`;

    const json = JSON.stringify(value);
    const ph = this.addValue(ctx, json);
    return this.driverCapabilities.explicitJsonCast ? `(${ph}::text)::${type}` : `${ph}::${type}`;
  }
}

/**
 * Converts a JS array to a Postgres array literal string: `{"val1","val2"}`.
 * Safely handles nesting and escaping of special characters.
 */
function toPgArray(arr: unknown[]): string {
  const elements = arr.map((val) => {
    if (val == null) return 'NULL';
    if (Array.isArray(val)) return toPgArray(val);
    if (typeof val === 'boolean') return val ? 'true' : 'false';
    if (val instanceof Uint8Array || (typeof Buffer !== 'undefined' && Buffer.isBuffer(val))) {
      const hex = Array.from(val)
        .map((b) => b.toString(16).padStart(2, '0'))
        .join('');
      return `"\\\\x${hex}"`;
    }
    const str = String(val);
    const escaped = str.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
    return `"${escaped}"`;
  });
  return `{${elements.join(',')}}`;
}
